<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: model_config.proto

namespace Inference\ModelOptimizationPolicy\Cuda\GraphSpec;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>inference.ModelOptimizationPolicy.Cuda.GraphSpec.LowerBound</code>
 */
class LowerBound extends \Google\Protobuf\Internal\Message
{
    /**
     *\@\@      .. cpp:var:: int32 batch_size
     *\@\@
     *\@\@         The batch size of the CUDA graph. If 'max_batch_size' is 0,
     *\@\@         'batch_size' must be set to 0. Otherwise, 'batch_size' must
     *\@\@         be set to value between 1 and 'max_batch_size'.
     *\@\@
     *
     * Generated from protobuf field <code>int32 batch_size = 1;</code>
     */
    protected $batch_size = 0;
    /**
     *\@\@      .. cpp:var:: map<string, Shape> input
     *\@\@
     *\@\@         The specification of the inputs. 'Shape' is the shape of
     *\@\@         the input without batching dimension.
     *\@\@
     *
     * Generated from protobuf field <code>map<string, .inference.ModelOptimizationPolicy.Cuda.GraphSpec.Shape> input = 2;</code>
     */
    private $input;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $batch_size
     *          \@\@      .. cpp:var:: int32 batch_size
     *          \@\@
     *          \@\@         The batch size of the CUDA graph. If 'max_batch_size' is 0,
     *          \@\@         'batch_size' must be set to 0. Otherwise, 'batch_size' must
     *          \@\@         be set to value between 1 and 'max_batch_size'.
     *          \@\@
     *     @type array|\Google\Protobuf\Internal\MapField $input
     *          \@\@      .. cpp:var:: map<string, Shape> input
     *          \@\@
     *          \@\@         The specification of the inputs. 'Shape' is the shape of
     *          \@\@         the input without batching dimension.
     *          \@\@
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\ModelConfig::initOnce();
        parent::__construct($data);
    }

    /**
     *\@\@      .. cpp:var:: int32 batch_size
     *\@\@
     *\@\@         The batch size of the CUDA graph. If 'max_batch_size' is 0,
     *\@\@         'batch_size' must be set to 0. Otherwise, 'batch_size' must
     *\@\@         be set to value between 1 and 'max_batch_size'.
     *\@\@
     *
     * Generated from protobuf field <code>int32 batch_size = 1;</code>
     * @return int
     */
    public function getBatchSize()
    {
        return $this->batch_size;
    }

    /**
     *\@\@      .. cpp:var:: int32 batch_size
     *\@\@
     *\@\@         The batch size of the CUDA graph. If 'max_batch_size' is 0,
     *\@\@         'batch_size' must be set to 0. Otherwise, 'batch_size' must
     *\@\@         be set to value between 1 and 'max_batch_size'.
     *\@\@
     *
     * Generated from protobuf field <code>int32 batch_size = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setBatchSize($var)
    {
        GPBUtil::checkInt32($var);
        $this->batch_size = $var;

        return $this;
    }

    /**
     *\@\@      .. cpp:var:: map<string, Shape> input
     *\@\@
     *\@\@         The specification of the inputs. 'Shape' is the shape of
     *\@\@         the input without batching dimension.
     *\@\@
     *
     * Generated from protobuf field <code>map<string, .inference.ModelOptimizationPolicy.Cuda.GraphSpec.Shape> input = 2;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getInput()
    {
        return $this->input;
    }

    /**
     *\@\@      .. cpp:var:: map<string, Shape> input
     *\@\@
     *\@\@         The specification of the inputs. 'Shape' is the shape of
     *\@\@         the input without batching dimension.
     *\@\@
     *
     * Generated from protobuf field <code>map<string, .inference.ModelOptimizationPolicy.Cuda.GraphSpec.Shape> input = 2;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setInput($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::MESSAGE, \Inference\ModelOptimizationPolicy\Cuda\GraphSpec\Shape::class);
        $this->input = $arr;

        return $this;
    }

}

