# Per-install secrets for Synaplan.
#
# Each value gets its own entropy label so the secrets stay independent of each
# other: a leaked realtime key must not reveal the key that encrypts the stored
# AI provider credentials.
#
# The derived values are also written to the app's own data directory, and that
# copy wins on every later start. Reason: derive_entropy is keyed with the
# device seed in ${UMBREL_ROOT}/db/umbrel-seed, which is NOT part of an umbrelOS
# backup — a backup holds `home` and `app-data` only, and a missing seed is
# regenerated at random. Restoring this app onto a different device would
# therefore derive a new database password while the restored data directory
# still expects the old one, locking the app out of its own database with no
# way for the user to recover it. Keeping the secrets next to the data they
# unlock makes the restore consistent. It is also where umbrelOS says it wants
# app secrets to live (see the comment on the seed in modules/apps/apps.ts).
#
# BOOTSTRAP_ADMIN_PASSWORD is deliberately not part of this: it uses Umbrel's
# APP_PASSWORD so the manifest's deterministicPassword shows the user the very
# password the administrator account was created with. It is only consumed
# while no administrator exists, so a changed value cannot lock anyone out.

synaplan_secrets_file="${EXPORTS_APP_DATA_DIR}/secrets.env"

if [ -f "${synaplan_secrets_file}" ]; then
	. "${synaplan_secrets_file}"
fi

# Derive whatever the file did not provide. This also covers a truncated file
# and secrets added by a later release.
synaplan_derived="false"
for synaplan_secret in \
	APP_SECRET:app-secret \
	TOKEN_SECRET:token-secret \
	DB_PASSWORD:db-password \
	DB_ROOT_PASSWORD:db-root-password \
	REALTIME_API_KEY:realtime-api-key \
	REALTIME_TOKEN_SECRET:realtime-token-secret; do
	synaplan_name="APP_SYNAPLAN_${synaplan_secret%%:*}"
	synaplan_label="${synaplan_secret##*:}"

	eval "synaplan_value=\${${synaplan_name}:-}"
	if [ -z "${synaplan_value}" ]; then
		eval "export ${synaplan_name}=\"\$(derive_entropy \"\${app_entropy_identifier}-${synaplan_label}\")\""
		synaplan_derived="true"
	else
		eval "export ${synaplan_name}"
	fi
done

if [ "${synaplan_derived}" = "true" ]; then
	# Written through a temporary file so a start interrupted mid-write cannot
	# leave a half-read secrets file behind. A failure here is not fatal: the
	# values are valid on this device either way.
	{
		umask 077
		{
			echo "# Generated by Synaplan's exports.sh. Keep this file with the data"
			echo "# directory it belongs to — restoring one without the other locks"
			echo "# the app out of its database."
			echo "APP_SYNAPLAN_APP_SECRET='${APP_SYNAPLAN_APP_SECRET}'"
			echo "APP_SYNAPLAN_TOKEN_SECRET='${APP_SYNAPLAN_TOKEN_SECRET}'"
			echo "APP_SYNAPLAN_DB_PASSWORD='${APP_SYNAPLAN_DB_PASSWORD}'"
			echo "APP_SYNAPLAN_DB_ROOT_PASSWORD='${APP_SYNAPLAN_DB_ROOT_PASSWORD}'"
			echo "APP_SYNAPLAN_REALTIME_API_KEY='${APP_SYNAPLAN_REALTIME_API_KEY}'"
			echo "APP_SYNAPLAN_REALTIME_TOKEN_SECRET='${APP_SYNAPLAN_REALTIME_TOKEN_SECRET}'"
		} >"${synaplan_secrets_file}.tmp" &&
			mv "${synaplan_secrets_file}.tmp" "${synaplan_secrets_file}"
	} || true
fi

unset synaplan_secrets_file synaplan_derived synaplan_secret synaplan_name synaplan_label synaplan_value
