<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: model_config.proto

namespace Inference\ModelWarmup;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 *\@\@
 *\@\@  .. cpp:var:: message Input
 *\@\@
 *\@\@     Meta data associated with an input.
 *\@\@
 *
 * Generated from protobuf message <code>inference.ModelWarmup.Input</code>
 */
class Input extends \Google\Protobuf\Internal\Message
{
    /**
     *\@\@    .. cpp:var:: DataType data_type
     *\@\@
     *\@\@       The data-type of the input.
     *\@\@
     *
     * Generated from protobuf field <code>.inference.DataType data_type = 1;</code>
     */
    protected $data_type = 0;
    /**
     *\@\@    .. cpp:var:: int64 dims (repeated)
     *\@\@
     *\@\@       The shape of the input tensor, not including the batch dimension.
     *\@\@
     *
     * Generated from protobuf field <code>repeated int64 dims = 2;</code>
     */
    private $dims;
    protected $input_data_type;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $data_type
     *          \@\@    .. cpp:var:: DataType data_type
     *          \@\@
     *          \@\@       The data-type of the input.
     *          \@\@
     *     @type int[]|string[] $dims
     *          \@\@    .. cpp:var:: int64 dims (repeated)
     *          \@\@
     *          \@\@       The shape of the input tensor, not including the batch dimension.
     *          \@\@
     *     @type bool $zero_data
     *          \@\@
     *          \@\@    .. cpp:var:: bool zero_data
     *          \@\@
     *          \@\@       The identifier for using zeros as input data. Note that the
     *          \@\@       value of 'zero_data' will not be checked, instead, zero data
     *          \@\@       will be used as long as the field is set.
     *          \@\@
     *     @type bool $random_data
     *          \@\@
     *          \@\@    .. cpp:var:: bool random_data
     *          \@\@
     *          \@\@       The identifier for using random data as input data. Note that
     *          \@\@       the value of 'random_data' will not be checked, instead,
     *          \@\@       random data will be used as long as the field is set.
     *          \@\@
     *     @type string $input_data_file
     *          \@\@    .. cpp:var:: string input_data_file
     *          \@\@
     *          \@\@       The file whose content will be used as raw input data in
     *          \@\@       row-major order. The file must be provided in a sub-directory
     *          \@\@       'warmup' under the model directory. The file contents should be
     *          \@\@       in binary format. For TYPE_STRING data-type, an element is
     *          \@\@       represented by a 4-byte unsigned integer giving the length
     *          \@\@       followed by the actual bytes.
     *          \@\@
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\ModelConfig::initOnce();
        parent::__construct($data);
    }

    /**
     *\@\@    .. cpp:var:: DataType data_type
     *\@\@
     *\@\@       The data-type of the input.
     *\@\@
     *
     * Generated from protobuf field <code>.inference.DataType data_type = 1;</code>
     * @return int
     */
    public function getDataType()
    {
        return $this->data_type;
    }

    /**
     *\@\@    .. cpp:var:: DataType data_type
     *\@\@
     *\@\@       The data-type of the input.
     *\@\@
     *
     * Generated from protobuf field <code>.inference.DataType data_type = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setDataType($var)
    {
        GPBUtil::checkEnum($var, \Inference\DataType::class);
        $this->data_type = $var;

        return $this;
    }

    /**
     *\@\@    .. cpp:var:: int64 dims (repeated)
     *\@\@
     *\@\@       The shape of the input tensor, not including the batch dimension.
     *\@\@
     *
     * Generated from protobuf field <code>repeated int64 dims = 2;</code>
     * @return RepeatedField<int>|RepeatedField<string>
     */
    public function getDims()
    {
        return $this->dims;
    }

    /**
     *\@\@    .. cpp:var:: int64 dims (repeated)
     *\@\@
     *\@\@       The shape of the input tensor, not including the batch dimension.
     *\@\@
     *
     * Generated from protobuf field <code>repeated int64 dims = 2;</code>
     * @param int[]|string[] $var
     * @return $this
     */
    public function setDims($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT64);
        $this->dims = $arr;

        return $this;
    }

    /**
     *\@\@
     *\@\@    .. cpp:var:: bool zero_data
     *\@\@
     *\@\@       The identifier for using zeros as input data. Note that the
     *\@\@       value of 'zero_data' will not be checked, instead, zero data
     *\@\@       will be used as long as the field is set.
     *\@\@
     *
     * Generated from protobuf field <code>bool zero_data = 3;</code>
     * @return bool
     */
    public function getZeroData()
    {
        return $this->readOneof(3);
    }

    public function hasZeroData()
    {
        return $this->hasOneof(3);
    }

    /**
     *\@\@
     *\@\@    .. cpp:var:: bool zero_data
     *\@\@
     *\@\@       The identifier for using zeros as input data. Note that the
     *\@\@       value of 'zero_data' will not be checked, instead, zero data
     *\@\@       will be used as long as the field is set.
     *\@\@
     *
     * Generated from protobuf field <code>bool zero_data = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setZeroData($var)
    {
        GPBUtil::checkBool($var);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     *\@\@
     *\@\@    .. cpp:var:: bool random_data
     *\@\@
     *\@\@       The identifier for using random data as input data. Note that
     *\@\@       the value of 'random_data' will not be checked, instead,
     *\@\@       random data will be used as long as the field is set.
     *\@\@
     *
     * Generated from protobuf field <code>bool random_data = 4;</code>
     * @return bool
     */
    public function getRandomData()
    {
        return $this->readOneof(4);
    }

    public function hasRandomData()
    {
        return $this->hasOneof(4);
    }

    /**
     *\@\@
     *\@\@    .. cpp:var:: bool random_data
     *\@\@
     *\@\@       The identifier for using random data as input data. Note that
     *\@\@       the value of 'random_data' will not be checked, instead,
     *\@\@       random data will be used as long as the field is set.
     *\@\@
     *
     * Generated from protobuf field <code>bool random_data = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setRandomData($var)
    {
        GPBUtil::checkBool($var);
        $this->writeOneof(4, $var);

        return $this;
    }

    /**
     *\@\@    .. cpp:var:: string input_data_file
     *\@\@
     *\@\@       The file whose content will be used as raw input data in
     *\@\@       row-major order. The file must be provided in a sub-directory
     *\@\@       'warmup' under the model directory. The file contents should be
     *\@\@       in binary format. For TYPE_STRING data-type, an element is
     *\@\@       represented by a 4-byte unsigned integer giving the length
     *\@\@       followed by the actual bytes.
     *\@\@
     *
     * Generated from protobuf field <code>string input_data_file = 5;</code>
     * @return string
     */
    public function getInputDataFile()
    {
        return $this->readOneof(5);
    }

    public function hasInputDataFile()
    {
        return $this->hasOneof(5);
    }

    /**
     *\@\@    .. cpp:var:: string input_data_file
     *\@\@
     *\@\@       The file whose content will be used as raw input data in
     *\@\@       row-major order. The file must be provided in a sub-directory
     *\@\@       'warmup' under the model directory. The file contents should be
     *\@\@       in binary format. For TYPE_STRING data-type, an element is
     *\@\@       represented by a 4-byte unsigned integer giving the length
     *\@\@       followed by the actual bytes.
     *\@\@
     *
     * Generated from protobuf field <code>string input_data_file = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setInputDataFile($var)
    {
        GPBUtil::checkString($var, True);
        $this->writeOneof(5, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getInputDataType()
    {
        return $this->whichOneof("input_data_type");
    }

}

