<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: model_config.proto

namespace Inference\ModelVersionPolicy;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *&#64;&#64;  .. cpp:var:: message Latest
 *&#64;&#64;
 *&#64;&#64;     Serve only the latest version(s) of a model. This is
 *&#64;&#64;     the default policy.
 *&#64;&#64;
 *
 * Generated from protobuf message <code>inference.ModelVersionPolicy.Latest</code>
 */
class Latest extends \Google\Protobuf\Internal\Message
{
    /**
     *&#64;&#64;    .. cpp:var:: uint32 num_versions
     *&#64;&#64;
     *&#64;&#64;       Serve only the 'num_versions' highest-numbered versions. T
     *&#64;&#64;       The default value of 'num_versions' is 1, indicating that by
     *&#64;&#64;       default only the single highest-number version of a
     *&#64;&#64;       model will be served.
     *&#64;&#64;
     *
     * Generated from protobuf field <code>uint32 num_versions = 1;</code>
     */
    protected $num_versions = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $num_versions
     *          &#64;&#64;    .. cpp:var:: uint32 num_versions
     *          &#64;&#64;
     *          &#64;&#64;       Serve only the 'num_versions' highest-numbered versions. T
     *          &#64;&#64;       The default value of 'num_versions' is 1, indicating that by
     *          &#64;&#64;       default only the single highest-number version of a
     *          &#64;&#64;       model will be served.
     *          &#64;&#64;
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\ModelConfig::initOnce();
        parent::__construct($data);
    }

    /**
     *&#64;&#64;    .. cpp:var:: uint32 num_versions
     *&#64;&#64;
     *&#64;&#64;       Serve only the 'num_versions' highest-numbered versions. T
     *&#64;&#64;       The default value of 'num_versions' is 1, indicating that by
     *&#64;&#64;       default only the single highest-number version of a
     *&#64;&#64;       model will be served.
     *&#64;&#64;
     *
     * Generated from protobuf field <code>uint32 num_versions = 1;</code>
     * @return int
     */
    public function getNumVersions()
    {
        return $this->num_versions;
    }

    /**
     *&#64;&#64;    .. cpp:var:: uint32 num_versions
     *&#64;&#64;
     *&#64;&#64;       Serve only the 'num_versions' highest-numbered versions. T
     *&#64;&#64;       The default value of 'num_versions' is 1, indicating that by
     *&#64;&#64;       default only the single highest-number version of a
     *&#64;&#64;       model will be served.
     *&#64;&#64;
     *
     * Generated from protobuf field <code>uint32 num_versions = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setNumVersions($var)
    {
        GPBUtil::checkUint32($var);
        $this->num_versions = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Latest::class, \Inference\ModelVersionPolicy_Latest::class);

