<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc_service.proto

namespace Inference\ModelMetadataResponse;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *&#64;&#64;
 *&#64;&#64;  .. cpp:var:: message TensorMetadata
 *&#64;&#64;
 *&#64;&#64;     Metadata for a tensor.
 *&#64;&#64;
 *
 * Generated from protobuf message <code>inference.ModelMetadataResponse.TensorMetadata</code>
 */
class TensorMetadata extends \Google\Protobuf\Internal\Message
{
    /**
     *&#64;&#64;
     *&#64;&#64;    .. cpp:var:: string name
     *&#64;&#64;
     *&#64;&#64;       The tensor name.
     *&#64;&#64;
     *
     * Generated from protobuf field <code>string name = 1;</code>
     */
    protected $name = '';
    /**
     *&#64;&#64;
     *&#64;&#64;    .. cpp:var:: string datatype
     *&#64;&#64;
     *&#64;&#64;       The tensor data type.
     *&#64;&#64;
     *
     * Generated from protobuf field <code>string datatype = 2;</code>
     */
    protected $datatype = '';
    /**
     *&#64;&#64;
     *&#64;&#64;    .. cpp:var:: int64 shape (repeated)
     *&#64;&#64;
     *&#64;&#64;       The tensor shape. A variable-size dimension is represented
     *&#64;&#64;       by a -1 value.
     *&#64;&#64;
     *
     * Generated from protobuf field <code>repeated int64 shape = 3;</code>
     */
    private $shape;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *          &#64;&#64;
     *          &#64;&#64;    .. cpp:var:: string name
     *          &#64;&#64;
     *          &#64;&#64;       The tensor name.
     *          &#64;&#64;
     *     @type string $datatype
     *          &#64;&#64;
     *          &#64;&#64;    .. cpp:var:: string datatype
     *          &#64;&#64;
     *          &#64;&#64;       The tensor data type.
     *          &#64;&#64;
     *     @type int[]|string[]|\Google\Protobuf\Internal\RepeatedField $shape
     *          &#64;&#64;
     *          &#64;&#64;    .. cpp:var:: int64 shape (repeated)
     *          &#64;&#64;
     *          &#64;&#64;       The tensor shape. A variable-size dimension is represented
     *          &#64;&#64;       by a -1 value.
     *          &#64;&#64;
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\GrpcService::initOnce();
        parent::__construct($data);
    }

    /**
     *&#64;&#64;
     *&#64;&#64;    .. cpp:var:: string name
     *&#64;&#64;
     *&#64;&#64;       The tensor name.
     *&#64;&#64;
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     *&#64;&#64;
     *&#64;&#64;    .. cpp:var:: string name
     *&#64;&#64;
     *&#64;&#64;       The tensor name.
     *&#64;&#64;
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     *&#64;&#64;
     *&#64;&#64;    .. cpp:var:: string datatype
     *&#64;&#64;
     *&#64;&#64;       The tensor data type.
     *&#64;&#64;
     *
     * Generated from protobuf field <code>string datatype = 2;</code>
     * @return string
     */
    public function getDatatype()
    {
        return $this->datatype;
    }

    /**
     *&#64;&#64;
     *&#64;&#64;    .. cpp:var:: string datatype
     *&#64;&#64;
     *&#64;&#64;       The tensor data type.
     *&#64;&#64;
     *
     * Generated from protobuf field <code>string datatype = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setDatatype($var)
    {
        GPBUtil::checkString($var, True);
        $this->datatype = $var;

        return $this;
    }

    /**
     *&#64;&#64;
     *&#64;&#64;    .. cpp:var:: int64 shape (repeated)
     *&#64;&#64;
     *&#64;&#64;       The tensor shape. A variable-size dimension is represented
     *&#64;&#64;       by a -1 value.
     *&#64;&#64;
     *
     * Generated from protobuf field <code>repeated int64 shape = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getShape()
    {
        return $this->shape;
    }

    /**
     *&#64;&#64;
     *&#64;&#64;    .. cpp:var:: int64 shape (repeated)
     *&#64;&#64;
     *&#64;&#64;       The tensor shape. A variable-size dimension is represented
     *&#64;&#64;       by a -1 value.
     *&#64;&#64;
     *
     * Generated from protobuf field <code>repeated int64 shape = 3;</code>
     * @param int[]|string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setShape($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT64);
        $this->shape = $arr;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(TensorMetadata::class, \Inference\ModelMetadataResponse_TensorMetadata::class);

