export const selectors = {
  login: {
    email: '#email',
    password: '#password',
    submit: 'button[type="submit"]',
    signUpLink: '[data-testid="link-signup"]',
  },
  register: {
    fullName: '[data-testid="input-full-name"]',
    email: '[data-testid="input-email"]',
    password: '[data-testid="input-password"]',
    confirmPassword: '[data-testid="input-confirm-password"]',
    submit: '[data-testid="btn-register"]',
    successSection: '[data-testid="section-registration-success"]',
    backToLoginBtn: '[data-testid="btn-goto-login"]',
  },
  verifyEmail: {
    successState: '[data-testid="state-success"]',
    goToLoginLink: '[data-testid="link-success-login"]',
  },
  header: {
    modeToggle: '[data-testid="btn-mode-toggle"]',
  },
  nav: {
    sidebar: '[data-testid="nav-sidebar"]',
  },
  models: {
    page: '[data-testid="page-config-ai-models"]',
    capabilityItem: '[data-testid="item-capability"]',
    capabilityDropdown: '[data-testid="btn-model-dropdown"]',
    capabilityOption: '[data-testid="btn-model-option"]',
  },
  rag: {
    page: '[data-testid="page-rag-search"]',
    queryInput: '[data-testid="input-query"]',
    searchButton: '[data-testid="btn-search"]',
    searchSummary: '[data-testid="text-search-summary"]',
    resultsSection: '[data-testid="section-results"]',
    resultItem: '[data-testid="item-result"]',
  },
  chat: {
    newChatButton: '[data-testid="btn-chat-new-dropdown"]',
    chatBtnToggle: '[data-testid="btn-chat-toggle"]',
    textInput: '[data-testid="input-chat-message"]',
    sendBtn: '[data-testid="btn-chat-send"]',
    attachBtn: '[data-testid="btn-chat-attach"]',
    fileInput: '[data-testid="input-chat-file"]',
    messageContainer: '[data-testid="message-container"]',
    aiAnswerBubble: '[data-testid="assistant-message-bubble"]',
    loadIndicator: '[data-testid="loading-typing-indicator"]',
    messageText: '[data-testid="message-text"]',
    againDropdown: '[data-testid="btn-message-model-toggle"]',
    againDropdownItem: 'button.dropdown-item',
  },
  files: {
    page: '[data-testid="page-files-upload"]',
    filePicker: '[data-testid="section-file-picker"]',
    selectButton: '[data-testid="btn-select-files"]',
    fileInput: '[data-testid="input-files"]',
    uploadButton: '[data-testid="btn-upload"]',
    table: '[data-testid="section-table"]',
    fileRow: '[data-testid="item-file"]',
    emptyState: '[data-testid="state-empty"]',
  },
  fileSelection: {
    modal: '[data-testid="modal-file-selection"]',
    uploadButton: '[data-testid="btn-file-selection-upload"]',
    attachButton: '[data-testid="btn-file-selection-attach"]',
  },
  userMenu: {
    button: '[data-testid="btn-user-menu-toggle"]',
    logoutBtn: '[data-testid="btn-user-logout"]',
  },
  widgets: {
    page: '[data-testid="page-widgets"]',
    createButton: '[data-testid="btn-create-widget"]',
    simpleForm: {
      modal: '[data-testid="modal-simple-widget-form"]',
      nameInput: '[data-testid="input-widget-name"]',
      websiteInput: '[data-testid="input-website-url"]',
      taskPromptInput: '[data-testid="input-task-prompt"]',
      createButton: '[data-testid="btn-create"]',
      cancelButton: '[data-testid="btn-cancel"]',
    },
    successModal: {
      modal: '[data-testid="modal-widget-success"]',
      embedCode: '[data-testid="section-embed-code"]',
      testButton: '[data-testid="btn-test-widget"]',
      closeButton: '[data-testid="btn-close"]',
    },
    widgetCard: {
      item: '[data-testid="item-widget"]',
      embedButton: '[data-testid="btn-widget-embed"]',
      testButton: '[data-testid="btn-widget-test"]',
      advancedButton: '[data-testid="btn-widget-advanced"]',
    },
    advancedConfig: {
      modal: '[data-testid="modal-advanced-config"]',
      tabButton: '[data-testid="btn-tab"]',
      behaviorTab: '[data-testid="section-behavior"]',
      securityTab: '[data-testid="section-security"]',
      assistantTab: '[data-testid="section-assistant"]',
      autoMessageInput: '[data-testid="input-auto-message"]',
      messageLimitInput: '[data-testid="input-message-limit"]',
      maxFileSizeInput: '[data-testid="input-max-file-size"]',
      promptContentInput: '[data-testid="input-prompt-content"]',
      selectionRulesInput: '[data-testid="input-selection-rules"]',
      domainInput: '[data-testid="input-domain"]',
      addDomainButton: '[data-testid="btn-add-domain"]',
      saveButton: '[data-testid="btn-save"]',
      closeButton: '[data-testid="btn-close"]',
    },
  },
  widget: {
    // Shadow DOM Host: The widget creates a shadow root inside this element
    // Use .locator() to access elements inside Shadow DOM
    host: '#synaplan-widget-host',
    // Button is attached directly to body (not in Shadow DOM) for easier styling/positioning
    button: '#synaplan-widget-button',
    // Elements inside Shadow DOM - must be accessed via host.locator()
    chatWindow: '[data-testid="section-chat-window"]',
    messagesContainer: '[data-testid="section-messages"]',
    input: '[data-testid="input-message"]',
    sendButton: '[data-testid="btn-send"]',
    attachButton: '[data-testid="btn-attach"]',
    fileInput: '[data-testid="input-file"]',
    fileUploadError: '[data-testid="text-file-upload-error"]',
    fileSizeError: '.text-red-600, .text-red-400', // File size error message
    removeFileButton: (index: number) => `[data-testid="btn-remove-file-${index}"]`,
  },
  toast: {},
} as const
