export const selectors = {
  login: {
    email: '#email',
    password: '#password',
    submit: 'button[type="submit"]',
  },
  header: {
    modeToggle: '[data-testid="btn-mode-toggle"]',
  },
  nav: {
    newChatButton: '[data-testid="btn-chat-new"]',
    sidebar: '[data-testid="nav-sidebar"]',
  },
  models: {
    page: '[data-testid="page-config-ai-models"]',
    capabilityItem: '[data-testid="item-capability"]',
    capabilityDropdown: '[data-testid="btn-model-dropdown"]',
    capabilityOption: '[data-testid="btn-model-option"]',
  },
  rag: {
    page: '[data-testid="page-rag-search"]',
    queryInput: '[data-testid="input-query"]',
    searchButton: '[data-testid="btn-search"]',
    searchSummary: '[data-testid="text-search-summary"]',
    resultsSection: '[data-testid="section-results"]',
    resultItem: '[data-testid="item-result"]',
  },
  chat: {
    textInput: '[data-testid="input-chat-message"]',
    sendBtn: '[data-testid="btn-chat-send"]',
    attachBtn: '[data-testid="btn-chat-attach"]',
    fileInput: '[data-testid="input-chat-file"]',
    messageContainer: '[data-testid="message-container"]',
    aiAnswerBubble: '[data-testid="assistant-message-bubble"]',
    loadIndicator: '[data-testid="loading-typing-indicator"]',
    messageText: '[data-testid="message-text"]',
    againDropdown: '[data-testid="btn-message-model-toggle"]',
    againDropdownItem: 'button.dropdown-item',
  },
  files: {
    page: '[data-testid="page-files-upload"]',
    filePicker: '[data-testid="section-file-picker"]',
    selectButton: '[data-testid="btn-select-files"]',
    fileInput: '[data-testid="input-files"]',
    uploadButton: '[data-testid="btn-upload"]',
    table: '[data-testid="section-table"]',
    fileRow: '[data-testid="item-file"]',
    emptyState: '[data-testid="state-empty"]',
  },
  userMenu: {
    button: '[data-testid="btn-user-menu-toggle"]',
    logoutBtn: '[data-testid="btn-user-logout"]',
  },
  toast: {},
} as const
