<template>
  <div class="flex flex-col gap-2" data-testid="comp-sidebar-chat-list">
    <!-- Widget Chats Section (only this remains) -->
    <div>
      <button
        class="w-full flex items-center gap-2 px-3 py-2 rounded-lg txt-secondary hover-surface transition-colors text-left focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary min-h-[44px]"
        data-testid="btn-chat-section-widget"
        @click="toggleSection('widget')"
      >
        <ChevronRightIcon
          :class="['w-4 h-4 transition-transform flex-shrink-0', sections.widget && 'rotate-90']"
        />
        <span class="text-xs font-medium uppercase tracking-wider">Widget Chats</span>
        <PuzzlePieceIcon class="w-3.5 h-3.5 ml-auto" />
      </button>

      <div v-if="sections.widget" class="flex flex-col gap-1 mt-1 relative">
        <SidebarChatListItem
          v-for="chat in widgetChats"
          :key="chat.id"
          :chat="chat"
          :is-active="chat.id === activeChat"
          @open="openChat"
          @share="handleShare"
          @rename="handleRename"
          @delete="handleDelete"
        />

        <!-- Show All Button -->
        <button
          v-if="allWidgetChats.length > 5"
          class="px-3 py-2 rounded-lg txt-secondary hover-surface transition-colors text-left text-sm focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary min-h-[44px]"
          data-testid="btn-chat-show-all-widget"
          @click="navigateToStatistics"
        >
          {{ $t('chat.showAll') }}
        </button>

        <button
          v-if="widgetArchivedChats.length > 0"
          class="flex items-center gap-2 px-3 py-2 rounded-lg txt-secondary hover-surface transition-colors text-left focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary min-h-[44px] mt-2"
          data-testid="btn-chat-section-widget-archived"
          @click="toggleSection('widgetArchived')"
        >
          <ChevronRightIcon
            :class="[
              'w-3.5 h-3.5 transition-transform flex-shrink-0',
              sections.widgetArchived && 'rotate-90',
            ]"
          />
          <span class="text-xs font-medium uppercase tracking-wider"
            >Archived ({{ widgetArchivedChats.length }})</span
          >
        </button>

        <div v-if="sections.widgetArchived" class="flex flex-col gap-1 mt-1">
          <SidebarChatListItem
            v-for="chat in widgetArchivedChats"
            :key="chat.id"
            :chat="chat"
            :is-active="chat.id === activeChat"
            @open="openChat"
            @share="handleShare"
            @rename="handleRename"
            @delete="handleDelete"
          />
        </div>
      </div>
    </div>

    <!-- Chat Share Modal -->
    <ChatShareModal
      :is-open="shareModalOpen"
      :chat-id="shareModalChatId"
      :chat-title="shareModalChatTitle"
      @close="shareModalOpen = false"
      @shared="chatsStore.loadChats()"
      @unshared="chatsStore.loadChats()"
    />
  </div>
</template>

<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'
import { useRouter } from 'vue-router'
import { useI18n } from 'vue-i18n'
import { ChevronRightIcon, PuzzlePieceIcon } from '@heroicons/vue/24/outline'
import SidebarChatListItem from './SidebarChatListItem.vue'
import ChatShareModal from './ChatShareModal.vue'
import { useChatsStore } from '@/stores/chats'
import { useDialog } from '@/composables/useDialog'
import { useNotification } from '@/composables/useNotification'
import type { Chat } from '@/mocks/chats'

const { t } = useI18n()
const chatsStore = useChatsStore()
const router = useRouter()
const dialog = useDialog()
const { success } = useNotification()

const sections = ref({
  widget: false,
  widgetArchived: false,
})

// Helper to format dates
const formatDate = (value: string | number): string => {
  const date = typeof value === 'number' ? new Date(value * 1000) : new Date(value)
  const now = new Date()
  const diffInSeconds = Math.floor((now.getTime() - date.getTime()) / 1000)

  if (diffInSeconds < 60) return 'Just now'
  if (diffInSeconds < 3600) return `${Math.floor(diffInSeconds / 60)}m ago`
  if (diffInSeconds < 86400) return `${Math.floor(diffInSeconds / 3600)}h ago`
  if (diffInSeconds < 604800) return `${Math.floor(diffInSeconds / 86400)}d ago`
  return date.toLocaleDateString()
}

// Map API chats to sidebar format - removed allMyChats and myChats
// Generate default widget title from session info
const getDefaultWidgetTitle = (widgetName: string | null, sessionId: string): string => {
  const shortId = sessionId.slice(-6)
  return widgetName ? `${widgetName} • ${shortId}` : shortId
}

// Check if title is an auto-generated widget title (old or new format)
const isAutoGeneratedTitle = (
  title: string,
  widgetName: string | null,
  sessionId: string
): boolean => {
  const shortId = sessionId.slice(-6)
  // Current format: "Widget Name • abc123"
  if (title === getDefaultWidgetTitle(widgetName, sessionId)) return true
  // Old format: "abc123 • Widget Name"
  if (widgetName && title === `${shortId} • ${widgetName}`) return true
  if (title === `Widget • ${shortId}`) return true
  // Even older format with "Widget:" prefix
  if (title.startsWith('Widget:')) return true
  return false
}

// Clean up title for rename dialog (remove "Widget:" prefix if present)
const cleanTitleForEdit = (title: string): string => {
  if (title.startsWith('Widget: ')) {
    return title.slice(8) // Remove "Widget: " prefix
  }
  if (title.startsWith('Widget:')) {
    return title.slice(7) // Remove "Widget:" prefix (no space)
  }
  return title
}

const allWidgetChats = computed((): Chat[] => {
  const sessionChatsRaw = chatsStore.chats
    .filter((c) => c.widgetSession)
    .map((c) => {
      const session = c.widgetSession!
      const defaultTitle = getDefaultWidgetTitle(session.widgetName, session.sessionId)
      // Use custom title only if it's not an auto-generated one
      const title =
        c.title && !isAutoGeneratedTitle(c.title, session.widgetName, session.sessionId)
          ? c.title
          : defaultTitle
      const lastTimestamp =
        session.lastMessage ?? Math.floor(new Date(c.updatedAt).getTime() / 1000)
      const timestampLabel = `${session.messageCount} msg · ${formatDate(lastTimestamp)}`

      return {
        metaTimestamp: lastTimestamp,
        item: {
          id: String(c.id),
          title,
          timestamp: timestampLabel,
          type: 'widget' as const,
          archived: false,
        },
      }
    })
    .sort((a, b) => b.metaTimestamp - a.metaTimestamp)

  return sessionChatsRaw.map((entry) => entry.item)
})

const widgetChats = computed((): Chat[] => {
  return allWidgetChats.value.slice(0, 5)
})

const widgetArchivedChats = computed((): Chat[] => {
  return []
})

const activeChat = computed(() => {
  return chatsStore.activeChatId ? String(chatsStore.activeChatId) : ''
})

const toggleSection = (section: 'widget' | 'widgetArchived') => {
  sections.value[section] = !sections.value[section]
}

const openChat = async (id: string) => {
  const chatId = Number(id)
  chatsStore.setActiveChat(chatId)
  // History will be loaded automatically via watcher in ChatView
  // Navigate to chat view if not already there
  if (router.currentRoute.value.path !== '/') {
    router.push('/')
  }
}

const shareModalOpen = ref(false)
const shareModalChatId = ref<number | null>(null)
const shareModalChatTitle = ref<string>('')

const handleShare = (id: string) => {
  const chat = chatsStore.chats.find((c) => c.id === Number(id))
  shareModalChatId.value = Number(id)
  shareModalChatTitle.value = chat?.title || 'Chat'
  shareModalOpen.value = true
}

const handleRename = async (id: string) => {
  const chat = chatsStore.chats.find((c) => c.id === Number(id))
  const currentTitle = chat?.title || ''
  const cleanedTitle = cleanTitleForEdit(currentTitle)
  const isWidgetChat = chat?.widgetSession !== undefined
  const message = isWidgetChat
    ? `${t('chat.enterNewName')}\n\n${t('chat.renameNote')}`
    : t('chat.enterNewName')
  const newTitle = await dialog.prompt({
    title: t('chat.rename'),
    message,
    placeholder: t('chat.namePlaceholder'),
    defaultValue: cleanedTitle,
    confirmText: t('common.rename'),
    cancelText: t('common.cancel'),
  })

  if (newTitle && newTitle.trim()) {
    await chatsStore.updateChatTitle(Number(id), newTitle.trim())
    success(t('chat.renameSuccess'))
  }
}

const handleDelete = async (id: string) => {
  const confirmed = await dialog.confirm({
    title: 'Delete Chat',
    message: 'Are you sure you want to delete this chat? This action cannot be undone.',
    confirmText: 'Delete',
    cancelText: 'Cancel',
    danger: true,
  })

  if (confirmed) {
    await chatsStore.deleteChat(Number(id))
  }
}

const navigateToStatistics = () => {
  router.push('/statistics#chats')
}

// Load chats on mount
onMounted(async () => {
  await chatsStore.loadChats()
})
</script>
