<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: grpc_service.proto

namespace Inference\LogSettingsResponse;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 * Generated from protobuf message <code>inference.LogSettingsResponse.SettingValue</code>
 */
class SettingValue extends \Google\Protobuf\Internal\Message
{
    protected $parameter_choice;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $bool_param
     *          \@\@    .. cpp:var:: bool bool_param
     *          \@\@
     *          \@\@       A boolean parameter value.
     *          \@\@
     *     @type int $uint32_param
     *          \@\@    .. cpp:var:: uint32 uint32_param
     *          \@\@
     *          \@\@       An int32 parameter value.
     *          \@\@
     *     @type string $string_param
     *          \@\@    .. cpp:var:: string string_param
     *          \@\@
     *          \@\@       A string parameter value.
     *          \@\@
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\GrpcService::initOnce();
        parent::__construct($data);
    }

    /**
     *\@\@    .. cpp:var:: bool bool_param
     *\@\@
     *\@\@       A boolean parameter value.
     *\@\@
     *
     * Generated from protobuf field <code>bool bool_param = 1;</code>
     * @return bool
     */
    public function getBoolParam()
    {
        return $this->readOneof(1);
    }

    public function hasBoolParam()
    {
        return $this->hasOneof(1);
    }

    /**
     *\@\@    .. cpp:var:: bool bool_param
     *\@\@
     *\@\@       A boolean parameter value.
     *\@\@
     *
     * Generated from protobuf field <code>bool bool_param = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setBoolParam($var)
    {
        GPBUtil::checkBool($var);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     *\@\@    .. cpp:var:: uint32 uint32_param
     *\@\@
     *\@\@       An int32 parameter value.
     *\@\@
     *
     * Generated from protobuf field <code>uint32 uint32_param = 2;</code>
     * @return int
     */
    public function getUint32Param()
    {
        return $this->readOneof(2);
    }

    public function hasUint32Param()
    {
        return $this->hasOneof(2);
    }

    /**
     *\@\@    .. cpp:var:: uint32 uint32_param
     *\@\@
     *\@\@       An int32 parameter value.
     *\@\@
     *
     * Generated from protobuf field <code>uint32 uint32_param = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setUint32Param($var)
    {
        GPBUtil::checkUint32($var);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     *\@\@    .. cpp:var:: string string_param
     *\@\@
     *\@\@       A string parameter value.
     *\@\@
     *
     * Generated from protobuf field <code>string string_param = 3;</code>
     * @return string
     */
    public function getStringParam()
    {
        return $this->readOneof(3);
    }

    public function hasStringParam()
    {
        return $this->hasOneof(3);
    }

    /**
     *\@\@    .. cpp:var:: string string_param
     *\@\@
     *\@\@       A string parameter value.
     *\@\@
     *
     * Generated from protobuf field <code>string string_param = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setStringParam($var)
    {
        GPBUtil::checkString($var, True);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getParameterChoice()
    {
        return $this->whichOneof("parameter_choice");
    }

}

