<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: grpc_service.proto

namespace Inference\TraceSettingResponse;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 *\@\@
 *\@\@  .. cpp:var:: message SettingValue
 *\@\@
 *\@\@     The values to be associated with a trace setting.
 *\@\@
 *
 * Generated from protobuf message <code>inference.TraceSettingResponse.SettingValue</code>
 */
class SettingValue extends \Google\Protobuf\Internal\Message
{
    /**
     *\@\@
     *\@\@    .. cpp:var:: string value (repeated)
     *\@\@
     *\@\@       The value.
     *\@\@
     *
     * Generated from protobuf field <code>repeated string value = 1;</code>
     */
    private $value;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string[] $value
     *          \@\@
     *          \@\@    .. cpp:var:: string value (repeated)
     *          \@\@
     *          \@\@       The value.
     *          \@\@
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\GrpcService::initOnce();
        parent::__construct($data);
    }

    /**
     *\@\@
     *\@\@    .. cpp:var:: string value (repeated)
     *\@\@
     *\@\@       The value.
     *\@\@
     *
     * Generated from protobuf field <code>repeated string value = 1;</code>
     * @return RepeatedField<string>
     */
    public function getValue()
    {
        return $this->value;
    }

    /**
     *\@\@
     *\@\@    .. cpp:var:: string value (repeated)
     *\@\@
     *\@\@       The value.
     *\@\@
     *
     * Generated from protobuf field <code>repeated string value = 1;</code>
     * @param string[] $var
     * @return $this
     */
    public function setValue($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->value = $arr;

        return $this;
    }

}

