<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: model_config.proto

namespace Inference\ModelRateLimiter;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 *\@\@  .. cpp:var:: message Resource
 *\@\@
 *\@\@     The resource property.
 *\@\@
 *
 * Generated from protobuf message <code>inference.ModelRateLimiter.Resource</code>
 */
class Resource extends \Google\Protobuf\Internal\Message
{
    /**
     *\@\@  .. cpp:var:: string name
     *\@\@
     *\@\@     The name associated with the resource.
     *\@\@
     *
     * Generated from protobuf field <code>string name = 1;</code>
     */
    protected $name = '';
    /**
     *\@\@  .. cpp:var:: bool global
     *\@\@
     *\@\@     Whether or not the resource is global. If true then the resource
     *\@\@     is assumed to be shared among the devices otherwise specified
     *\@\@     count of the resource is assumed for each device associated
     *\@\@     with the instance.
     *\@\@
     *
     * Generated from protobuf field <code>bool global = 2;</code>
     */
    protected $global = false;
    /**
     *\@\@  .. cpp:var:: uint32 count
     *\@\@
     *\@\@     The number of resources required for the execution of the model
     *\@\@     instance.
     *\@\@
     *
     * Generated from protobuf field <code>uint32 count = 3;</code>
     */
    protected $count = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *          \@\@  .. cpp:var:: string name
     *          \@\@
     *          \@\@     The name associated with the resource.
     *          \@\@
     *     @type bool $global
     *          \@\@  .. cpp:var:: bool global
     *          \@\@
     *          \@\@     Whether or not the resource is global. If true then the resource
     *          \@\@     is assumed to be shared among the devices otherwise specified
     *          \@\@     count of the resource is assumed for each device associated
     *          \@\@     with the instance.
     *          \@\@
     *     @type int $count
     *          \@\@  .. cpp:var:: uint32 count
     *          \@\@
     *          \@\@     The number of resources required for the execution of the model
     *          \@\@     instance.
     *          \@\@
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\ModelConfig::initOnce();
        parent::__construct($data);
    }

    /**
     *\@\@  .. cpp:var:: string name
     *\@\@
     *\@\@     The name associated with the resource.
     *\@\@
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     *\@\@  .. cpp:var:: string name
     *\@\@
     *\@\@     The name associated with the resource.
     *\@\@
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     *\@\@  .. cpp:var:: bool global
     *\@\@
     *\@\@     Whether or not the resource is global. If true then the resource
     *\@\@     is assumed to be shared among the devices otherwise specified
     *\@\@     count of the resource is assumed for each device associated
     *\@\@     with the instance.
     *\@\@
     *
     * Generated from protobuf field <code>bool global = 2;</code>
     * @return bool
     */
    public function getGlobal()
    {
        return $this->global;
    }

    /**
     *\@\@  .. cpp:var:: bool global
     *\@\@
     *\@\@     Whether or not the resource is global. If true then the resource
     *\@\@     is assumed to be shared among the devices otherwise specified
     *\@\@     count of the resource is assumed for each device associated
     *\@\@     with the instance.
     *\@\@
     *
     * Generated from protobuf field <code>bool global = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setGlobal($var)
    {
        GPBUtil::checkBool($var);
        $this->global = $var;

        return $this;
    }

    /**
     *\@\@  .. cpp:var:: uint32 count
     *\@\@
     *\@\@     The number of resources required for the execution of the model
     *\@\@     instance.
     *\@\@
     *
     * Generated from protobuf field <code>uint32 count = 3;</code>
     * @return int
     */
    public function getCount()
    {
        return $this->count;
    }

    /**
     *\@\@  .. cpp:var:: uint32 count
     *\@\@
     *\@\@     The number of resources required for the execution of the model
     *\@\@     instance.
     *\@\@
     *
     * Generated from protobuf field <code>uint32 count = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setCount($var)
    {
        GPBUtil::checkUint32($var);
        $this->count = $var;

        return $this;
    }

}

