<?php

declare(strict_types=1);

namespace App\Controller;

use App\Entity\User;
use App\Service\PlatformLink\Exception\PlatformLinkValidationException;
use App\Service\PlatformLink\OutlookConnectService;
use OpenApi\Attributes as OA;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\Security\Http\Attribute\CurrentUser;

/**
 * Outlook add-in (Synamail) connect. Lives outside /api/v1/platform-links so
 * it is never hidden by PLATFORM_LINKS.ENABLED (C1 keeps that prefix 404 when
 * the flag is off; Outlook connect is shipped behaviour).
 */
#[Route('/api/v1/addin', name: 'addin_')]
#[OA\Tag(name: 'Platform Links')]
final class AddinConnectController extends AbstractController
{
    public function __construct(
        private readonly OutlookConnectService $outlookConnectService,
    ) {
    }

    #[Route('/connect', name: 'connect', methods: ['POST'])]
    #[OA\Post(
        path: '/api/v1/addin/connect',
        operationId: 'connectOutlookAddin',
        summary: 'Mint the Outlook add-in key and build the relay redirect',
        description: 'Session-authenticated. Mints a scoped add-in API key for the signed-in user. When redirect_uri prefix-matches the Outlook built-in allow-list, `redirect` is the relay URL carrying the payload in its fragment; otherwise `redirect` is null and the bridge delivers `payload` through Office.js messageParent. The browser never decides where the key travels.',
        tags: ['Platform Links'],
        requestBody: new OA\RequestBody(
            required: true,
            content: new OA\JsonContent(
                required: ['state'],
                properties: [
                    new OA\Property(property: 'state', type: 'string', description: 'CSRF nonce generated by the add-in; round-trips unchanged.', example: 'a1b2c3'),
                    new OA\Property(property: 'redirect_uri', type: 'string', nullable: true, description: 'Same-origin relay page of the add-in.', example: 'https://addin.synaplan.com/src/dialog/auth-relay.html'),
                    new OA\Property(property: 'base_url', type: 'string', nullable: true, description: 'Synaplan base URL the add-in should call. Defaults to the request origin.', example: 'https://web.synaplan.com'),
                ]
            )
        ),
        responses: [
            new OA\Response(
                response: 200,
                description: 'Key minted',
                content: new OA\JsonContent(
                    required: ['success', 'redirect', 'payload'],
                    properties: [
                        new OA\Property(property: 'success', type: 'boolean', example: true),
                        new OA\Property(property: 'redirect', type: 'string', nullable: true, description: 'Relay URL with `#payload=<base64 JSON>`, or null when redirect_uri was missing or not allow-listed.', example: 'https://addin.synaplan.com/src/dialog/auth-relay.html#payload=eyJ...'),
                        new OA\Property(
                            property: 'payload',
                            type: 'object',
                            required: ['state', 'apiKey', 'keyId', 'email', 'baseUrl'],
                            properties: [
                                new OA\Property(property: 'state', type: 'string', example: 'a1b2c3'),
                                new OA\Property(property: 'apiKey', type: 'string', description: 'Shown once.', example: 'sk_...'),
                                new OA\Property(property: 'keyId', type: 'integer', example: 42),
                                new OA\Property(property: 'email', type: 'string', example: 'jane@example.org'),
                                new OA\Property(property: 'baseUrl', type: 'string', example: 'https://web.synaplan.com'),
                            ]
                        ),
                    ]
                )
            ),
            new OA\Response(response: 400, description: 'Missing or oversized state'),
            new OA\Response(response: 401, description: 'Not authenticated'),
        ]
    )]
    public function connect(Request $request, #[CurrentUser] ?User $user): JsonResponse
    {
        if (!$user instanceof User) {
            return $this->json(['success' => false, 'error' => 'Not authenticated'], Response::HTTP_UNAUTHORIZED);
        }

        $data = json_decode($request->getContent(), true);
        $data = \is_array($data) ? $data : [];

        try {
            $result = $this->outlookConnectService->connect(
                $user,
                \is_string($data['state'] ?? null) ? $data['state'] : '',
                \is_string($data['redirect_uri'] ?? null) ? $data['redirect_uri'] : '',
                \is_string($data['base_url'] ?? null) ? $data['base_url'] : '',
                $request->getSchemeAndHttpHost(),
                (string) $request->headers->get('User-Agent', ''),
                $request->getClientIp() ?? '',
            );
        } catch (PlatformLinkValidationException $e) {
            return $this->json(['success' => false, 'error' => $e->getMessage()], Response::HTTP_BAD_REQUEST);
        }

        return $this->json(['success' => true, ...$result]);
    }
}
