<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: grpc_service.proto

namespace Inference\ModelInferRequest;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 *\@\@
 *\@\@  .. cpp:var:: message InferRequestedOutputTensor
 *\@\@
 *\@\@     An output tensor requested for an inference request.
 *\@\@
 *
 * Generated from protobuf message <code>inference.ModelInferRequest.InferRequestedOutputTensor</code>
 */
class InferRequestedOutputTensor extends \Google\Protobuf\Internal\Message
{
    /**
     *\@\@
     *\@\@    .. cpp:var:: string name
     *\@\@
     *\@\@       The tensor name.
     *\@\@
     *
     * Generated from protobuf field <code>string name = 1;</code>
     */
    protected $name = '';
    /**
     *\@\@    .. cpp:var:: map<string,InferParameter> parameters
     *\@\@
     *\@\@       Optional requested output tensor parameters.
     *\@\@
     *
     * Generated from protobuf field <code>map<string, .inference.InferParameter> parameters = 2;</code>
     */
    private $parameters;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *          \@\@
     *          \@\@    .. cpp:var:: string name
     *          \@\@
     *          \@\@       The tensor name.
     *          \@\@
     *     @type array|\Google\Protobuf\Internal\MapField $parameters
     *          \@\@    .. cpp:var:: map<string,InferParameter> parameters
     *          \@\@
     *          \@\@       Optional requested output tensor parameters.
     *          \@\@
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\GrpcService::initOnce();
        parent::__construct($data);
    }

    /**
     *\@\@
     *\@\@    .. cpp:var:: string name
     *\@\@
     *\@\@       The tensor name.
     *\@\@
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     *\@\@
     *\@\@    .. cpp:var:: string name
     *\@\@
     *\@\@       The tensor name.
     *\@\@
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     *\@\@    .. cpp:var:: map<string,InferParameter> parameters
     *\@\@
     *\@\@       Optional requested output tensor parameters.
     *\@\@
     *
     * Generated from protobuf field <code>map<string, .inference.InferParameter> parameters = 2;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getParameters()
    {
        return $this->parameters;
    }

    /**
     *\@\@    .. cpp:var:: map<string,InferParameter> parameters
     *\@\@
     *\@\@       Optional requested output tensor parameters.
     *\@\@
     *
     * Generated from protobuf field <code>map<string, .inference.InferParameter> parameters = 2;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setParameters($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::MESSAGE, \Inference\InferParameter::class);
        $this->parameters = $arr;

        return $this;
    }

}

