<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: grpc_service.proto

namespace Inference\ModelInferRequest;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 *\@\@
 *\@\@  .. cpp:var:: message InferInputTensor
 *\@\@
 *\@\@     An input tensor for an inference request.
 *\@\@
 *
 * Generated from protobuf message <code>inference.ModelInferRequest.InferInputTensor</code>
 */
class InferInputTensor extends \Google\Protobuf\Internal\Message
{
    /**
     *\@\@
     *\@\@    .. cpp:var:: string name
     *\@\@
     *\@\@       The tensor name.
     *\@\@
     *
     * Generated from protobuf field <code>string name = 1;</code>
     */
    protected $name = '';
    /**
     *\@\@
     *\@\@    .. cpp:var:: string datatype
     *\@\@
     *\@\@       The tensor data type.
     *\@\@
     *
     * Generated from protobuf field <code>string datatype = 2;</code>
     */
    protected $datatype = '';
    /**
     *\@\@
     *\@\@    .. cpp:var:: int64 shape (repeated)
     *\@\@
     *\@\@       The tensor shape.
     *\@\@
     *
     * Generated from protobuf field <code>repeated int64 shape = 3;</code>
     */
    private $shape;
    /**
     *\@\@    .. cpp:var:: map<string,InferParameter> parameters
     *\@\@
     *\@\@       Optional inference input tensor parameters.
     *\@\@
     *
     * Generated from protobuf field <code>map<string, .inference.InferParameter> parameters = 4;</code>
     */
    private $parameters;
    /**
     *\@\@    .. cpp:var:: InferTensorContents contents
     *\@\@
     *\@\@       The tensor contents using a data-type format. This field
     *\@\@       must not be specified if tensor contents are being specified
     *\@\@       in ModelInferRequest.raw_input_contents.
     *\@\@
     *
     * Generated from protobuf field <code>.inference.InferTensorContents contents = 5;</code>
     */
    protected $contents = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *          \@\@
     *          \@\@    .. cpp:var:: string name
     *          \@\@
     *          \@\@       The tensor name.
     *          \@\@
     *     @type string $datatype
     *          \@\@
     *          \@\@    .. cpp:var:: string datatype
     *          \@\@
     *          \@\@       The tensor data type.
     *          \@\@
     *     @type int[]|string[] $shape
     *          \@\@
     *          \@\@    .. cpp:var:: int64 shape (repeated)
     *          \@\@
     *          \@\@       The tensor shape.
     *          \@\@
     *     @type array|\Google\Protobuf\Internal\MapField $parameters
     *          \@\@    .. cpp:var:: map<string,InferParameter> parameters
     *          \@\@
     *          \@\@       Optional inference input tensor parameters.
     *          \@\@
     *     @type \Inference\InferTensorContents $contents
     *          \@\@    .. cpp:var:: InferTensorContents contents
     *          \@\@
     *          \@\@       The tensor contents using a data-type format. This field
     *          \@\@       must not be specified if tensor contents are being specified
     *          \@\@       in ModelInferRequest.raw_input_contents.
     *          \@\@
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\GrpcService::initOnce();
        parent::__construct($data);
    }

    /**
     *\@\@
     *\@\@    .. cpp:var:: string name
     *\@\@
     *\@\@       The tensor name.
     *\@\@
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     *\@\@
     *\@\@    .. cpp:var:: string name
     *\@\@
     *\@\@       The tensor name.
     *\@\@
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     *\@\@
     *\@\@    .. cpp:var:: string datatype
     *\@\@
     *\@\@       The tensor data type.
     *\@\@
     *
     * Generated from protobuf field <code>string datatype = 2;</code>
     * @return string
     */
    public function getDatatype()
    {
        return $this->datatype;
    }

    /**
     *\@\@
     *\@\@    .. cpp:var:: string datatype
     *\@\@
     *\@\@       The tensor data type.
     *\@\@
     *
     * Generated from protobuf field <code>string datatype = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setDatatype($var)
    {
        GPBUtil::checkString($var, True);
        $this->datatype = $var;

        return $this;
    }

    /**
     *\@\@
     *\@\@    .. cpp:var:: int64 shape (repeated)
     *\@\@
     *\@\@       The tensor shape.
     *\@\@
     *
     * Generated from protobuf field <code>repeated int64 shape = 3;</code>
     * @return RepeatedField<int>|RepeatedField<string>
     */
    public function getShape()
    {
        return $this->shape;
    }

    /**
     *\@\@
     *\@\@    .. cpp:var:: int64 shape (repeated)
     *\@\@
     *\@\@       The tensor shape.
     *\@\@
     *
     * Generated from protobuf field <code>repeated int64 shape = 3;</code>
     * @param int[]|string[] $var
     * @return $this
     */
    public function setShape($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT64);
        $this->shape = $arr;

        return $this;
    }

    /**
     *\@\@    .. cpp:var:: map<string,InferParameter> parameters
     *\@\@
     *\@\@       Optional inference input tensor parameters.
     *\@\@
     *
     * Generated from protobuf field <code>map<string, .inference.InferParameter> parameters = 4;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getParameters()
    {
        return $this->parameters;
    }

    /**
     *\@\@    .. cpp:var:: map<string,InferParameter> parameters
     *\@\@
     *\@\@       Optional inference input tensor parameters.
     *\@\@
     *
     * Generated from protobuf field <code>map<string, .inference.InferParameter> parameters = 4;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setParameters($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::MESSAGE, \Inference\InferParameter::class);
        $this->parameters = $arr;

        return $this;
    }

    /**
     *\@\@    .. cpp:var:: InferTensorContents contents
     *\@\@
     *\@\@       The tensor contents using a data-type format. This field
     *\@\@       must not be specified if tensor contents are being specified
     *\@\@       in ModelInferRequest.raw_input_contents.
     *\@\@
     *
     * Generated from protobuf field <code>.inference.InferTensorContents contents = 5;</code>
     * @return \Inference\InferTensorContents|null
     */
    public function getContents()
    {
        return $this->contents;
    }

    public function hasContents()
    {
        return isset($this->contents);
    }

    public function clearContents()
    {
        unset($this->contents);
    }

    /**
     *\@\@    .. cpp:var:: InferTensorContents contents
     *\@\@
     *\@\@       The tensor contents using a data-type format. This field
     *\@\@       must not be specified if tensor contents are being specified
     *\@\@       in ModelInferRequest.raw_input_contents.
     *\@\@
     *
     * Generated from protobuf field <code>.inference.InferTensorContents contents = 5;</code>
     * @param \Inference\InferTensorContents $var
     * @return $this
     */
    public function setContents($var)
    {
        GPBUtil::checkMessage($var, \Inference\InferTensorContents::class);
        $this->contents = $var;

        return $this;
    }

}

