<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: model_config.proto

namespace Inference\ModelOptimizationPolicy\Cuda\GraphSpec;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *&#64;&#64;      .. cpp:var:: message Dims
 *&#64;&#64;
 *&#64;&#64;         Specification of tensor dimension.
 *&#64;&#64;
 *
 * Generated from protobuf message <code>inference.ModelOptimizationPolicy.Cuda.GraphSpec.Shape</code>
 */
class Shape extends \Google\Protobuf\Internal\Message
{
    /**
     *&#64;&#64;        .. cpp:var:: int64 dim (repeated)
     *&#64;&#64;
     *&#64;&#64;           The dimension.
     *&#64;&#64;
     *
     * Generated from protobuf field <code>repeated int64 dim = 1;</code>
     */
    private $dim;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int[]|string[]|\Google\Protobuf\Internal\RepeatedField $dim
     *          &#64;&#64;        .. cpp:var:: int64 dim (repeated)
     *          &#64;&#64;
     *          &#64;&#64;           The dimension.
     *          &#64;&#64;
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\ModelConfig::initOnce();
        parent::__construct($data);
    }

    /**
     *&#64;&#64;        .. cpp:var:: int64 dim (repeated)
     *&#64;&#64;
     *&#64;&#64;           The dimension.
     *&#64;&#64;
     *
     * Generated from protobuf field <code>repeated int64 dim = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDim()
    {
        return $this->dim;
    }

    /**
     *&#64;&#64;        .. cpp:var:: int64 dim (repeated)
     *&#64;&#64;
     *&#64;&#64;           The dimension.
     *&#64;&#64;
     *
     * Generated from protobuf field <code>repeated int64 dim = 1;</code>
     * @param int[]|string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDim($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT64);
        $this->dim = $arr;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Shape::class, \Inference\ModelOptimizationPolicy_Cuda_GraphSpec_Shape::class);

