<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: model_config.proto

namespace Inference\ModelOptimizationPolicy;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *&#64;&#64;
 *&#64;&#64;  .. cpp:var:: message Graph
 *&#64;&#64;
 *&#64;&#64;     Enable generic graph optimization of the model. If not specified
 *&#64;&#64;     the framework's default level of optimization is used. Supports
 *&#64;&#64;     TensorFlow graphdef and savedmodel and Onnx models. For TensorFlow
 *&#64;&#64;     causes XLA to be enabled/disabled for the model. For Onnx defaults
 *&#64;&#64;     to enabling all optimizations, -1 enables only basic optimizations,
 *&#64;&#64;     +1 enables only basic and extended optimizations.
 *&#64;&#64;
 *
 * Generated from protobuf message <code>inference.ModelOptimizationPolicy.Graph</code>
 */
class Graph extends \Google\Protobuf\Internal\Message
{
    /**
     *&#64;&#64;    .. cpp:var:: int32 level
     *&#64;&#64;
     *&#64;&#64;       The optimization level. Defaults to 0 (zero) if not specified.
     *&#64;&#64;
     *&#64;&#64;         - -1: Disabled
     *&#64;&#64;         -  0: Framework default
     *&#64;&#64;         -  1+: Enable optimization level (greater values indicate
     *&#64;&#64;            higher optimization levels)
     *&#64;&#64;
     *
     * Generated from protobuf field <code>int32 level = 1;</code>
     */
    protected $level = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $level
     *          &#64;&#64;    .. cpp:var:: int32 level
     *          &#64;&#64;
     *          &#64;&#64;       The optimization level. Defaults to 0 (zero) if not specified.
     *          &#64;&#64;
     *          &#64;&#64;         - -1: Disabled
     *          &#64;&#64;         -  0: Framework default
     *          &#64;&#64;         -  1+: Enable optimization level (greater values indicate
     *          &#64;&#64;            higher optimization levels)
     *          &#64;&#64;
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\ModelConfig::initOnce();
        parent::__construct($data);
    }

    /**
     *&#64;&#64;    .. cpp:var:: int32 level
     *&#64;&#64;
     *&#64;&#64;       The optimization level. Defaults to 0 (zero) if not specified.
     *&#64;&#64;
     *&#64;&#64;         - -1: Disabled
     *&#64;&#64;         -  0: Framework default
     *&#64;&#64;         -  1+: Enable optimization level (greater values indicate
     *&#64;&#64;            higher optimization levels)
     *&#64;&#64;
     *
     * Generated from protobuf field <code>int32 level = 1;</code>
     * @return int
     */
    public function getLevel()
    {
        return $this->level;
    }

    /**
     *&#64;&#64;    .. cpp:var:: int32 level
     *&#64;&#64;
     *&#64;&#64;       The optimization level. Defaults to 0 (zero) if not specified.
     *&#64;&#64;
     *&#64;&#64;         - -1: Disabled
     *&#64;&#64;         -  0: Framework default
     *&#64;&#64;         -  1+: Enable optimization level (greater values indicate
     *&#64;&#64;            higher optimization levels)
     *&#64;&#64;
     *
     * Generated from protobuf field <code>int32 level = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setLevel($var)
    {
        GPBUtil::checkInt32($var);
        $this->level = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Graph::class, \Inference\ModelOptimizationPolicy_Graph::class);

