<?php

declare(strict_types=1);

namespace App\Service\Multitask\Execution\Runner;

use App\Entity\File;
use App\Repository\FileRepository;
use App\Service\File\ConversationFile;
use App\Service\File\ConversationFileCatalog;
use App\Service\File\GeneratedDocumentStore;
use App\Service\File\Office\DocumentExportService;
use App\Service\File\Office\DocumentThumbnailGenerator;
use App\Service\Multitask\Execution\NodeContext;
use App\Service\Multitask\Execution\NodeResult;
use App\Service\Multitask\Execution\TaskRunner;
use App\Service\Multitask\Plan\Capability;
use App\Service\Multitask\Plan\TaskNode;
use App\Service\Multitask\Skill\SkillDescriptor;
use Psr\Log\LoggerInterface;

/**
 * `document_export` runner — converts an office file that ALREADY exists in the
 * conversation to PDF (#1691).
 *
 * "hieraus eine PDF" on an attached workbook used to plan `extract_text` →
 * `document_generation`: the model re-authored a new workbook from the text
 * extract and Collabora converted THAT, so the PDF lost the original's column
 * widths, number formats and styling. This node runs the exact conversion the
 * file chip's "Download as PDF" runs — {@see DocumentExportService} on the
 * original bytes — and picks no model.
 *
 * Node contract:
 *   - params.file / inputs.file  optional; a `file:ID` reference from the files
 *                                list, or an upstream node's file descriptor
 *                                (`$nX.file`). Defaults to the office file the
 *                                user most recently attached or shared.
 *   - output                     one PDF file descriptor + `document_export`
 *                                metadata (source and PDF file ids)
 */
final readonly class DocumentExportRunner implements TaskRunner
{
    private const SERVE_PREFIX = '/api/v1/files/uploads/';

    public function __construct(
        private DocumentExportService $exportService,
        private GeneratedDocumentStore $documentStore,
        private ConversationFileCatalog $conversationFiles,
        private FileRepository $files,
        private LoggerInterface $logger,
    ) {
    }

    public function supportedCapabilities(): array
    {
        return [Capability::DocumentExport];
    }

    /**
     * @return list<SkillDescriptor>
     */
    public function describe(): array
    {
        return [
            new SkillDescriptor(
                Capability::DocumentExport,
                'Convert an office file that ALREADY EXISTS in this conversation (attached to this message, shared earlier, or generated by an earlier turn: DOCX, XLSX, PPTX, ODT, ODS, ODP) into a PDF. The server renders the ORIGINAL file with its layout intact — nothing is re-written. Use it whenever the user wants an existing file exported/converted/saved as PDF ("export this as PDF", "hieraus eine PDF", "diese XLSX als PDF"); NEVER plan extract_text + document_generation for that. Optional params.file: a `file:ID` reference from the files list (defaults to the office file the user most recently attached or shared). Creating a NEW document delivered as PDF stays document_generation.',
                available: fn (): bool => $this->engineConfigured(),
            ),
        ];
    }

    public function run(TaskNode $node, NodeContext $context): NodeResult
    {
        if (!$this->engineConfigured()) {
            return NodeResult::failed('document_export: the office engine is not configured');
        }

        $catalog = $this->conversationFiles->build($context->message, $context->thread);
        $entry = $this->requestedEntry($node, $context, $catalog) ?? $this->defaultEntry($catalog);
        if (null === $entry) {
            return NodeResult::failed('document_export: no office file in this conversation to convert');
        }

        $source = $this->loadFile($entry, $context);
        if (null === $source) {
            return NodeResult::failed('document_export: file "'.$entry->displayName.'" is not available');
        }

        $pdfPath = $this->exportService->exportToPdf($source);
        if (null === $pdfPath) {
            return NodeResult::failed('document_export: the office engine could not convert "'.$source->getFileName().'" to PDF');
        }

        $pdf = $this->documentStore->storePdfFor(
            $source,
            $pdfPath,
            $source->getFileText(),
            !empty($context->options['incognito']),
        );
        if (null === $pdf) {
            return NodeResult::failed('document_export: could not store the PDF of "'.$source->getFileName().'"');
        }

        $this->logger->info('DocumentExportRunner: exported conversation file to PDF', [
            'node_id' => $node->id,
            'source_file_id' => $source->getId(),
            'pdf_file_id' => $pdf->getId(),
        ]);

        $relative = ltrim($pdf->getFilePath(), '/');

        return NodeResult::ok(
            'PDF created from "'.$source->getFileName().'": '.$pdf->getFileName(),
            [[
                'path' => self::SERVE_PREFIX.$relative,
                'type' => 'document',
                'local_path' => $relative,
            ]],
            [
                'media_type' => 'document',
                'document_export' => [
                    'source_file_id' => $source->getId(),
                    'source_filename' => $source->getFileName(),
                    'pdf_file_id' => $pdf->getId(),
                ],
            ],
        );
    }

    /**
     * The file the planner named, when it named one the catalog offers.
     *
     * @param list<ConversationFile> $catalog
     */
    private function requestedEntry(TaskNode $node, NodeContext $context, array $catalog): ?ConversationFile
    {
        $inputs = $context->resolveInputs($node);
        $requested = $node->params['file'] ?? $inputs['file'] ?? null;

        if (is_string($requested) && '' !== trim($requested)) {
            $entry = $this->conversationFiles->findByReference($catalog, $requested);

            return null !== $entry && self::isExportable($entry) ? $entry : null;
        }

        if (is_array($requested)) {
            $path = $requested['local_path'] ?? $requested['path'] ?? null;
            if (!is_string($path) || '' === trim($path)) {
                return null;
            }
            $relative = $this->conversationFiles->normalizeRelativePath($path);
            foreach ($catalog as $entry) {
                if ($entry->relativePath === $relative && self::isExportable($entry)) {
                    return $entry;
                }
            }
        }

        return null;
    }

    /**
     * The catalog is ordered by how likely the user means a file — current
     * attachments, then this turn's upstream outputs, then the thread newest
     * first — so the first exportable office file is the one to convert.
     *
     * @param list<ConversationFile> $catalog
     */
    private function defaultEntry(array $catalog): ?ConversationFile
    {
        foreach ($catalog as $entry) {
            if (self::isExportable($entry)) {
                return $entry;
            }
        }

        return null;
    }

    private static function isExportable(ConversationFile $entry): bool
    {
        if (ConversationFile::CATEGORY_DOCUMENT !== $entry->category) {
            return false;
        }

        return DocumentThumbnailGenerator::isOffice(pathinfo($entry->relativePath, PATHINFO_EXTENSION));
    }

    private function loadFile(ConversationFile $entry, NodeContext $context): ?File
    {
        $userId = (int) ($context->userId ?? $context->message->getUserId());

        if (null !== $entry->fileId) {
            $file = $this->files->find($entry->fileId);

            return $file instanceof File && $file->getUserId() === $userId ? $file : null;
        }

        // `attached:N` entries are the current message's own attachments, in
        // marker order, and may not have an id yet.
        if (1 === preg_match('/^attached:(\d+)$/', $entry->reference, $m)) {
            $attachments = $this->conversationFiles->attachments($context->message);

            return $attachments[(int) $m[1] - 1] ?? null;
        }

        return null;
    }

    /**
     * SkillCatalogFactory builds runners without constructors for DB-free
     * planner-prompt tests; an unwired runner has no engine to offer.
     */
    private function engineConfigured(): bool
    {
        if (!(new \ReflectionProperty($this, 'exportService'))->isInitialized($this)) {
            return false;
        }

        return $this->exportService->isEnabled();
    }
}
