<template>
  <div class="space-y-6" data-testid="admin-ai-models-panel">
    <div class="surface-card p-6">
      <h2 class="text-xl font-semibold txt-primary mb-4">Add Models (Import)</h2>

      <div class="grid grid-cols-1 lg:grid-cols-2 gap-4">
        <div>
          <label class="block text-sm font-medium txt-secondary mb-2">URLs (one per line)</label>
          <textarea
            v-model="urlsText"
            class="w-full h-28 px-4 py-3 rounded-lg surface-card border border-light-border/30 dark:border-dark-border/20 txt-primary text-sm focus:outline-none focus:ring-2 focus:ring-[var(--brand)]"
            placeholder="https://platform.openai.com/docs/pricing"
          />
        </div>
        <div>
          <label class="block text-sm font-medium txt-secondary mb-2">Text dump (paste provider pricing/model list)</label>
          <textarea
            v-model="textDump"
            class="w-full h-28 px-4 py-3 rounded-lg surface-card border border-light-border/30 dark:border-dark-border/20 txt-primary text-sm focus:outline-none focus:ring-2 focus:ring-[var(--brand)]"
            placeholder="Paste tables, model lists, pricing paragraphs…"
          />
        </div>
      </div>

      <div class="mt-4 flex flex-wrap items-center gap-3">
        <label class="flex items-center gap-2 text-sm txt-secondary">
          <input v-model="allowDelete" type="checkbox" class="rounded border-light-border/30 dark:border-dark-border/20" />
          Allow DELETE statements
        </label>

        <button
          type="button"
          class="px-4 py-2 rounded-lg bg-[var(--brand)] text-white text-sm font-medium hover:opacity-90 transition"
          :disabled="importLoading"
          @click="generatePreview"
        >
          {{ importLoading ? 'Generating…' : 'Generate SQL' }}
        </button>

        <button
          type="button"
          class="px-4 py-2 rounded-lg border border-light-border/30 dark:border-dark-border/20 txt-primary text-sm font-medium hover:bg-black/5 dark:hover:bg-white/5 transition"
          :disabled="applyLoading || !sqlPreview || !validationOk"
          @click="applySql"
        >
          {{ applyLoading ? 'Applying…' : 'Apply SQL' }}
        </button>

      </div>

      <div class="mt-4">
        <label class="block text-sm font-medium txt-secondary mb-2">SQL preview</label>
        <textarea
          v-model="sqlPreview"
          class="w-full h-48 px-4 py-3 rounded-lg surface-card border border-light-border/30 dark:border-dark-border/20 font-mono text-xs txt-primary focus:outline-none focus:ring-2 focus:ring-[var(--brand)]"
          placeholder="Click “Generate SQL” to let the SORT model propose INSERT/UPDATE/DELETE statements…"
        />

        <div v-if="validationErrors.length > 0" class="mt-3 p-3 rounded-lg bg-red-500/5 border border-red-500/20">
          <div class="text-sm font-semibold text-red-500 mb-1">Validation errors</div>
          <ul class="text-sm txt-primary list-disc pl-5">
            <li v-for="(e, i) in validationErrors" :key="i">{{ e }}</li>
          </ul>
        </div>

        <div v-else-if="sqlPreview" class="mt-3 p-3 rounded-lg bg-green-500/5 border border-green-500/20">
          <div class="text-sm txt-primary">
            Validated: <span class="font-semibold">{{ statements.length }}</span> statement(s)
          </div>
          <div class="text-xs txt-secondary mt-1" v-if="aiProvider || aiModel">
            Generated by: {{ aiProvider || 'unknown' }} / {{ aiModel || 'unknown' }}
          </div>
        </div>
      </div>
    </div>

    <div class="surface-card p-6" data-testid="admin-ai-models-editor">
      <div class="flex items-center justify-between gap-3 mb-4">
        <h2 class="text-xl font-semibold txt-primary">Edit Models</h2>
        <button
          type="button"
          class="px-4 py-2 rounded-lg border border-light-border/30 dark:border-dark-border/20 txt-primary text-sm font-medium hover:bg-black/5 dark:hover:bg-white/5 transition"
          :disabled="modelsLoading"
          @click="loadModels"
        >
          Refresh
        </button>
      </div>

      <div class="grid grid-cols-1 md:grid-cols-4 gap-3 mb-4">
        <input v-model="newModel.service" class="px-3 py-2 rounded-lg surface-card border border-light-border/30 dark:border-dark-border/20 txt-primary text-sm" placeholder="Service (OpenAI)" />
        <input v-model="newModel.tag" class="px-3 py-2 rounded-lg surface-card border border-light-border/30 dark:border-dark-border/20 txt-primary text-sm" placeholder="Tag (chat)" />
        <input v-model="newModel.providerId" class="px-3 py-2 rounded-lg surface-card border border-light-border/30 dark:border-dark-border/20 txt-primary text-sm" placeholder="Provider ID (gpt-4.1)" />
        <input v-model="newModel.name" class="px-3 py-2 rounded-lg surface-card border border-light-border/30 dark:border-dark-border/20 txt-primary text-sm" placeholder="Name (GPT-4.1)" />
      </div>

      <div class="flex flex-wrap items-center gap-3 mb-6">
        <button
          type="button"
          class="px-4 py-2 rounded-lg bg-[var(--brand)] text-white text-sm font-medium hover:opacity-90 transition"
          :disabled="createLoading"
          @click="createModel"
        >
          {{ createLoading ? 'Creating…' : 'Create Model' }}
        </button>
        <div class="text-xs txt-secondary">
          Unique key: <span class="txt-primary font-semibold">BSERVICE + BTAG + BPROVID</span>
        </div>
      </div>

      <div v-if="modelsLoading" class="text-center py-8">
        <div class="inline-block animate-spin rounded-full h-8 w-8 border-b-2 border-[var(--brand)]"></div>
        <p class="mt-2 txt-secondary">Loading admin models…</p>
      </div>

      <div v-else class="overflow-x-auto scroll-thin">
        <table class="w-full min-w-[980px]">
          <thead>
            <tr class="border-b-2 border-light-border/30 dark:border-dark-border/20">
              <th class="text-left py-3 px-2 txt-secondary text-xs font-semibold uppercase tracking-wide">ID</th>
              <th class="text-left py-3 px-2 txt-secondary text-xs font-semibold uppercase tracking-wide">Service</th>
              <th class="text-left py-3 px-2 txt-secondary text-xs font-semibold uppercase tracking-wide">Tag</th>
              <th class="text-left py-3 px-2 txt-secondary text-xs font-semibold uppercase tracking-wide">Provider ID</th>
              <th class="text-left py-3 px-2 txt-secondary text-xs font-semibold uppercase tracking-wide">Name</th>
              <th class="text-left py-3 px-2 txt-secondary text-xs font-semibold uppercase tracking-wide">Selectable</th>
              <th class="text-left py-3 px-2 txt-secondary text-xs font-semibold uppercase tracking-wide">Active</th>
              <th class="text-left py-3 px-2 txt-secondary text-xs font-semibold uppercase tracking-wide">Price in</th>
              <th class="text-left py-3 px-2 txt-secondary text-xs font-semibold uppercase tracking-wide">Unit in</th>
              <th class="text-left py-3 px-2 txt-secondary text-xs font-semibold uppercase tracking-wide">Price out</th>
              <th class="text-left py-3 px-2 txt-secondary text-xs font-semibold uppercase tracking-wide">Unit out</th>
              <th class="text-left py-3 px-2 txt-secondary text-xs font-semibold uppercase tracking-wide">Actions</th>
            </tr>
          </thead>
          <tbody>
            <tr
              v-for="m in adminModels"
              :key="m.id"
              class="border-b border-light-border/10 dark:border-dark-border/10 hover:bg-black/5 dark:hover:bg-white/5 transition-colors"
            >
              <td class="py-2 px-2"><span class="pill text-xs">{{ m.id }}</span></td>
              <td class="py-2 px-2"><input v-model="m.service" class="w-32 px-2 py-1 rounded surface-card border border-light-border/30 dark:border-dark-border/20 txt-primary text-xs" /></td>
              <td class="py-2 px-2"><input v-model="m.tag" class="w-24 px-2 py-1 rounded surface-card border border-light-border/30 dark:border-dark-border/20 txt-primary text-xs" /></td>
              <td class="py-2 px-2"><input v-model="m.providerId" class="w-56 px-2 py-1 rounded surface-card border border-light-border/30 dark:border-dark-border/20 txt-primary text-xs" /></td>
              <td class="py-2 px-2"><input v-model="m.name" class="w-44 px-2 py-1 rounded surface-card border border-light-border/30 dark:border-dark-border/20 txt-primary text-xs" /></td>
              <td class="py-2 px-2">
                <select v-model.number="m.selectable" class="px-2 py-1 rounded surface-card border border-light-border/30 dark:border-dark-border/20 txt-primary text-xs">
                  <option :value="0">0</option>
                  <option :value="1">1</option>
                </select>
              </td>
              <td class="py-2 px-2">
                <select v-model.number="m.active" class="px-2 py-1 rounded surface-card border border-light-border/30 dark:border-dark-border/20 txt-primary text-xs">
                  <option :value="0">0</option>
                  <option :value="1">1</option>
                </select>
              </td>
              <td class="py-2 px-2"><input v-model.number="m.priceIn" type="number" step="0.000001" class="w-24 px-2 py-1 rounded surface-card border border-light-border/30 dark:border-dark-border/20 txt-primary text-xs" /></td>
              <td class="py-2 px-2"><input v-model="m.inUnit" class="w-24 px-2 py-1 rounded surface-card border border-light-border/30 dark:border-dark-border/20 txt-primary text-xs" /></td>
              <td class="py-2 px-2"><input v-model.number="m.priceOut" type="number" step="0.000001" class="w-24 px-2 py-1 rounded surface-card border border-light-border/30 dark:border-dark-border/20 txt-primary text-xs" /></td>
              <td class="py-2 px-2"><input v-model="m.outUnit" class="w-24 px-2 py-1 rounded surface-card border border-light-border/30 dark:border-dark-border/20 txt-primary text-xs" /></td>
              <td class="py-2 px-2">
                <div class="flex items-center gap-2">
                  <button
                    type="button"
                    class="px-3 py-1 rounded-lg bg-[var(--brand)] text-white text-xs font-medium hover:opacity-90 transition"
                    :disabled="rowSavingId === m.id"
                    @click="saveModel(m)"
                  >
                    {{ rowSavingId === m.id ? 'Saving…' : 'Save' }}
                  </button>
                  <button
                    type="button"
                    class="px-3 py-1 rounded-lg border border-red-500/40 text-red-500 text-xs font-medium hover:bg-red-500/10 transition"
                    :disabled="rowDeletingId === m.id"
                    @click="deleteModel(m)"
                  >
                    {{ rowDeletingId === m.id ? 'Deleting…' : 'Delete' }}
                  </button>
                </div>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { useNotification } from '@/composables/useNotification'
import { adminModelsApi, type AdminModel } from '@/services/api/adminModelsApi'

interface NewModel {
  service: string
  tag: string
  providerId: string
  name: string
}

const { success, error: showError } = useNotification()

const urlsText = ref('')
const textDump = ref('')
const allowDelete = ref(false)

const importLoading = ref(false)
const applyLoading = ref(false)

const sqlPreview = ref('')
const validationErrors = ref<string[]>([])
const statements = ref<string[]>([])
const aiProvider = ref<string | null>(null)
const aiModel = ref<string | null>(null)

const adminModels = ref<AdminModel[]>([])
const modelsLoading = ref(false)
const createLoading = ref(false)
const rowSavingId = ref<number | null>(null)
const rowDeletingId = ref<number | null>(null)

const newModel = ref<NewModel>({
  service: '',
  tag: '',
  providerId: '',
  name: '',
})

const validationOk = computed(() => validationErrors.value.length === 0 && statements.value.length > 0)

function parseUrls(): string[] {
  return urlsText.value
    .split('\n')
    .map(s => s.trim())
    .filter(Boolean)
}

async function generatePreview() {
  importLoading.value = true
  validationErrors.value = []
  statements.value = []
  try {
    const res = await adminModelsApi.importPreview({
      urls: parseUrls(),
      textDump: textDump.value,
      allowDelete: allowDelete.value,
    })
    sqlPreview.value = res.sql
    aiProvider.value = res.ai.provider
    aiModel.value = res.ai.model
    validationErrors.value = res.validation.errors || []
    statements.value = res.validation.statements || []
  } catch (e: any) {
    showError(e?.response?.data?.error || 'Failed to generate SQL')
  } finally {
    importLoading.value = false
  }
}

async function applySql() {
  applyLoading.value = true
  try {
    const res = await adminModelsApi.importApply({ sql: sqlPreview.value })
    success(`Applied ${res.applied} statement(s)`)
    await loadModels()
  } catch (e: any) {
    showError(e?.response?.data?.error || 'Failed to apply SQL')
  } finally {
    applyLoading.value = false
  }
}

async function loadModels() {
  modelsLoading.value = true
  try {
    const res = await adminModelsApi.list()
    adminModels.value = res.models
  } catch (e: any) {
    showError(e?.response?.data?.error || 'Failed to load admin models')
  } finally {
    modelsLoading.value = false
  }
}

async function createModel() {
  createLoading.value = true
  try {
    const payload = {
      service: newModel.value.service.trim(),
      tag: newModel.value.tag.trim(),
      providerId: newModel.value.providerId.trim(),
      name: newModel.value.name.trim(),
    }
    await adminModelsApi.create(payload)
    success('Model created')
    newModel.value = { service: '', tag: '', providerId: '', name: '' }
    await loadModels()
  } catch (e: any) {
    showError(e?.response?.data?.error || 'Failed to create model')
  } finally {
    createLoading.value = false
  }
}

async function saveModel(m: AdminModel) {
  rowSavingId.value = m.id
  try {
    await adminModelsApi.update(m.id, {
      service: m.service,
      tag: m.tag,
      providerId: m.providerId,
      name: m.name,
      selectable: m.selectable,
      active: m.active,
      priceIn: m.priceIn,
      inUnit: m.inUnit,
      priceOut: m.priceOut,
      outUnit: m.outUnit,
      quality: m.quality,
      rating: m.rating,
      description: m.description,
      json: m.json,
    })
    success('Model saved')
  } catch (e: any) {
    showError(e?.response?.data?.error || 'Failed to save model')
    await loadModels()
  } finally {
    rowSavingId.value = null
  }
}

async function deleteModel(m: AdminModel) {
  if (!confirm(`Delete model ${m.id} (${m.service}/${m.tag}/${m.providerId})?`)) return
  rowDeletingId.value = m.id
  try {
    await adminModelsApi.delete(m.id)
    success('Model deleted')
    await loadModels()
  } catch (e: any) {
    showError(e?.response?.data?.error || 'Failed to delete model')
  } finally {
    rowDeletingId.value = null
  }
}

onMounted(async () => {
  await loadModels()
})
</script>


