#!/bin/bash
set -euo pipefail

# Materialize PHP runtime config from the synaplan-base-php image:
#   - render PHP_*/FRANKENPHP_* env-var overrides into 99-synaplan-env.ini
#   - activate the dev override (templates/synaplan-dev.ini) when APP_ENV=dev
#   - write /etc/caddy/synaplan-worker-mode.Caddyfile (real snippet in prod,
#     empty stub in dev) so the Caddyfile `import` is always safe
# Source (don't exec) so we keep the parent shell's set -euo pipefail.
# shellcheck source=/dev/null
source /usr/local/bin/synaplan-php-configure

# Locate shared role helpers both in the production image and when the script is
# run directly from a repository checkout by shell characterization tests.
_RUNTIME_LIB=""
for _candidate in \
    "$(dirname "$0")/lib/container-runtime.sh" \
    "/usr/local/bin/lib/container-runtime.sh"; do
    if [ -r "$_candidate" ]; then
        _RUNTIME_LIB="$_candidate"
        break
    fi
done

if [ -z "$_RUNTIME_LIB" ]; then
    echo "❌ ERROR: container-runtime.sh not found"
    exit 1
fi

# shellcheck disable=SC1090
. "$_RUNTIME_LIB"

SYNAPLAN_ROLE="${SYNAPLAN_ROLE:-web}"
export SYNAPLAN_ROLE
case "$SYNAPLAN_ROLE" in
    web|worker|scheduler) ;;
    *)
        echo "❌ ERROR: Unsupported SYNAPLAN_ROLE '${SYNAPLAN_ROLE}'. Expected web, worker, or scheduler."
        exit 64
        ;;
esac

# Boot milestones for the dev onboarding page (mirrors the ollama-download.json
# pattern below). The dev stack's boot-status server reads this file through a
# read-only bind mount of backend/var and shows the user WHICH boot step is
# running instead of a silent multi-minute wait. Only the web role writes it —
# worker/scheduler share the same var/ directory and must not fight over it.
# Every write is best-effort: a failure here must never break the boot.
BOOT_STATUS_FILE="${BOOT_STATUS_FILE:-/var/www/backend/var/boot-status.json}"
write_boot_status() {
    # $1 phase  $2 human-readable message (optional)
    [ "$SYNAPLAN_ROLE" = "web" ] || return 0
    mkdir -p "$(dirname "$BOOT_STATUS_FILE")" 2>/dev/null || return 0
    printf '{"phase":"%s","message":"%s","updatedAt":"%s"}\n' \
        "$1" "${2:-}" "$(date -u +%Y-%m-%dT%H:%M:%SZ)" \
        > "${BOOT_STATUS_FILE}.tmp" 2>/dev/null \
        && mv "${BOOT_STATUS_FILE}.tmp" "$BOOT_STATUS_FILE" 2>/dev/null \
        || true
}

write_boot_status "initializing" "Backend container started"

# Test mode: disable the PHP 8.4 tracing JIT and re-stat .php files.
#
# The base image (synaplan-base-php >= 1.0.0) ships production-tuned OPcache
# settings: `opcache.validate_timestamps=0`, `opcache.jit=tracing`, JIT buffer
# 128M. Those defaults are correct for prod but caused non-deterministic
# Doctrine schema-introspection failures inside `bin/console
# doctrine:migrations:migrate` under PHP 8.4 in CI — different test runs
# reported different missing tables for the same migration code, the
# fingerprint of a tracing-JIT bug.
#
# We deliberately keep OPcache *enabled* (as in dev) — turning it off
# entirely makes every `php bin/console` invocation and every FrankenPHP
# request 30-60x slower (Symfony has to reflect ~25k vendor classes from
# disk on every hit), which then makes streaming chat endpoints slow enough
# that the frontend abort logic / chat-id watcher trips and replaces the
# AI response with a "cancelled by user" notice — breaking unrelated E2E
# tests.
#
# What this override actually does (mirrors templates/synaplan-dev.ini):
#   - opcache stays enabled, but stat()s files on every request so test
#     code edits take effect without a container rebuild.
#   - JIT is disabled, side-stepping the PHP 8.4 tracing-JIT bugs.
#   - assertions stay on, errors are surfaced.
# The base image only auto-applies these for APP_ENV=dev; we extend the
# same treatment to APP_ENV=test here.
#
# We write a 99-* override so it loads after every other ini in conf.d
# (including the 99-synaplan-env.ini the configure shim just wrote).
if [ "${APP_ENV:-prod}" = "test" ]; then
    cat > /usr/local/etc/php/conf.d/99-synaplan-test.ini <<'EOF'
; Auto-generated by docker-entrypoint.sh when APP_ENV=test.
; Mirrors the base image's APP_ENV=dev profile (templates/synaplan-dev.ini):
; OPcache stays on, but JIT is disabled and timestamps revalidate every
; request. Disabling JIT side-steps PHP 8.4 tracing-JIT bugs that produced
; random Doctrine schema-introspection failures during migrations in CI.
opcache.validate_timestamps = 1
opcache.revalidate_freq     = 0
opcache.jit                 = disable
opcache.jit_buffer_size     = 0
zend.assertions             = 1
display_errors              = On
display_startup_errors      = On
EOF
    echo "🧪 APP_ENV=test → OPcache JIT disabled, timestamps revalidate (mirrors dev profile)"
fi

echo "🚀 Starting Synaplan Backend..."

# Create empty .env file if it doesn't exist
# This is needed for Symfony's Dotenv component to work properly
if [ ! -f /var/www/backend/.env ]; then
    echo "📝 Creating empty .env file..."
    touch /var/www/backend/.env
fi

# Fix .env ownership to match the parent directory (host user's UID/GID on bind-mounts).
# Runs on every startup to repair root-owned files from previous container runs.
EXPECTED_OWNER="$(stat -c %u:%g /var/www/backend 2>/dev/null)" || true
if [ -n "$EXPECTED_OWNER" ]; then
    CURRENT_OWNER="$(stat -c %u:%g /var/www/backend/.env 2>/dev/null)" || true
    if [ "$CURRENT_OWNER" != "$EXPECTED_OWNER" ]; then
        chown "$EXPECTED_OWNER" /var/www/backend/.env 2>/dev/null || true
    fi
fi

# Source .env file as defaults (existing env vars from docker-compose take precedence)
if [ -f /var/www/backend/.env ]; then
    echo "📄 Loading defaults from .env file (existing env vars take precedence)..."
    while IFS='=' read -r key value; do
        # Skip comments and empty lines
        [[ -z "$key" || "$key" =~ ^[[:space:]]*# ]] && continue
        # Trim whitespace from key
        key="$(echo "$key" | tr -d '[:space:]')"
        # Skip invalid variable names
        [[ "$key" =~ ^[a-zA-Z_][a-zA-Z0-9_]*$ ]] || continue
        # Only export if not already set in environment
        if [ -z "${!key+x}" ]; then
            # Strip surrounding quotes from value
            value="${value#\"}" ; value="${value%\"}"
            value="${value#\'}" ; value="${value%\'}"
            export "${key}=${value}"
        fi
    done < /var/www/backend/.env
fi

# Validate required environment variables
if [ -z "${APP_URL:-}" ]; then
    echo "❌ ERROR: APP_URL is not set!"
    echo "   APP_URL is required for the application to work correctly."
    echo "   Please set it in your environment or .env file."
    echo "   Example: APP_URL=https://synaplan.example.com"
    exit 1
fi

# Tier 1 of the first-admin bootstrap guard: the pairing rule, checked here
# because it is free — it needs only the environment that was just loaded, no
# vendor/ and no PHP — so the most common mistake fails within milliseconds.
# Tier 2 (require_valid_bootstrap_admin_config) validates the remaining rules
# with the application's own validator once vendor/ is guaranteed to exist; see
# below, after the /docker-entrypoint.d block. Both tiers apply to every role,
# since all of them receive the same environment.
require_bootstrap_admin_pair

# Build DATABASE URLs from environment variables if not already set
# Fallback for deployments that provide DB credentials as separate env vars
if [ -z "${DATABASE_WRITE_URL:-}" ] && [ -n "${DB_HOST:-}" ]; then
    # URL-encode the password to handle special characters (using jq)
    DB_PASSWORD_ENCODED=$(printf %s "${DB_PASSWORD:-}" | jq -sRr @uri)
    # Default to MariaDB platform identifier ("mariadb-" prefix) so DBAL picks
    # MariaDBPlatform and applies the MariaDB-specific schema introspection
    # (string default quote-stripping etc.). See docs/MIGRATIONS.md for why.
    export DATABASE_WRITE_URL="mysql://${DB_USER:-synaplan}:${DB_PASSWORD_ENCODED}@${DB_HOST}:${DB_PORT:-3306}/${DB_NAME:-synaplan}?serverVersion=${DB_SERVER_VERSION:-mariadb-12.2.2}&charset=utf8mb4"
    export DATABASE_READ_URL="${DATABASE_WRITE_URL}"
    echo "✅ Built DATABASE URLs from environment variables"
fi

# Run additional startup scripts from docker-entrypoint.d (if any)
# Useful for dev environments to mount custom initialization scripts
write_boot_status "dependencies" "Installing backend dependencies"
if [ -d "/docker-entrypoint.d" ]; then
    # Check if directory has any files (avoid empty glob expansion)
    if compgen -G "/docker-entrypoint.d/*" > /dev/null; then
        echo "🔧 Running additional startup scripts from /docker-entrypoint.d/..."
        for f in /docker-entrypoint.d/*; do
            # In dev mode, skip ownership check (scripts are mounted from host with host user ownership)
            # In production, verify the file is owned by root and not world-writable
            if [ "${APP_ENV:-prod}" != "dev" ]; then
                if [ ! -O "$f" ] || [ -k "$f" ]; then
                    echo "   ⚠️  Skipping unsafe file: $(basename "$f") (not owned by current user or has sticky bit)"
                    continue
                fi
            fi
            if [ -x "$f" ]; then
                echo "   Executing: $(basename "$f")"
                "$f"
            elif [ -f "$f" ]; then
                echo "   ⚠️  Skipping non-executable: $(basename "$f")"
            fi
        done
        echo "✅ Additional startup scripts completed"
    fi
fi

if [ -z "${GROQ_API_KEY:-}" ]; then
cat <<'EOM'
=====================================================================
🚀  GROQ TIP
💥  groq.com has fast, cheap and good models - get your free key there
💥  and put it into backend/.env (GROQ_API_KEY=...) to unlock them!
=====================================================================
EOM
fi

# Ensure writable directories exist and have correct permissions
# This runs on every startup to handle volume mounts (Mac/Linux compatibility)
mkdir -p /var/www/backend/var/cache /var/www/backend/var/log /var/www/backend/var/uploads /var/www/backend/public/up

# Fix ownership and permissions recursively (works on both Mac and Linux)
# -R flag handles all subdirectories and files, no need for separate find commands
chown -R www-data:www-data /var/www/backend/var /var/www/backend/public/up 2>/dev/null || true
chmod -R 775 /var/www/backend/var /var/www/backend/public/up 2>/dev/null || true

# Regenerate autoloader if plugins directory exists and has content
# This MUST happen BEFORE any php bin/console commands because Symfony bootstrapping
# will try to compile services from plugins. The Docker image is built without /plugins
# (it's mounted at runtime) and --classmap-authoritative prevents Composer from
# scanning for new classes at runtime.
PLUGINS_DIR="${PLUGINS_DIR:-/plugins}"
if [ -d "$PLUGINS_DIR" ] && [ "$(ls -A "$PLUGINS_DIR" 2>/dev/null)" ]; then
    echo "🔌 Plugins detected in $PLUGINS_DIR - regenerating autoloader..."
    # Use --optimize to maintain performance, but without --classmap-authoritative
    # so that plugin classes can be discovered at runtime
    composer dump-autoload --optimize --no-interaction 2>&1 || {
        echo "⚠️  Failed to regenerate autoloader for plugins"
        echo "   This may cause plugin loading failures"
    }
    echo "✅ Autoloader regenerated with plugin support"
fi

# Tier 2 of the first-admin bootstrap guard: the complete rule set, decided by
# the application's own validator (App\Service\Admin\BootstrapAdminConfiguration).
#
# This is the earliest point where that is possible: it needs vendor/, which the
# dev stack only populates in the /docker-entrypoint.d block above, and it must
# see the plugin-aware autoloader regenerated just above it. It still runs before
# the role dispatch, the database wait, the migrations and the seeders below, so
# an invalid email or password fails in seconds instead of crash-looping the
# container after every full initialization attempt.
#
# Completely inert when neither bootstrap variable is set.
require_valid_bootstrap_admin_config

# Non-web roles share the same environment and filesystem preparation above,
# but never run migrations or seeders. They wait for the web role to complete
# database initialization before starting their long-running process.
case "$SYNAPLAN_ROLE" in
    worker)
        run_worker_role
        ;;
    scheduler)
        run_scheduler_role
        exit $?
        ;;
esac

# Wait for database to be ready
write_boot_status "waiting-for-database" "Waiting for the database"
wait_for_database 0 2

# Run database migrations.
#
# The bootstrap is implemented in a sourceable library so the same code runs in
# production and in the bash-level tests under _docker/backend/tests/.
# See lib/migrations-bootstrap.sh for the full self-healing contract.
echo "🔄 Running database migrations..."
write_boot_status "migrating" "Setting up the database structure"

# Locate the bootstrap library regardless of how the entrypoint was invoked.
#   - Production image: `$(dirname "$0")` resolves to /usr/local/bin, where
#     the Dockerfile copies both the entrypoint and `lib/`.
#   - Running the entrypoint directly from a repo checkout (tests, local
#     debugging): the library sits next to the script in `_docker/backend/lib/`.
# The `/usr/local/bin/lib/...` fallback is kept as a belt-and-suspenders path
# in case `$0` is a symlink or otherwise can't be resolved.
_MIGRATIONS_LIB=""
for _candidate in \
    "$(dirname "$0")/lib/migrations-bootstrap.sh" \
    "/usr/local/bin/lib/migrations-bootstrap.sh"; do
    if [ -r "$_candidate" ]; then
        _MIGRATIONS_LIB="$_candidate"
        break
    fi
done

if [ -z "$_MIGRATIONS_LIB" ]; then
    echo "❌ ERROR: migrations-bootstrap.sh not found; aborting to avoid replaying DDL on legacy DBs"
    exit 1
fi

# shellcheck disable=SC1090
. "$_MIGRATIONS_LIB"

# run_migrations_with_retry re-runs the idempotent bootstrap before each attempt,
# so a failed first start (transient DB error, or a crash mid-baseline that left
# orphan tables) self-heals within this same start instead of crash-looping.
run_migrations_with_retry "" "main"
echo "✅ Database migrations applied!"

# Same flow for the test database (PHPUnit + DAMA transaction rollback).
#
# Best-effort and non-fatal in dev: a broken OR missing test DB must never
# block the dev backend from starting. Depending on which compose file is
# active, the `db_test` host referenced in backend/.env.test may not exist
# (it ships with docker-compose.test.yml's separate test-stack, not the
# default dev stack). When it is missing, every `--env=test` console call
# fails to connect — so we run the self-healing bootstrap inside a subshell
# whose non-zero exit is swallowed, and capture its output so a missing test
# DB doesn't spam the dev log with confusing `Connection refused` traces. To
# debug the test bootstrap, run the same commands manually inside the container.
if [ "$APP_ENV" = "dev" ]; then
    echo "🔄 Migrating test database (best-effort)..."
    _test_bootstrap_failed=0
    (
        set -e
        run_migrations_with_retry "--env=test" "test"
    ) >/dev/null 2>&1 || _test_bootstrap_failed=1

    if [ "$_test_bootstrap_failed" -eq 0 ]; then
        echo "✅ Test database migrations applied!"
    else
        echo "ℹ️  Test database unreachable — skipping (expected unless docker-compose.test.yml is active)."
    fi
    unset _test_bootstrap_failed
fi

# Load demo user fixtures FIRST (dev/test only, when DB is fresh).
# Important: doctrine:fixtures:load purges ALL entity tables before reloading.
# We therefore run fixtures BEFORE app:seed so the idempotent seed step can
# re-populate models/prompts/config/rate-limits afterwards.
#
# SEED_DEMO_DATA=false opts out inside dev/test and leaves the database without
# a single user, which is the only way to reach the first-run setup wizard
# locally (production never loads fixtures anyway). Default stays true, so
# `docker compose up -d` and the E2E suite are unchanged.
FIXTURES_MARKER="/var/www/backend/var/.fixtures_loaded"

write_boot_status "seeding" "Loading starter data"
if [ "${SEED_DEMO_DATA:-true}" != "true" ]; then
    echo "⏭️  SEED_DEMO_DATA=${SEED_DEMO_DATA} → skipping demo user fixtures."
    echo "   🧭 An empty database starts in first-run setup: open http://localhost:5173/setup"
elif [ "$APP_ENV" = "dev" ] || [ "$APP_ENV" = "test" ]; then
    # If marker exists but DB is empty (e.g. tmpfs wipe, or marker on host volume after down/up), remove stale marker so we load fixtures
    if [ -f "$FIXTURES_MARKER" ]; then
        _uc=$(php bin/console dbal:run-sql "SELECT COUNT(*) as count FROM BUSER" 2>/dev/null | grep -oE '[0-9]+' | tail -1)
        if [ "${_uc:-0}" -eq 0 ]; then
            rm -f "$FIXTURES_MARKER" 2>/dev/null || true
        fi
    fi

    if [ -f "$FIXTURES_MARKER" ]; then
        echo "✅ Demo user fixtures already loaded (marker present)"
        echo "   👤 Login: admin@synaplan.com / admin123"
        echo "   💡 To reload: rm backend/var/.fixtures_loaded && docker compose restart backend"
    else
        # Check if users actually exist in database (not just marker file)
        USER_COUNT=$(php bin/console dbal:run-sql "SELECT COUNT(*) as count FROM BUSER" 2>/dev/null | grep -oE '[0-9]+' | tail -1)
        USER_COUNT=${USER_COUNT:-0}

        if [ "$USER_COUNT" -eq 0 ]; then
            echo "🌱 Loading demo user fixtures (current users: $USER_COUNT)..."
            # Note: Not using --purge-with-truncate because TRUNCATE fails with foreign key constraints
            if php bin/console doctrine:fixtures:load --no-interaction 2>&1 | tee /tmp/fixtures.log; then
                if grep -q "loading App" /tmp/fixtures.log; then
                    touch "$FIXTURES_MARKER"
                    echo "✅ Demo user fixtures loaded!"
                    echo "   👤 Admin: admin@synaplan.com / admin123"
                    echo "   👤 Demo:  demo@synaplan.com / demo123"
                    echo "   👤 Test:  test@example.com / test123"
                else
                    echo "⚠️  Fixtures might have failed - check logs"
                fi
            else
                echo "❌ Fixtures loading failed!"
                echo "   Please run manually: docker compose exec backend php bin/console doctrine:fixtures:load"
            fi
        else
            touch "$FIXTURES_MARKER"
            echo "✅ Demo user fixtures already present ($USER_COUNT users)"
            echo "   👤 Login: admin@synaplan.com / admin123"
            echo "   💡 To reload: rm backend/var/.fixtures_loaded && docker compose restart backend"
        fi
    fi
fi

# Seed production-essential catalogs (idempotent, safe in dev + prod).
# Runs AFTER fixtures so a fresh dev DB ends up with both demo users and full
# model/prompt/config catalogs. In prod this is the sole data-initialisation step.
echo "🌱 Seeding catalogs (idempotent)..."
php bin/console app:seed --no-interaction || {
    echo "⚠️  app:seed failed — see logs above. Continuing startup."
}

# Point chat at a provider that actually has a key. The seeded default is a
# cloud provider, so an install that only configured a different one (or none)
# would otherwise greet the user with an "invalid API key" error. No-op when the
# current default already works or was deliberately set to a keyless provider.
echo "🔌 Checking default AI provider..."
php bin/console app:provider:apply-defaults --auto --no-interaction || {
    echo "⚠️  Could not verify the default AI provider — continuing startup."
}

# Managed deployments may provide first-admin credentials. The command is
# intentionally called only when at least one bootstrap value is present, so
# existing development and self-host behavior remains unchanged. The command
# validates incomplete configuration and is idempotent after an admin exists.
if [ -n "${BOOTSTRAP_ADMIN_EMAIL:-}" ] || [ -n "${BOOTSTRAP_ADMIN_PASSWORD:-}" ]; then
    echo "👤 Bootstrapping initial administrator..."
    php bin/console app:bootstrap-admin --no-interaction
fi

# Ollama model downloads (optional, only if AUTO_DOWNLOAD_MODELS=true).
# Progress is mirrored to var/ollama-download.json for GET /api/v1/config/local-ai/status.
OLLAMA_STATUS_FILE="${OLLAMA_STATUS_FILE:-/var/www/backend/var/ollama-download.json}"

write_ollama_download_status() {
    # $1 status  $2 currentModel  $3 percent (number or empty)  $4 message
    local status="$1"
    local current_model="${2:-}"
    local percent="${3:-}"
    local message="${4:-}"
    local updated_at
    updated_at="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
    mkdir -p "$(dirname "$OLLAMA_STATUS_FILE")"

    if command -v jq >/dev/null 2>&1; then
        local percent_json="null"
        if [ -n "$percent" ]; then
            percent_json="$percent"
        fi
        jq -n \
            --arg status "$status" \
            --arg currentModel "$current_model" \
            --argjson percent "$percent_json" \
            --arg message "$message" \
            --arg updatedAt "$updated_at" \
            '{
                status: $status,
                currentModel: (if $currentModel == "" then null else $currentModel end),
                percent: $percent,
                message: (if $message == "" then null else $message end),
                models: [],
                updatedAt: $updatedAt
            }' > "${OLLAMA_STATUS_FILE}.tmp" && mv "${OLLAMA_STATUS_FILE}.tmp" "$OLLAMA_STATUS_FILE"
    else
        # Minimal fallback when jq is unavailable (should not happen in our image).
        printf '{"status":"%s","currentModel":%s,"percent":%s,"message":%s,"models":[],"updatedAt":"%s"}\n' \
            "$status" \
            "$([ -n "$current_model" ] && printf '"%s"' "$current_model" || echo null)" \
            "$([ -n "$percent" ] && echo "$percent" || echo null)" \
            "$([ -n "$message" ] && printf '"%s"' "$message" || echo null)" \
            "$updated_at" > "${OLLAMA_STATUS_FILE}.tmp" && mv "${OLLAMA_STATUS_FILE}.tmp" "$OLLAMA_STATUS_FILE"
    fi
}

if [ -n "${OLLAMA_BASE_URL:-}" ] && [ "${AUTO_DOWNLOAD_MODELS:-false}" = "true" ]; then
    echo ""
    echo "🤖 AUTO_DOWNLOAD_MODELS=true - Starting AI model downloads in background..."
    write_ollama_download_status "waiting" "" "" "Waiting for Ollama service"

    (
        echo "[Background] Waiting for Ollama service..."
        until curl -f "$OLLAMA_BASE_URL/api/tags" > /dev/null 2>&1; do
            sleep 3
        done
        echo "[Background] ✅ Ollama ready, downloading models..."
        write_ollama_download_status "downloading" "" "0" "Ollama ready, starting model downloads"

        MODELS=("bge-m3")
        # Default OFF, matching docker-compose.yml: pulling the chat model is a
        # ~14 GB download, so it must stay an explicit opt-in — also for a bare
        # `docker run` that does not go through compose.
        if [ "${ENABLE_LOCAL_GPT_OSS:-false}" = "true" ]; then
            MODELS+=("gpt-oss:20b")
        fi
        DOWNLOAD_FAILED=0
        for MODEL in "${MODELS[@]}"; do
            # Ollama reports untagged models with an implicit ":latest", so a bare
            # name never matched here and every restart re-issued a pull.
            case "$MODEL" in
                *:*) MODEL_TAG="$MODEL" ;;
                *) MODEL_TAG="$MODEL:latest" ;;
            esac
            if ! curl -s "$OLLAMA_BASE_URL/api/tags" | grep -qE "\"name\":\"($MODEL|$MODEL_TAG)\""; then
                echo "[Background] 📥 Downloading $MODEL..."
                write_ollama_download_status "downloading" "$MODEL" "0" "Downloading $MODEL"
                LAST_MILESTONE=-1
                if curl -sS -N "$OLLAMA_BASE_URL/api/pull" \
                    -H "Content-Type: application/json" \
                    -d "{\"name\":\"$MODEL\"}" | while IFS= read -r line; do
                        [ -z "$line" ] && continue

                        # Parse JSON fields using sed
                        STATUS=$(echo "$line" | sed -n 's/.*"status":"\([^"]*\)".*/\1/p')
                        COMPLETED=$(echo "$line" | sed -n 's/.*"completed":\([0-9]*\).*/\1/p')
                        TOTAL=$(echo "$line" | sed -n 's/.*"total":\([0-9]*\).*/\1/p')

                        if [ -n "$COMPLETED" ] && [ -n "$TOTAL" ] && [ "$TOTAL" -gt 0 ]; then
                            PERCENT=$((COMPLETED * 100 / TOTAL))
                            MB_COMPLETED=$((COMPLETED / 1048576))
                            MB_TOTAL=$((TOTAL / 1048576))

                            # Only print / write at 10, 20, 30...90, 100% milestones
                            MILESTONE=$((PERCENT - PERCENT % 10))
                            if [ $PERCENT -gt 0 ] && [ $((PERCENT % 10)) -lt 2 ]; then
                                if [ "$MILESTONE" -ne "$LAST_MILESTONE" ]; then
                                    LAST_MILESTONE=$MILESTONE
                                    echo "[Background] [${MODEL}] ${STATUS} - ${MB_COMPLETED}MB/${MB_TOTAL}MB (${MILESTONE}%)"
                                    write_ollama_download_status "downloading" "$MODEL" "$MILESTONE" "Downloading $MODEL"
                                fi
                            fi
                        elif [ -n "$STATUS" ]; then
                            # Show important status changes
                            case "$STATUS" in
                                "pulling manifest"|"verifying sha256"|"success")
                                    echo "[Background] [${MODEL}] ${STATUS}"
                                    ;;
                            esac
                        fi
                    done; then
                    echo "[Background] ✅ $MODEL downloaded!"
                    write_ollama_download_status "downloading" "$MODEL" "100" "$MODEL ready"
                else
                    echo "[Background] ⚠️  $MODEL download failed"
                    DOWNLOAD_FAILED=1
                    write_ollama_download_status "error" "$MODEL" "" "Download failed for $MODEL"
                fi
            else
                echo "[Background] ✅ $MODEL already available"
                write_ollama_download_status "downloading" "$MODEL" "100" "$MODEL already available"
            fi
        done
        if [ "$DOWNLOAD_FAILED" -eq 0 ]; then
            echo "[Background] 🎉 Model downloads completed!"
            write_ollama_download_status "ready" "" "100" "Local AI models ready"
        fi
    ) &

    echo "✅ Model download started in background"
else
    # Clear any status left behind by an earlier run, otherwise the UI keeps
    # showing a download that is no longer happening.
    write_ollama_download_status "idle" "" "" ""
    echo ""
    echo "⏭️  Skipping automatic model downloads"
    echo "   💡 Tip: Use 'AUTO_DOWNLOAD_MODELS=true docker compose up -d'"
    echo "   Models will download automatically when first used"
fi

# Clear and warmup cache
echo "🧹 Clearing cache..."
write_boot_status "warming-up" "Warming up caches"
php bin/console cache:clear
echo "✅ Cache ready!"

# Start FrankenPHP
echo ""
echo "🎉 Backend ready! Starting FrankenPHP..."
echo "   🌐 Frontend: ${APP_URL}"
echo "   🌐 API: ${APP_URL}/api"
echo "   📚 Swagger: ${APP_URL}/api/doc"
echo ""

write_boot_status "web-starting" "Starting the web server"
exec frankenphp run --config /etc/caddy/Caddyfile
