<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: grpc_service.proto

namespace Inference;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 *\@\@
 *\@\@.. cpp:var:: message CudaSharedMemoryStatusRequest
 *\@\@
 *\@\@   Request message for CudaSharedMemoryStatus.
 *\@\@
 *
 * Generated from protobuf message <code>inference.CudaSharedMemoryStatusRequest</code>
 */
class CudaSharedMemoryStatusRequest extends \Google\Protobuf\Internal\Message
{
    /**
     *\@\@
     *\@\@  .. cpp:var:: string name
     *\@\@
     *\@\@     The name of the region to get status for. If empty the
     *\@\@     status is returned for all registered regions.
     *\@\@
     *
     * Generated from protobuf field <code>string name = 1;</code>
     */
    protected $name = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *          \@\@
     *          \@\@  .. cpp:var:: string name
     *          \@\@
     *          \@\@     The name of the region to get status for. If empty the
     *          \@\@     status is returned for all registered regions.
     *          \@\@
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\GrpcService::initOnce();
        parent::__construct($data);
    }

    /**
     *\@\@
     *\@\@  .. cpp:var:: string name
     *\@\@
     *\@\@     The name of the region to get status for. If empty the
     *\@\@     status is returned for all registered regions.
     *\@\@
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     *\@\@
     *\@\@  .. cpp:var:: string name
     *\@\@
     *\@\@     The name of the region to get status for. If empty the
     *\@\@     status is returned for all registered regions.
     *\@\@
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

}

