<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: grpc_service.proto

namespace Inference;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 *\@\@
 *\@\@.. cpp:var:: message InferTensorContents
 *\@\@
 *\@\@   The data contained in a tensor represented by the repeated type
 *\@\@   that matches the tensor's data type. Protobuf oneof is not used
 *\@\@   because oneofs cannot contain repeated fields.
 *\@\@
 *
 * Generated from protobuf message <code>inference.InferTensorContents</code>
 */
class InferTensorContents extends \Google\Protobuf\Internal\Message
{
    /**
     *\@\@
     *\@\@  .. cpp:var:: bool bool_contents (repeated)
     *\@\@
     *\@\@     Representation for BOOL data type. The size must match what is
     *\@\@     expected by the tensor's shape. The contents must be the flattened,
     *\@\@     one-dimensional, row-major order of the tensor elements.
     *\@\@
     *
     * Generated from protobuf field <code>repeated bool bool_contents = 1;</code>
     */
    private $bool_contents;
    /**
     *\@\@
     *\@\@  .. cpp:var:: int32 int_contents (repeated)
     *\@\@
     *\@\@     Representation for INT8, INT16, and INT32 data types. The size
     *\@\@     must match what is expected by the tensor's shape. The contents
     *\@\@     must be the flattened, one-dimensional, row-major order of the
     *\@\@     tensor elements.
     *\@\@
     *
     * Generated from protobuf field <code>repeated int32 int_contents = 2;</code>
     */
    private $int_contents;
    /**
     *\@\@
     *\@\@  .. cpp:var:: int64 int64_contents (repeated)
     *\@\@
     *\@\@     Representation for INT64 data types. The size must match what
     *\@\@     is expected by the tensor's shape. The contents must be the
     *\@\@     flattened, one-dimensional, row-major order of the tensor elements.
     *\@\@
     *
     * Generated from protobuf field <code>repeated int64 int64_contents = 3;</code>
     */
    private $int64_contents;
    /**
     *\@\@
     *\@\@  .. cpp:var:: uint32 uint_contents (repeated)
     *\@\@
     *\@\@     Representation for UINT8, UINT16, and UINT32 data types. The size
     *\@\@     must match what is expected by the tensor's shape. The contents
     *\@\@     must be the flattened, one-dimensional, row-major order of the
     *\@\@     tensor elements.
     *\@\@
     *
     * Generated from protobuf field <code>repeated uint32 uint_contents = 4;</code>
     */
    private $uint_contents;
    /**
     *\@\@
     *\@\@  .. cpp:var:: uint64 uint64_contents (repeated)
     *\@\@
     *\@\@     Representation for UINT64 data types. The size must match what
     *\@\@     is expected by the tensor's shape. The contents must be the
     *\@\@     flattened, one-dimensional, row-major order of the tensor elements.
     *\@\@
     *
     * Generated from protobuf field <code>repeated uint64 uint64_contents = 5;</code>
     */
    private $uint64_contents;
    /**
     *\@\@
     *\@\@  .. cpp:var:: float fp32_contents (repeated)
     *\@\@
     *\@\@     Representation for FP32 data type. The size must match what is
     *\@\@     expected by the tensor's shape. The contents must be the flattened,
     *\@\@     one-dimensional, row-major order of the tensor elements.
     *\@\@
     *
     * Generated from protobuf field <code>repeated float fp32_contents = 6;</code>
     */
    private $fp32_contents;
    /**
     *\@\@
     *\@\@  .. cpp:var:: double fp64_contents (repeated)
     *\@\@
     *\@\@     Representation for FP64 data type. The size must match what is
     *\@\@     expected by the tensor's shape. The contents must be the flattened,
     *\@\@     one-dimensional, row-major order of the tensor elements.
     *\@\@
     *
     * Generated from protobuf field <code>repeated double fp64_contents = 7;</code>
     */
    private $fp64_contents;
    /**
     *\@\@
     *\@\@  .. cpp:var:: bytes bytes_contents (repeated)
     *\@\@
     *\@\@     Representation for BYTES data type. The size must match what is
     *\@\@     expected by the tensor's shape. The contents must be the flattened,
     *\@\@     one-dimensional, row-major order of the tensor elements.
     *\@\@
     *
     * Generated from protobuf field <code>repeated bytes bytes_contents = 8;</code>
     */
    private $bytes_contents;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool[] $bool_contents
     *          \@\@
     *          \@\@  .. cpp:var:: bool bool_contents (repeated)
     *          \@\@
     *          \@\@     Representation for BOOL data type. The size must match what is
     *          \@\@     expected by the tensor's shape. The contents must be the flattened,
     *          \@\@     one-dimensional, row-major order of the tensor elements.
     *          \@\@
     *     @type int[] $int_contents
     *          \@\@
     *          \@\@  .. cpp:var:: int32 int_contents (repeated)
     *          \@\@
     *          \@\@     Representation for INT8, INT16, and INT32 data types. The size
     *          \@\@     must match what is expected by the tensor's shape. The contents
     *          \@\@     must be the flattened, one-dimensional, row-major order of the
     *          \@\@     tensor elements.
     *          \@\@
     *     @type int[]|string[] $int64_contents
     *          \@\@
     *          \@\@  .. cpp:var:: int64 int64_contents (repeated)
     *          \@\@
     *          \@\@     Representation for INT64 data types. The size must match what
     *          \@\@     is expected by the tensor's shape. The contents must be the
     *          \@\@     flattened, one-dimensional, row-major order of the tensor elements.
     *          \@\@
     *     @type int[] $uint_contents
     *          \@\@
     *          \@\@  .. cpp:var:: uint32 uint_contents (repeated)
     *          \@\@
     *          \@\@     Representation for UINT8, UINT16, and UINT32 data types. The size
     *          \@\@     must match what is expected by the tensor's shape. The contents
     *          \@\@     must be the flattened, one-dimensional, row-major order of the
     *          \@\@     tensor elements.
     *          \@\@
     *     @type int[]|string[] $uint64_contents
     *          \@\@
     *          \@\@  .. cpp:var:: uint64 uint64_contents (repeated)
     *          \@\@
     *          \@\@     Representation for UINT64 data types. The size must match what
     *          \@\@     is expected by the tensor's shape. The contents must be the
     *          \@\@     flattened, one-dimensional, row-major order of the tensor elements.
     *          \@\@
     *     @type float[] $fp32_contents
     *          \@\@
     *          \@\@  .. cpp:var:: float fp32_contents (repeated)
     *          \@\@
     *          \@\@     Representation for FP32 data type. The size must match what is
     *          \@\@     expected by the tensor's shape. The contents must be the flattened,
     *          \@\@     one-dimensional, row-major order of the tensor elements.
     *          \@\@
     *     @type float[] $fp64_contents
     *          \@\@
     *          \@\@  .. cpp:var:: double fp64_contents (repeated)
     *          \@\@
     *          \@\@     Representation for FP64 data type. The size must match what is
     *          \@\@     expected by the tensor's shape. The contents must be the flattened,
     *          \@\@     one-dimensional, row-major order of the tensor elements.
     *          \@\@
     *     @type string[] $bytes_contents
     *          \@\@
     *          \@\@  .. cpp:var:: bytes bytes_contents (repeated)
     *          \@\@
     *          \@\@     Representation for BYTES data type. The size must match what is
     *          \@\@     expected by the tensor's shape. The contents must be the flattened,
     *          \@\@     one-dimensional, row-major order of the tensor elements.
     *          \@\@
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\GrpcService::initOnce();
        parent::__construct($data);
    }

    /**
     *\@\@
     *\@\@  .. cpp:var:: bool bool_contents (repeated)
     *\@\@
     *\@\@     Representation for BOOL data type. The size must match what is
     *\@\@     expected by the tensor's shape. The contents must be the flattened,
     *\@\@     one-dimensional, row-major order of the tensor elements.
     *\@\@
     *
     * Generated from protobuf field <code>repeated bool bool_contents = 1;</code>
     * @return RepeatedField<bool>
     */
    public function getBoolContents()
    {
        return $this->bool_contents;
    }

    /**
     *\@\@
     *\@\@  .. cpp:var:: bool bool_contents (repeated)
     *\@\@
     *\@\@     Representation for BOOL data type. The size must match what is
     *\@\@     expected by the tensor's shape. The contents must be the flattened,
     *\@\@     one-dimensional, row-major order of the tensor elements.
     *\@\@
     *
     * Generated from protobuf field <code>repeated bool bool_contents = 1;</code>
     * @param bool[] $var
     * @return $this
     */
    public function setBoolContents($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::BOOL);
        $this->bool_contents = $arr;

        return $this;
    }

    /**
     *\@\@
     *\@\@  .. cpp:var:: int32 int_contents (repeated)
     *\@\@
     *\@\@     Representation for INT8, INT16, and INT32 data types. The size
     *\@\@     must match what is expected by the tensor's shape. The contents
     *\@\@     must be the flattened, one-dimensional, row-major order of the
     *\@\@     tensor elements.
     *\@\@
     *
     * Generated from protobuf field <code>repeated int32 int_contents = 2;</code>
     * @return RepeatedField<int>
     */
    public function getIntContents()
    {
        return $this->int_contents;
    }

    /**
     *\@\@
     *\@\@  .. cpp:var:: int32 int_contents (repeated)
     *\@\@
     *\@\@     Representation for INT8, INT16, and INT32 data types. The size
     *\@\@     must match what is expected by the tensor's shape. The contents
     *\@\@     must be the flattened, one-dimensional, row-major order of the
     *\@\@     tensor elements.
     *\@\@
     *
     * Generated from protobuf field <code>repeated int32 int_contents = 2;</code>
     * @param int[] $var
     * @return $this
     */
    public function setIntContents($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT32);
        $this->int_contents = $arr;

        return $this;
    }

    /**
     *\@\@
     *\@\@  .. cpp:var:: int64 int64_contents (repeated)
     *\@\@
     *\@\@     Representation for INT64 data types. The size must match what
     *\@\@     is expected by the tensor's shape. The contents must be the
     *\@\@     flattened, one-dimensional, row-major order of the tensor elements.
     *\@\@
     *
     * Generated from protobuf field <code>repeated int64 int64_contents = 3;</code>
     * @return RepeatedField<int>|RepeatedField<string>
     */
    public function getInt64Contents()
    {
        return $this->int64_contents;
    }

    /**
     *\@\@
     *\@\@  .. cpp:var:: int64 int64_contents (repeated)
     *\@\@
     *\@\@     Representation for INT64 data types. The size must match what
     *\@\@     is expected by the tensor's shape. The contents must be the
     *\@\@     flattened, one-dimensional, row-major order of the tensor elements.
     *\@\@
     *
     * Generated from protobuf field <code>repeated int64 int64_contents = 3;</code>
     * @param int[]|string[] $var
     * @return $this
     */
    public function setInt64Contents($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT64);
        $this->int64_contents = $arr;

        return $this;
    }

    /**
     *\@\@
     *\@\@  .. cpp:var:: uint32 uint_contents (repeated)
     *\@\@
     *\@\@     Representation for UINT8, UINT16, and UINT32 data types. The size
     *\@\@     must match what is expected by the tensor's shape. The contents
     *\@\@     must be the flattened, one-dimensional, row-major order of the
     *\@\@     tensor elements.
     *\@\@
     *
     * Generated from protobuf field <code>repeated uint32 uint_contents = 4;</code>
     * @return RepeatedField<int>
     */
    public function getUintContents()
    {
        return $this->uint_contents;
    }

    /**
     *\@\@
     *\@\@  .. cpp:var:: uint32 uint_contents (repeated)
     *\@\@
     *\@\@     Representation for UINT8, UINT16, and UINT32 data types. The size
     *\@\@     must match what is expected by the tensor's shape. The contents
     *\@\@     must be the flattened, one-dimensional, row-major order of the
     *\@\@     tensor elements.
     *\@\@
     *
     * Generated from protobuf field <code>repeated uint32 uint_contents = 4;</code>
     * @param int[] $var
     * @return $this
     */
    public function setUintContents($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::UINT32);
        $this->uint_contents = $arr;

        return $this;
    }

    /**
     *\@\@
     *\@\@  .. cpp:var:: uint64 uint64_contents (repeated)
     *\@\@
     *\@\@     Representation for UINT64 data types. The size must match what
     *\@\@     is expected by the tensor's shape. The contents must be the
     *\@\@     flattened, one-dimensional, row-major order of the tensor elements.
     *\@\@
     *
     * Generated from protobuf field <code>repeated uint64 uint64_contents = 5;</code>
     * @return RepeatedField<int>|RepeatedField<string>
     */
    public function getUint64Contents()
    {
        return $this->uint64_contents;
    }

    /**
     *\@\@
     *\@\@  .. cpp:var:: uint64 uint64_contents (repeated)
     *\@\@
     *\@\@     Representation for UINT64 data types. The size must match what
     *\@\@     is expected by the tensor's shape. The contents must be the
     *\@\@     flattened, one-dimensional, row-major order of the tensor elements.
     *\@\@
     *
     * Generated from protobuf field <code>repeated uint64 uint64_contents = 5;</code>
     * @param int[]|string[] $var
     * @return $this
     */
    public function setUint64Contents($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::UINT64);
        $this->uint64_contents = $arr;

        return $this;
    }

    /**
     *\@\@
     *\@\@  .. cpp:var:: float fp32_contents (repeated)
     *\@\@
     *\@\@     Representation for FP32 data type. The size must match what is
     *\@\@     expected by the tensor's shape. The contents must be the flattened,
     *\@\@     one-dimensional, row-major order of the tensor elements.
     *\@\@
     *
     * Generated from protobuf field <code>repeated float fp32_contents = 6;</code>
     * @return RepeatedField<float>
     */
    public function getFp32Contents()
    {
        return $this->fp32_contents;
    }

    /**
     *\@\@
     *\@\@  .. cpp:var:: float fp32_contents (repeated)
     *\@\@
     *\@\@     Representation for FP32 data type. The size must match what is
     *\@\@     expected by the tensor's shape. The contents must be the flattened,
     *\@\@     one-dimensional, row-major order of the tensor elements.
     *\@\@
     *
     * Generated from protobuf field <code>repeated float fp32_contents = 6;</code>
     * @param float[] $var
     * @return $this
     */
    public function setFp32Contents($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::FLOAT);
        $this->fp32_contents = $arr;

        return $this;
    }

    /**
     *\@\@
     *\@\@  .. cpp:var:: double fp64_contents (repeated)
     *\@\@
     *\@\@     Representation for FP64 data type. The size must match what is
     *\@\@     expected by the tensor's shape. The contents must be the flattened,
     *\@\@     one-dimensional, row-major order of the tensor elements.
     *\@\@
     *
     * Generated from protobuf field <code>repeated double fp64_contents = 7;</code>
     * @return RepeatedField<float>
     */
    public function getFp64Contents()
    {
        return $this->fp64_contents;
    }

    /**
     *\@\@
     *\@\@  .. cpp:var:: double fp64_contents (repeated)
     *\@\@
     *\@\@     Representation for FP64 data type. The size must match what is
     *\@\@     expected by the tensor's shape. The contents must be the flattened,
     *\@\@     one-dimensional, row-major order of the tensor elements.
     *\@\@
     *
     * Generated from protobuf field <code>repeated double fp64_contents = 7;</code>
     * @param float[] $var
     * @return $this
     */
    public function setFp64Contents($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::DOUBLE);
        $this->fp64_contents = $arr;

        return $this;
    }

    /**
     *\@\@
     *\@\@  .. cpp:var:: bytes bytes_contents (repeated)
     *\@\@
     *\@\@     Representation for BYTES data type. The size must match what is
     *\@\@     expected by the tensor's shape. The contents must be the flattened,
     *\@\@     one-dimensional, row-major order of the tensor elements.
     *\@\@
     *
     * Generated from protobuf field <code>repeated bytes bytes_contents = 8;</code>
     * @return RepeatedField<string>
     */
    public function getBytesContents()
    {
        return $this->bytes_contents;
    }

    /**
     *\@\@
     *\@\@  .. cpp:var:: bytes bytes_contents (repeated)
     *\@\@
     *\@\@     Representation for BYTES data type. The size must match what is
     *\@\@     expected by the tensor's shape. The contents must be the flattened,
     *\@\@     one-dimensional, row-major order of the tensor elements.
     *\@\@
     *
     * Generated from protobuf field <code>repeated bytes bytes_contents = 8;</code>
     * @param string[] $var
     * @return $this
     */
    public function setBytesContents($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::BYTES);
        $this->bytes_contents = $arr;

        return $this;
    }

}

