<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: grpc_service.proto

namespace Inference;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 *\@\@
 *\@\@.. cpp:var:: message ModelConfigRequest
 *\@\@
 *\@\@   Request message for ModelConfig.
 *\@\@
 *
 * Generated from protobuf message <code>inference.ModelConfigRequest</code>
 */
class ModelConfigRequest extends \Google\Protobuf\Internal\Message
{
    /**
     *\@\@
     *\@\@  .. cpp:var:: string name
     *\@\@
     *\@\@     The name of the model.
     *\@\@
     *
     * Generated from protobuf field <code>string name = 1;</code>
     */
    protected $name = '';
    /**
     *\@\@  .. cpp:var:: string version
     *\@\@
     *\@\@     The version of the model. If not given the model version
     *\@\@     is selected automatically based on the version policy.
     *\@\@
     *
     * Generated from protobuf field <code>string version = 2;</code>
     */
    protected $version = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *          \@\@
     *          \@\@  .. cpp:var:: string name
     *          \@\@
     *          \@\@     The name of the model.
     *          \@\@
     *     @type string $version
     *          \@\@  .. cpp:var:: string version
     *          \@\@
     *          \@\@     The version of the model. If not given the model version
     *          \@\@     is selected automatically based on the version policy.
     *          \@\@
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\GrpcService::initOnce();
        parent::__construct($data);
    }

    /**
     *\@\@
     *\@\@  .. cpp:var:: string name
     *\@\@
     *\@\@     The name of the model.
     *\@\@
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     *\@\@
     *\@\@  .. cpp:var:: string name
     *\@\@
     *\@\@     The name of the model.
     *\@\@
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     *\@\@  .. cpp:var:: string version
     *\@\@
     *\@\@     The version of the model. If not given the model version
     *\@\@     is selected automatically based on the version policy.
     *\@\@
     *
     * Generated from protobuf field <code>string version = 2;</code>
     * @return string
     */
    public function getVersion()
    {
        return $this->version;
    }

    /**
     *\@\@  .. cpp:var:: string version
     *\@\@
     *\@\@     The version of the model. If not given the model version
     *\@\@     is selected automatically based on the version policy.
     *\@\@
     *
     * Generated from protobuf field <code>string version = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setVersion($var)
    {
        GPBUtil::checkString($var, True);
        $this->version = $var;

        return $this;
    }

}

