<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: model_config.proto

namespace Inference;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 *\@\@
 *\@\@.. cpp:var:: message ModelWarmup
 *\@\@
 *\@\@   Settings used to construct the request sample for model warmup.
 *\@\@
 *
 * Generated from protobuf message <code>inference.ModelWarmup</code>
 */
class ModelWarmup extends \Google\Protobuf\Internal\Message
{
    /**
     *\@\@  .. cpp:var:: string name
     *\@\@
     *\@\@     The name of the request sample.
     *\@\@
     *
     * Generated from protobuf field <code>string name = 1;</code>
     */
    protected $name = '';
    /**
     *\@\@  .. cpp:var:: uint32 batch_size
     *\@\@
     *\@\@     The batch size of the inference request. This must be >= 1. For
     *\@\@     models that don't support batching, batch_size must be 1. If
     *\@\@     batch_size > 1, the 'inputs' specified below will be duplicated to
     *\@\@     match the batch size requested.
     *\@\@
     *
     * Generated from protobuf field <code>uint32 batch_size = 2;</code>
     */
    protected $batch_size = 0;
    /**
     *\@\@  .. cpp:var:: map<string, Input> inputs
     *\@\@
     *\@\@     The warmup meta data associated with every model input, including
     *\@\@     control tensors.
     *\@\@
     *
     * Generated from protobuf field <code>map<string, .inference.ModelWarmup.Input> inputs = 3;</code>
     */
    private $inputs;
    /**
     *\@\@  .. cpp:var:: uint32 count
     *\@\@
     *\@\@     The number of iterations that this warmup sample will be executed.
     *\@\@     For example, if this field is set to 2, 2 model executions using this
     *\@\@     sample will be scheduled for warmup. Default value is 0 which
     *\@\@     indicates that this sample will be used only once.
     *\@\@     Note that for sequence model, 'count' may not work well
     *\@\@     because the model often expect a valid sequence of requests which
     *\@\@     should be represented by a series of warmup samples. 'count > 1'
     *\@\@     essentially "resends" one of the sample, which may invalidate the
     *\@\@     sequence and result in unexpected warmup failure.
     *\@\@
     *
     * Generated from protobuf field <code>uint32 count = 4;</code>
     */
    protected $count = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *          \@\@  .. cpp:var:: string name
     *          \@\@
     *          \@\@     The name of the request sample.
     *          \@\@
     *     @type int $batch_size
     *          \@\@  .. cpp:var:: uint32 batch_size
     *          \@\@
     *          \@\@     The batch size of the inference request. This must be >= 1. For
     *          \@\@     models that don't support batching, batch_size must be 1. If
     *          \@\@     batch_size > 1, the 'inputs' specified below will be duplicated to
     *          \@\@     match the batch size requested.
     *          \@\@
     *     @type array|\Google\Protobuf\Internal\MapField $inputs
     *          \@\@  .. cpp:var:: map<string, Input> inputs
     *          \@\@
     *          \@\@     The warmup meta data associated with every model input, including
     *          \@\@     control tensors.
     *          \@\@
     *     @type int $count
     *          \@\@  .. cpp:var:: uint32 count
     *          \@\@
     *          \@\@     The number of iterations that this warmup sample will be executed.
     *          \@\@     For example, if this field is set to 2, 2 model executions using this
     *          \@\@     sample will be scheduled for warmup. Default value is 0 which
     *          \@\@     indicates that this sample will be used only once.
     *          \@\@     Note that for sequence model, 'count' may not work well
     *          \@\@     because the model often expect a valid sequence of requests which
     *          \@\@     should be represented by a series of warmup samples. 'count > 1'
     *          \@\@     essentially "resends" one of the sample, which may invalidate the
     *          \@\@     sequence and result in unexpected warmup failure.
     *          \@\@
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\ModelConfig::initOnce();
        parent::__construct($data);
    }

    /**
     *\@\@  .. cpp:var:: string name
     *\@\@
     *\@\@     The name of the request sample.
     *\@\@
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     *\@\@  .. cpp:var:: string name
     *\@\@
     *\@\@     The name of the request sample.
     *\@\@
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     *\@\@  .. cpp:var:: uint32 batch_size
     *\@\@
     *\@\@     The batch size of the inference request. This must be >= 1. For
     *\@\@     models that don't support batching, batch_size must be 1. If
     *\@\@     batch_size > 1, the 'inputs' specified below will be duplicated to
     *\@\@     match the batch size requested.
     *\@\@
     *
     * Generated from protobuf field <code>uint32 batch_size = 2;</code>
     * @return int
     */
    public function getBatchSize()
    {
        return $this->batch_size;
    }

    /**
     *\@\@  .. cpp:var:: uint32 batch_size
     *\@\@
     *\@\@     The batch size of the inference request. This must be >= 1. For
     *\@\@     models that don't support batching, batch_size must be 1. If
     *\@\@     batch_size > 1, the 'inputs' specified below will be duplicated to
     *\@\@     match the batch size requested.
     *\@\@
     *
     * Generated from protobuf field <code>uint32 batch_size = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setBatchSize($var)
    {
        GPBUtil::checkUint32($var);
        $this->batch_size = $var;

        return $this;
    }

    /**
     *\@\@  .. cpp:var:: map<string, Input> inputs
     *\@\@
     *\@\@     The warmup meta data associated with every model input, including
     *\@\@     control tensors.
     *\@\@
     *
     * Generated from protobuf field <code>map<string, .inference.ModelWarmup.Input> inputs = 3;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getInputs()
    {
        return $this->inputs;
    }

    /**
     *\@\@  .. cpp:var:: map<string, Input> inputs
     *\@\@
     *\@\@     The warmup meta data associated with every model input, including
     *\@\@     control tensors.
     *\@\@
     *
     * Generated from protobuf field <code>map<string, .inference.ModelWarmup.Input> inputs = 3;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setInputs($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::MESSAGE, \Inference\ModelWarmup\Input::class);
        $this->inputs = $arr;

        return $this;
    }

    /**
     *\@\@  .. cpp:var:: uint32 count
     *\@\@
     *\@\@     The number of iterations that this warmup sample will be executed.
     *\@\@     For example, if this field is set to 2, 2 model executions using this
     *\@\@     sample will be scheduled for warmup. Default value is 0 which
     *\@\@     indicates that this sample will be used only once.
     *\@\@     Note that for sequence model, 'count' may not work well
     *\@\@     because the model often expect a valid sequence of requests which
     *\@\@     should be represented by a series of warmup samples. 'count > 1'
     *\@\@     essentially "resends" one of the sample, which may invalidate the
     *\@\@     sequence and result in unexpected warmup failure.
     *\@\@
     *
     * Generated from protobuf field <code>uint32 count = 4;</code>
     * @return int
     */
    public function getCount()
    {
        return $this->count;
    }

    /**
     *\@\@  .. cpp:var:: uint32 count
     *\@\@
     *\@\@     The number of iterations that this warmup sample will be executed.
     *\@\@     For example, if this field is set to 2, 2 model executions using this
     *\@\@     sample will be scheduled for warmup. Default value is 0 which
     *\@\@     indicates that this sample will be used only once.
     *\@\@     Note that for sequence model, 'count' may not work well
     *\@\@     because the model often expect a valid sequence of requests which
     *\@\@     should be represented by a series of warmup samples. 'count > 1'
     *\@\@     essentially "resends" one of the sample, which may invalidate the
     *\@\@     sequence and result in unexpected warmup failure.
     *\@\@
     *
     * Generated from protobuf field <code>uint32 count = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setCount($var)
    {
        GPBUtil::checkUint32($var);
        $this->count = $var;

        return $this;
    }

}

