<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: model_config.proto

namespace Inference;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 *\@\@
 *\@\@.. cpp:var:: message ModelParameter
 *\@\@
 *\@\@   A model parameter.
 *\@\@
 *
 * Generated from protobuf message <code>inference.ModelParameter</code>
 */
class ModelParameter extends \Google\Protobuf\Internal\Message
{
    /**
     *\@\@  .. cpp:var:: string string_value
     *\@\@
     *\@\@     The string value of the parameter.
     *\@\@
     *
     * Generated from protobuf field <code>string string_value = 1;</code>
     */
    protected $string_value = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $string_value
     *          \@\@  .. cpp:var:: string string_value
     *          \@\@
     *          \@\@     The string value of the parameter.
     *          \@\@
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\ModelConfig::initOnce();
        parent::__construct($data);
    }

    /**
     *\@\@  .. cpp:var:: string string_value
     *\@\@
     *\@\@     The string value of the parameter.
     *\@\@
     *
     * Generated from protobuf field <code>string string_value = 1;</code>
     * @return string
     */
    public function getStringValue()
    {
        return $this->string_value;
    }

    /**
     *\@\@  .. cpp:var:: string string_value
     *\@\@
     *\@\@     The string value of the parameter.
     *\@\@
     *
     * Generated from protobuf field <code>string string_value = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setStringValue($var)
    {
        GPBUtil::checkString($var, True);
        $this->string_value = $var;

        return $this;
    }

}

