<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: grpc_service.proto

namespace Inference;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 *\@\@
 *\@\@.. cpp:var:: message ModelRepositoryParameter
 *\@\@
 *\@\@   An model repository parameter value.
 *\@\@
 *
 * Generated from protobuf message <code>inference.ModelRepositoryParameter</code>
 */
class ModelRepositoryParameter extends \Google\Protobuf\Internal\Message
{
    protected $parameter_choice;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $bool_param
     *          \@\@    .. cpp:var:: bool bool_param
     *          \@\@
     *          \@\@       A boolean parameter value.
     *          \@\@
     *     @type int|string $int64_param
     *          \@\@    .. cpp:var:: int64 int64_param
     *          \@\@
     *          \@\@       An int64 parameter value.
     *          \@\@
     *     @type string $string_param
     *          \@\@    .. cpp:var:: string string_param
     *          \@\@
     *          \@\@       A string parameter value.
     *          \@\@
     *     @type string $bytes_param
     *          \@\@    .. cpp:var:: bytes bytes_param
     *          \@\@
     *          \@\@       A bytes parameter value.
     *          \@\@
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\GrpcService::initOnce();
        parent::__construct($data);
    }

    /**
     *\@\@    .. cpp:var:: bool bool_param
     *\@\@
     *\@\@       A boolean parameter value.
     *\@\@
     *
     * Generated from protobuf field <code>bool bool_param = 1;</code>
     * @return bool
     */
    public function getBoolParam()
    {
        return $this->readOneof(1);
    }

    public function hasBoolParam()
    {
        return $this->hasOneof(1);
    }

    /**
     *\@\@    .. cpp:var:: bool bool_param
     *\@\@
     *\@\@       A boolean parameter value.
     *\@\@
     *
     * Generated from protobuf field <code>bool bool_param = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setBoolParam($var)
    {
        GPBUtil::checkBool($var);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     *\@\@    .. cpp:var:: int64 int64_param
     *\@\@
     *\@\@       An int64 parameter value.
     *\@\@
     *
     * Generated from protobuf field <code>int64 int64_param = 2;</code>
     * @return int|string
     */
    public function getInt64Param()
    {
        return $this->readOneof(2);
    }

    public function hasInt64Param()
    {
        return $this->hasOneof(2);
    }

    /**
     *\@\@    .. cpp:var:: int64 int64_param
     *\@\@
     *\@\@       An int64 parameter value.
     *\@\@
     *
     * Generated from protobuf field <code>int64 int64_param = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setInt64Param($var)
    {
        GPBUtil::checkInt64($var);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     *\@\@    .. cpp:var:: string string_param
     *\@\@
     *\@\@       A string parameter value.
     *\@\@
     *
     * Generated from protobuf field <code>string string_param = 3;</code>
     * @return string
     */
    public function getStringParam()
    {
        return $this->readOneof(3);
    }

    public function hasStringParam()
    {
        return $this->hasOneof(3);
    }

    /**
     *\@\@    .. cpp:var:: string string_param
     *\@\@
     *\@\@       A string parameter value.
     *\@\@
     *
     * Generated from protobuf field <code>string string_param = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setStringParam($var)
    {
        GPBUtil::checkString($var, True);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     *\@\@    .. cpp:var:: bytes bytes_param
     *\@\@
     *\@\@       A bytes parameter value.
     *\@\@
     *
     * Generated from protobuf field <code>bytes bytes_param = 4;</code>
     * @return string
     */
    public function getBytesParam()
    {
        return $this->readOneof(4);
    }

    public function hasBytesParam()
    {
        return $this->hasOneof(4);
    }

    /**
     *\@\@    .. cpp:var:: bytes bytes_param
     *\@\@
     *\@\@       A bytes parameter value.
     *\@\@
     *
     * Generated from protobuf field <code>bytes bytes_param = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setBytesParam($var)
    {
        GPBUtil::checkString($var, False);
        $this->writeOneof(4, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getParameterChoice()
    {
        return $this->whichOneof("parameter_choice");
    }

}

