<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: grpc_service.proto

namespace Inference;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 *\@\@
 *\@\@.. cpp:var:: message RepositoryIndexRequest
 *\@\@
 *\@\@   Request message for RepositoryIndex.
 *\@\@
 *
 * Generated from protobuf message <code>inference.RepositoryIndexRequest</code>
 */
class RepositoryIndexRequest extends \Google\Protobuf\Internal\Message
{
    /**
     *\@\@  .. cpp:var:: string repository_name
     *\@\@
     *\@\@     The name of the repository. If empty the index is returned
     *\@\@     for all repositories.
     *\@\@
     *
     * Generated from protobuf field <code>string repository_name = 1;</code>
     */
    protected $repository_name = '';
    /**
     *\@\@  .. cpp:var:: bool ready
     *\@\@
     *\@\@     If true returned only models currently ready for inferencing.
     *\@\@
     *
     * Generated from protobuf field <code>bool ready = 2;</code>
     */
    protected $ready = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $repository_name
     *          \@\@  .. cpp:var:: string repository_name
     *          \@\@
     *          \@\@     The name of the repository. If empty the index is returned
     *          \@\@     for all repositories.
     *          \@\@
     *     @type bool $ready
     *          \@\@  .. cpp:var:: bool ready
     *          \@\@
     *          \@\@     If true returned only models currently ready for inferencing.
     *          \@\@
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\GrpcService::initOnce();
        parent::__construct($data);
    }

    /**
     *\@\@  .. cpp:var:: string repository_name
     *\@\@
     *\@\@     The name of the repository. If empty the index is returned
     *\@\@     for all repositories.
     *\@\@
     *
     * Generated from protobuf field <code>string repository_name = 1;</code>
     * @return string
     */
    public function getRepositoryName()
    {
        return $this->repository_name;
    }

    /**
     *\@\@  .. cpp:var:: string repository_name
     *\@\@
     *\@\@     The name of the repository. If empty the index is returned
     *\@\@     for all repositories.
     *\@\@
     *
     * Generated from protobuf field <code>string repository_name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setRepositoryName($var)
    {
        GPBUtil::checkString($var, True);
        $this->repository_name = $var;

        return $this;
    }

    /**
     *\@\@  .. cpp:var:: bool ready
     *\@\@
     *\@\@     If true returned only models currently ready for inferencing.
     *\@\@
     *
     * Generated from protobuf field <code>bool ready = 2;</code>
     * @return bool
     */
    public function getReady()
    {
        return $this->ready;
    }

    /**
     *\@\@  .. cpp:var:: bool ready
     *\@\@
     *\@\@     If true returned only models currently ready for inferencing.
     *\@\@
     *
     * Generated from protobuf field <code>bool ready = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setReady($var)
    {
        GPBUtil::checkBool($var);
        $this->ready = $var;

        return $this;
    }

}

