<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: grpc_service.proto

namespace Inference;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 *\@\@
 *\@\@.. cpp:var:: message ServerLiveResponse
 *\@\@
 *\@\@   Response message for ServerLive.
 *\@\@
 *
 * Generated from protobuf message <code>inference.ServerLiveResponse</code>
 */
class ServerLiveResponse extends \Google\Protobuf\Internal\Message
{
    /**
     *\@\@
     *\@\@  .. cpp:var:: bool live
     *\@\@
     *\@\@     True if the inference server is live, false it not live.
     *\@\@
     *
     * Generated from protobuf field <code>bool live = 1;</code>
     */
    protected $live = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $live
     *          \@\@
     *          \@\@  .. cpp:var:: bool live
     *          \@\@
     *          \@\@     True if the inference server is live, false it not live.
     *          \@\@
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\GrpcService::initOnce();
        parent::__construct($data);
    }

    /**
     *\@\@
     *\@\@  .. cpp:var:: bool live
     *\@\@
     *\@\@     True if the inference server is live, false it not live.
     *\@\@
     *
     * Generated from protobuf field <code>bool live = 1;</code>
     * @return bool
     */
    public function getLive()
    {
        return $this->live;
    }

    /**
     *\@\@
     *\@\@  .. cpp:var:: bool live
     *\@\@
     *\@\@     True if the inference server is live, false it not live.
     *\@\@
     *
     * Generated from protobuf field <code>bool live = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setLive($var)
    {
        GPBUtil::checkBool($var);
        $this->live = $var;

        return $this;
    }

}

