<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: model_config.proto

namespace Inference;

if (false) {
    /**
     * This class is deprecated. Use Inference\BatchInput\Kind instead.
     * @deprecated
     */
    class BatchInput_Kind {}
}
class_exists(BatchInput\Kind::class);
@trigger_error('Inference\BatchInput_Kind is deprecated and will be removed in the next major release. Use Inference\BatchInput\Kind instead', E_USER_DEPRECATED);

