<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: model_config.proto

namespace Inference;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *&#64;&#64;.. cpp:var:: message BatchOutput
 *&#64;&#64;
 *&#64;&#64;   A batch output is an output produced by the model that must be handled
 *&#64;&#64;   differently by the backend based on all the requests in a batch.
 *&#64;&#64;
 *
 * Generated from protobuf message <code>inference.BatchOutput</code>
 */
class BatchOutput extends \Google\Protobuf\Internal\Message
{
    /**
     *&#64;&#64;  .. cpp:var:: string target_name (repeated)
     *&#64;&#64;
     *&#64;&#64;     The name of the outputs to be produced by this batch output
     *&#64;&#64;     specification.
     *&#64;&#64;
     *
     * Generated from protobuf field <code>repeated string target_name = 1;</code>
     */
    private $target_name;
    /**
     *&#64;&#64;  .. cpp:var:: Kind kind
     *&#64;&#64;
     *&#64;&#64;     The kind of this batch output.
     *&#64;&#64;
     *
     * Generated from protobuf field <code>.inference.BatchOutput.Kind kind = 2;</code>
     */
    protected $kind = 0;
    /**
     *&#64;&#64;  .. cpp:var:: string source_input (repeated)
     *&#64;&#64;
     *&#64;&#64;     The backend derives each batch output from one or more inputs.
     *&#64;&#64;     'source_input' gives the names of those inputs.
     *&#64;&#64;
     *
     * Generated from protobuf field <code>repeated string source_input = 3;</code>
     */
    private $source_input;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $target_name
     *          &#64;&#64;  .. cpp:var:: string target_name (repeated)
     *          &#64;&#64;
     *          &#64;&#64;     The name of the outputs to be produced by this batch output
     *          &#64;&#64;     specification.
     *          &#64;&#64;
     *     @type int $kind
     *          &#64;&#64;  .. cpp:var:: Kind kind
     *          &#64;&#64;
     *          &#64;&#64;     The kind of this batch output.
     *          &#64;&#64;
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $source_input
     *          &#64;&#64;  .. cpp:var:: string source_input (repeated)
     *          &#64;&#64;
     *          &#64;&#64;     The backend derives each batch output from one or more inputs.
     *          &#64;&#64;     'source_input' gives the names of those inputs.
     *          &#64;&#64;
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\ModelConfig::initOnce();
        parent::__construct($data);
    }

    /**
     *&#64;&#64;  .. cpp:var:: string target_name (repeated)
     *&#64;&#64;
     *&#64;&#64;     The name of the outputs to be produced by this batch output
     *&#64;&#64;     specification.
     *&#64;&#64;
     *
     * Generated from protobuf field <code>repeated string target_name = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTargetName()
    {
        return $this->target_name;
    }

    /**
     *&#64;&#64;  .. cpp:var:: string target_name (repeated)
     *&#64;&#64;
     *&#64;&#64;     The name of the outputs to be produced by this batch output
     *&#64;&#64;     specification.
     *&#64;&#64;
     *
     * Generated from protobuf field <code>repeated string target_name = 1;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTargetName($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->target_name = $arr;

        return $this;
    }

    /**
     *&#64;&#64;  .. cpp:var:: Kind kind
     *&#64;&#64;
     *&#64;&#64;     The kind of this batch output.
     *&#64;&#64;
     *
     * Generated from protobuf field <code>.inference.BatchOutput.Kind kind = 2;</code>
     * @return int
     */
    public function getKind()
    {
        return $this->kind;
    }

    /**
     *&#64;&#64;  .. cpp:var:: Kind kind
     *&#64;&#64;
     *&#64;&#64;     The kind of this batch output.
     *&#64;&#64;
     *
     * Generated from protobuf field <code>.inference.BatchOutput.Kind kind = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setKind($var)
    {
        GPBUtil::checkEnum($var, \Inference\BatchOutput_Kind::class);
        $this->kind = $var;

        return $this;
    }

    /**
     *&#64;&#64;  .. cpp:var:: string source_input (repeated)
     *&#64;&#64;
     *&#64;&#64;     The backend derives each batch output from one or more inputs.
     *&#64;&#64;     'source_input' gives the names of those inputs.
     *&#64;&#64;
     *
     * Generated from protobuf field <code>repeated string source_input = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSourceInput()
    {
        return $this->source_input;
    }

    /**
     *&#64;&#64;  .. cpp:var:: string source_input (repeated)
     *&#64;&#64;
     *&#64;&#64;     The backend derives each batch output from one or more inputs.
     *&#64;&#64;     'source_input' gives the names of those inputs.
     *&#64;&#64;
     *
     * Generated from protobuf field <code>repeated string source_input = 3;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSourceInput($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->source_input = $arr;

        return $this;
    }

}

