<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc_service.proto

namespace Inference;

if (false) {
    /**
     * This class is deprecated. Use Inference\LogSettingsResponse\SettingValue instead.
     * @deprecated
     */
    class LogSettingsResponse_SettingValue {}
}
class_exists(LogSettingsResponse\SettingValue::class);
@trigger_error('Inference\LogSettingsResponse_SettingValue is deprecated and will be removed in the next major release. Use Inference\LogSettingsResponse\SettingValue instead', E_USER_DEPRECATED);

