<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc_service.proto

namespace Inference;

if (false) {
    /**
     * This class is deprecated. Use Inference\LogSettingsRequest\SettingValue instead.
     * @deprecated
     */
    class LogSettingsRequest_SettingValue {}
}
class_exists(LogSettingsRequest\SettingValue::class);
@trigger_error('Inference\LogSettingsRequest_SettingValue is deprecated and will be removed in the next major release. Use Inference\LogSettingsRequest\SettingValue instead', E_USER_DEPRECATED);

