<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: model_config.proto

namespace Inference;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *&#64;&#64;
 *&#64;&#64;.. cpp:var:: message ModelEnsembling
 *&#64;&#64;
 *&#64;&#64;   Model ensembling configuration. These settings specify the models that
 *&#64;&#64;   compose the ensemble and how data flows between the models.
 *&#64;&#64;
 *
 * Generated from protobuf message <code>inference.ModelEnsembling</code>
 */
class ModelEnsembling extends \Google\Protobuf\Internal\Message
{
    /**
     *&#64;&#64;  .. cpp:var:: Step step (repeated)
     *&#64;&#64;
     *&#64;&#64;     The models and the input / output mappings used within the ensemble.
     *&#64;&#64;
     *
     * Generated from protobuf field <code>repeated .inference.ModelEnsembling.Step step = 1;</code>
     */
    private $step;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Inference\ModelEnsembling\Step[]|\Google\Protobuf\Internal\RepeatedField $step
     *          &#64;&#64;  .. cpp:var:: Step step (repeated)
     *          &#64;&#64;
     *          &#64;&#64;     The models and the input / output mappings used within the ensemble.
     *          &#64;&#64;
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\ModelConfig::initOnce();
        parent::__construct($data);
    }

    /**
     *&#64;&#64;  .. cpp:var:: Step step (repeated)
     *&#64;&#64;
     *&#64;&#64;     The models and the input / output mappings used within the ensemble.
     *&#64;&#64;
     *
     * Generated from protobuf field <code>repeated .inference.ModelEnsembling.Step step = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getStep()
    {
        return $this->step;
    }

    /**
     *&#64;&#64;  .. cpp:var:: Step step (repeated)
     *&#64;&#64;
     *&#64;&#64;     The models and the input / output mappings used within the ensemble.
     *&#64;&#64;
     *
     * Generated from protobuf field <code>repeated .inference.ModelEnsembling.Step step = 1;</code>
     * @param \Inference\ModelEnsembling\Step[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setStep($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Inference\ModelEnsembling\Step::class);
        $this->step = $arr;

        return $this;
    }

}

