<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: model_config.proto

namespace Inference;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *&#64;&#64;
 *&#64;&#64;.. cpp:var:: message ModelOutput
 *&#64;&#64;
 *&#64;&#64;   An output produced by the model.
 *&#64;&#64;
 *
 * Generated from protobuf message <code>inference.ModelOutput</code>
 */
class ModelOutput extends \Google\Protobuf\Internal\Message
{
    /**
     *&#64;&#64;  .. cpp:var:: string name
     *&#64;&#64;
     *&#64;&#64;     The name of the output.
     *&#64;&#64;
     *
     * Generated from protobuf field <code>string name = 1;</code>
     */
    protected $name = '';
    /**
     *&#64;&#64;  .. cpp:var:: DataType data_type
     *&#64;&#64;
     *&#64;&#64;     The data-type of the output.
     *&#64;&#64;
     *
     * Generated from protobuf field <code>.inference.DataType data_type = 2;</code>
     */
    protected $data_type = 0;
    /**
     *&#64;&#64;  .. cpp:var:: int64 dims (repeated)
     *&#64;&#64;
     *&#64;&#64;     The dimensions/shape of the output tensor.
     *&#64;&#64;
     *
     * Generated from protobuf field <code>repeated int64 dims = 3;</code>
     */
    private $dims;
    /**
     *&#64;&#64;  .. cpp:var:: ModelTensorReshape reshape
     *&#64;&#64;
     *&#64;&#64;     The shape produced for this output by the backend. The output will
     *&#64;&#64;     be reshaped from this to the shape specified in 'dims' before being
     *&#64;&#64;     returned in the inference response. The reshape must have the same
     *&#64;&#64;     number of elements as the output shape specified by 'dims'. Optional.
     *&#64;&#64;
     *
     * Generated from protobuf field <code>.inference.ModelTensorReshape reshape = 5;</code>
     */
    protected $reshape = null;
    /**
     *&#64;&#64;  .. cpp:var:: string label_filename
     *&#64;&#64;
     *&#64;&#64;     The label file associated with this output. Should be specified only
     *&#64;&#64;     for outputs that represent classifications. Optional.
     *&#64;&#64;
     *
     * Generated from protobuf field <code>string label_filename = 4;</code>
     */
    protected $label_filename = '';
    /**
     *&#64;&#64;  .. cpp:var:: bool is_shape_tensor
     *&#64;&#64;
     *&#64;&#64;     Whether or not the output is a shape tensor to the model. This field
     *&#64;&#64;     is currently supported only for the TensorRT model. An error will be
     *&#64;&#64;     generated if this specification does not comply with underlying
     *&#64;&#64;     model.
     *&#64;&#64;
     *
     * Generated from protobuf field <code>bool is_shape_tensor = 6;</code>
     */
    protected $is_shape_tensor = false;
    /**
     *&#64;&#64;  .. cpp:var:: bool is_non_linear_format_io
     *&#64;&#64;
     *&#64;&#64;     Indicates whether the output tensor uses a non-linear IO format. This
     *&#64;&#64;     field is currently supported only for TensorRT models. An error will
     *&#64;&#64;     be generated if this specification does not comply with the
     *&#64;&#64;     underlying model.
     *&#64;&#64;
     *
     * Generated from protobuf field <code>bool is_non_linear_format_io = 7;</code>
     */
    protected $is_non_linear_format_io = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *          &#64;&#64;  .. cpp:var:: string name
     *          &#64;&#64;
     *          &#64;&#64;     The name of the output.
     *          &#64;&#64;
     *     @type int $data_type
     *          &#64;&#64;  .. cpp:var:: DataType data_type
     *          &#64;&#64;
     *          &#64;&#64;     The data-type of the output.
     *          &#64;&#64;
     *     @type int[]|string[]|\Google\Protobuf\Internal\RepeatedField $dims
     *          &#64;&#64;  .. cpp:var:: int64 dims (repeated)
     *          &#64;&#64;
     *          &#64;&#64;     The dimensions/shape of the output tensor.
     *          &#64;&#64;
     *     @type \Inference\ModelTensorReshape $reshape
     *          &#64;&#64;  .. cpp:var:: ModelTensorReshape reshape
     *          &#64;&#64;
     *          &#64;&#64;     The shape produced for this output by the backend. The output will
     *          &#64;&#64;     be reshaped from this to the shape specified in 'dims' before being
     *          &#64;&#64;     returned in the inference response. The reshape must have the same
     *          &#64;&#64;     number of elements as the output shape specified by 'dims'. Optional.
     *          &#64;&#64;
     *     @type string $label_filename
     *          &#64;&#64;  .. cpp:var:: string label_filename
     *          &#64;&#64;
     *          &#64;&#64;     The label file associated with this output. Should be specified only
     *          &#64;&#64;     for outputs that represent classifications. Optional.
     *          &#64;&#64;
     *     @type bool $is_shape_tensor
     *          &#64;&#64;  .. cpp:var:: bool is_shape_tensor
     *          &#64;&#64;
     *          &#64;&#64;     Whether or not the output is a shape tensor to the model. This field
     *          &#64;&#64;     is currently supported only for the TensorRT model. An error will be
     *          &#64;&#64;     generated if this specification does not comply with underlying
     *          &#64;&#64;     model.
     *          &#64;&#64;
     *     @type bool $is_non_linear_format_io
     *          &#64;&#64;  .. cpp:var:: bool is_non_linear_format_io
     *          &#64;&#64;
     *          &#64;&#64;     Indicates whether the output tensor uses a non-linear IO format. This
     *          &#64;&#64;     field is currently supported only for TensorRT models. An error will
     *          &#64;&#64;     be generated if this specification does not comply with the
     *          &#64;&#64;     underlying model.
     *          &#64;&#64;
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\ModelConfig::initOnce();
        parent::__construct($data);
    }

    /**
     *&#64;&#64;  .. cpp:var:: string name
     *&#64;&#64;
     *&#64;&#64;     The name of the output.
     *&#64;&#64;
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     *&#64;&#64;  .. cpp:var:: string name
     *&#64;&#64;
     *&#64;&#64;     The name of the output.
     *&#64;&#64;
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     *&#64;&#64;  .. cpp:var:: DataType data_type
     *&#64;&#64;
     *&#64;&#64;     The data-type of the output.
     *&#64;&#64;
     *
     * Generated from protobuf field <code>.inference.DataType data_type = 2;</code>
     * @return int
     */
    public function getDataType()
    {
        return $this->data_type;
    }

    /**
     *&#64;&#64;  .. cpp:var:: DataType data_type
     *&#64;&#64;
     *&#64;&#64;     The data-type of the output.
     *&#64;&#64;
     *
     * Generated from protobuf field <code>.inference.DataType data_type = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setDataType($var)
    {
        GPBUtil::checkEnum($var, \Inference\DataType::class);
        $this->data_type = $var;

        return $this;
    }

    /**
     *&#64;&#64;  .. cpp:var:: int64 dims (repeated)
     *&#64;&#64;
     *&#64;&#64;     The dimensions/shape of the output tensor.
     *&#64;&#64;
     *
     * Generated from protobuf field <code>repeated int64 dims = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDims()
    {
        return $this->dims;
    }

    /**
     *&#64;&#64;  .. cpp:var:: int64 dims (repeated)
     *&#64;&#64;
     *&#64;&#64;     The dimensions/shape of the output tensor.
     *&#64;&#64;
     *
     * Generated from protobuf field <code>repeated int64 dims = 3;</code>
     * @param int[]|string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDims($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT64);
        $this->dims = $arr;

        return $this;
    }

    /**
     *&#64;&#64;  .. cpp:var:: ModelTensorReshape reshape
     *&#64;&#64;
     *&#64;&#64;     The shape produced for this output by the backend. The output will
     *&#64;&#64;     be reshaped from this to the shape specified in 'dims' before being
     *&#64;&#64;     returned in the inference response. The reshape must have the same
     *&#64;&#64;     number of elements as the output shape specified by 'dims'. Optional.
     *&#64;&#64;
     *
     * Generated from protobuf field <code>.inference.ModelTensorReshape reshape = 5;</code>
     * @return \Inference\ModelTensorReshape
     */
    public function getReshape()
    {
        return $this->reshape;
    }

    /**
     *&#64;&#64;  .. cpp:var:: ModelTensorReshape reshape
     *&#64;&#64;
     *&#64;&#64;     The shape produced for this output by the backend. The output will
     *&#64;&#64;     be reshaped from this to the shape specified in 'dims' before being
     *&#64;&#64;     returned in the inference response. The reshape must have the same
     *&#64;&#64;     number of elements as the output shape specified by 'dims'. Optional.
     *&#64;&#64;
     *
     * Generated from protobuf field <code>.inference.ModelTensorReshape reshape = 5;</code>
     * @param \Inference\ModelTensorReshape $var
     * @return $this
     */
    public function setReshape($var)
    {
        GPBUtil::checkMessage($var, \Inference\ModelTensorReshape::class);
        $this->reshape = $var;

        return $this;
    }

    /**
     *&#64;&#64;  .. cpp:var:: string label_filename
     *&#64;&#64;
     *&#64;&#64;     The label file associated with this output. Should be specified only
     *&#64;&#64;     for outputs that represent classifications. Optional.
     *&#64;&#64;
     *
     * Generated from protobuf field <code>string label_filename = 4;</code>
     * @return string
     */
    public function getLabelFilename()
    {
        return $this->label_filename;
    }

    /**
     *&#64;&#64;  .. cpp:var:: string label_filename
     *&#64;&#64;
     *&#64;&#64;     The label file associated with this output. Should be specified only
     *&#64;&#64;     for outputs that represent classifications. Optional.
     *&#64;&#64;
     *
     * Generated from protobuf field <code>string label_filename = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setLabelFilename($var)
    {
        GPBUtil::checkString($var, True);
        $this->label_filename = $var;

        return $this;
    }

    /**
     *&#64;&#64;  .. cpp:var:: bool is_shape_tensor
     *&#64;&#64;
     *&#64;&#64;     Whether or not the output is a shape tensor to the model. This field
     *&#64;&#64;     is currently supported only for the TensorRT model. An error will be
     *&#64;&#64;     generated if this specification does not comply with underlying
     *&#64;&#64;     model.
     *&#64;&#64;
     *
     * Generated from protobuf field <code>bool is_shape_tensor = 6;</code>
     * @return bool
     */
    public function getIsShapeTensor()
    {
        return $this->is_shape_tensor;
    }

    /**
     *&#64;&#64;  .. cpp:var:: bool is_shape_tensor
     *&#64;&#64;
     *&#64;&#64;     Whether or not the output is a shape tensor to the model. This field
     *&#64;&#64;     is currently supported only for the TensorRT model. An error will be
     *&#64;&#64;     generated if this specification does not comply with underlying
     *&#64;&#64;     model.
     *&#64;&#64;
     *
     * Generated from protobuf field <code>bool is_shape_tensor = 6;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsShapeTensor($var)
    {
        GPBUtil::checkBool($var);
        $this->is_shape_tensor = $var;

        return $this;
    }

    /**
     *&#64;&#64;  .. cpp:var:: bool is_non_linear_format_io
     *&#64;&#64;
     *&#64;&#64;     Indicates whether the output tensor uses a non-linear IO format. This
     *&#64;&#64;     field is currently supported only for TensorRT models. An error will
     *&#64;&#64;     be generated if this specification does not comply with the
     *&#64;&#64;     underlying model.
     *&#64;&#64;
     *
     * Generated from protobuf field <code>bool is_non_linear_format_io = 7;</code>
     * @return bool
     */
    public function getIsNonLinearFormatIo()
    {
        return $this->is_non_linear_format_io;
    }

    /**
     *&#64;&#64;  .. cpp:var:: bool is_non_linear_format_io
     *&#64;&#64;
     *&#64;&#64;     Indicates whether the output tensor uses a non-linear IO format. This
     *&#64;&#64;     field is currently supported only for TensorRT models. An error will
     *&#64;&#64;     be generated if this specification does not comply with the
     *&#64;&#64;     underlying model.
     *&#64;&#64;
     *
     * Generated from protobuf field <code>bool is_non_linear_format_io = 7;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsNonLinearFormatIo($var)
    {
        GPBUtil::checkBool($var);
        $this->is_non_linear_format_io = $var;

        return $this;
    }

}

