<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: model_config.proto

namespace Inference;

if (false) {
    /**
     * This class is deprecated. Use Inference\ModelOptimizationPolicy\PinnedMemoryBuffer instead.
     * @deprecated
     */
    class ModelOptimizationPolicy_PinnedMemoryBuffer {}
}
class_exists(ModelOptimizationPolicy\PinnedMemoryBuffer::class);
@trigger_error('Inference\ModelOptimizationPolicy_PinnedMemoryBuffer is deprecated and will be removed in the next major release. Use Inference\ModelOptimizationPolicy\PinnedMemoryBuffer instead', E_USER_DEPRECATED);

