<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc_service.proto

namespace Inference;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *&#64;&#64;
 *&#64;&#64;.. cpp:var:: message ModelStatisticsRequest
 *&#64;&#64;
 *&#64;&#64;   Request message for ModelStatistics.
 *&#64;&#64;
 *
 * Generated from protobuf message <code>inference.ModelStatisticsRequest</code>
 */
class ModelStatisticsRequest extends \Google\Protobuf\Internal\Message
{
    /**
     *&#64;&#64;  .. cpp:var:: string name
     *&#64;&#64;
     *&#64;&#64;     The name of the model. If not given returns statistics for
     *&#64;&#64;     all models.
     *&#64;&#64;
     *
     * Generated from protobuf field <code>string name = 1;</code>
     */
    protected $name = '';
    /**
     *&#64;&#64;  .. cpp:var:: string version
     *&#64;&#64;
     *&#64;&#64;     The version of the model. If not given returns statistics for
     *&#64;&#64;     all model versions.
     *&#64;&#64;
     *
     * Generated from protobuf field <code>string version = 2;</code>
     */
    protected $version = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *          &#64;&#64;  .. cpp:var:: string name
     *          &#64;&#64;
     *          &#64;&#64;     The name of the model. If not given returns statistics for
     *          &#64;&#64;     all models.
     *          &#64;&#64;
     *     @type string $version
     *          &#64;&#64;  .. cpp:var:: string version
     *          &#64;&#64;
     *          &#64;&#64;     The version of the model. If not given returns statistics for
     *          &#64;&#64;     all model versions.
     *          &#64;&#64;
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\GrpcService::initOnce();
        parent::__construct($data);
    }

    /**
     *&#64;&#64;  .. cpp:var:: string name
     *&#64;&#64;
     *&#64;&#64;     The name of the model. If not given returns statistics for
     *&#64;&#64;     all models.
     *&#64;&#64;
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     *&#64;&#64;  .. cpp:var:: string name
     *&#64;&#64;
     *&#64;&#64;     The name of the model. If not given returns statistics for
     *&#64;&#64;     all models.
     *&#64;&#64;
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     *&#64;&#64;  .. cpp:var:: string version
     *&#64;&#64;
     *&#64;&#64;     The version of the model. If not given returns statistics for
     *&#64;&#64;     all model versions.
     *&#64;&#64;
     *
     * Generated from protobuf field <code>string version = 2;</code>
     * @return string
     */
    public function getVersion()
    {
        return $this->version;
    }

    /**
     *&#64;&#64;  .. cpp:var:: string version
     *&#64;&#64;
     *&#64;&#64;     The version of the model. If not given returns statistics for
     *&#64;&#64;     all model versions.
     *&#64;&#64;
     *
     * Generated from protobuf field <code>string version = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setVersion($var)
    {
        GPBUtil::checkString($var, True);
        $this->version = $var;

        return $this;
    }

}

