<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: model_config.proto

namespace Inference;

if (false) {
    /**
     * This class is deprecated. Use Inference\ModelVersionPolicy\Latest instead.
     * @deprecated
     */
    class ModelVersionPolicy_Latest {}
}
class_exists(ModelVersionPolicy\Latest::class);
@trigger_error('Inference\ModelVersionPolicy_Latest is deprecated and will be removed in the next major release. Use Inference\ModelVersionPolicy\Latest instead', E_USER_DEPRECATED);

