<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: model_config.proto

namespace Inference;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *&#64;&#64;
 *&#64;&#64;  .. cpp:var:: message ModelMetrics
 *&#64;&#64;
 *&#64;&#64;     The metrics setting of this model.
 *&#64;&#64;     NOTE: Consider reusing this message body for backend metric custom
 *&#64;&#64;     configuration.
 *&#64;&#64;
 *
 * Generated from protobuf message <code>inference.ModelMetrics</code>
 */
class ModelMetrics extends \Google\Protobuf\Internal\Message
{
    /**
     *&#64;&#64;
     *&#64;&#64;  .. cpp::var:: MetricControl metric_control (repeated)
     *&#64;&#64;
     *&#64;&#64;     Optional custom configuration for selected metrics.
     *&#64;&#64;
     *
     * Generated from protobuf field <code>repeated .inference.ModelMetrics.MetricControl metric_control = 1;</code>
     */
    private $metric_control;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Inference\ModelMetrics\MetricControl[]|\Google\Protobuf\Internal\RepeatedField $metric_control
     *          &#64;&#64;
     *          &#64;&#64;  .. cpp::var:: MetricControl metric_control (repeated)
     *          &#64;&#64;
     *          &#64;&#64;     Optional custom configuration for selected metrics.
     *          &#64;&#64;
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\ModelConfig::initOnce();
        parent::__construct($data);
    }

    /**
     *&#64;&#64;
     *&#64;&#64;  .. cpp::var:: MetricControl metric_control (repeated)
     *&#64;&#64;
     *&#64;&#64;     Optional custom configuration for selected metrics.
     *&#64;&#64;
     *
     * Generated from protobuf field <code>repeated .inference.ModelMetrics.MetricControl metric_control = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getMetricControl()
    {
        return $this->metric_control;
    }

    /**
     *&#64;&#64;
     *&#64;&#64;  .. cpp::var:: MetricControl metric_control (repeated)
     *&#64;&#64;
     *&#64;&#64;     Optional custom configuration for selected metrics.
     *&#64;&#64;
     *
     * Generated from protobuf field <code>repeated .inference.ModelMetrics.MetricControl metric_control = 1;</code>
     * @param \Inference\ModelMetrics\MetricControl[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setMetricControl($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Inference\ModelMetrics\MetricControl::class);
        $this->metric_control = $arr;

        return $this;
    }

}

