<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: model_config.proto

namespace Inference;

if (false) {
    /**
     * This class is deprecated. Use Inference\ModelSequenceBatching\ControlInput instead.
     * @deprecated
     */
    class ModelSequenceBatching_ControlInput {}
}
class_exists(ModelSequenceBatching\ControlInput::class);
@trigger_error('Inference\ModelSequenceBatching_ControlInput is deprecated and will be removed in the next major release. Use Inference\ModelSequenceBatching\ControlInput instead', E_USER_DEPRECATED);

