<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: model_config.proto

namespace Inference;

if (false) {
    /**
     * This class is deprecated. Use Inference\ModelSequenceBatching\State instead.
     * @deprecated
     */
    class ModelSequenceBatching_State {}
}
class_exists(ModelSequenceBatching\State::class);
@trigger_error('Inference\ModelSequenceBatching_State is deprecated and will be removed in the next major release. Use Inference\ModelSequenceBatching\State instead', E_USER_DEPRECATED);

