<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: model_config.proto

namespace Inference;

if (false) {
    /**
     * This class is deprecated. Use Inference\ModelOptimizationPolicy\Cuda\GraphSpec\LowerBound instead.
     * @deprecated
     */
    class ModelOptimizationPolicy_Cuda_GraphSpec_LowerBound {}
}
class_exists(ModelOptimizationPolicy\Cuda\GraphSpec\LowerBound::class);
@trigger_error('Inference\ModelOptimizationPolicy_Cuda_GraphSpec_LowerBound is deprecated and will be removed in the next major release. Use Inference\ModelOptimizationPolicy\Cuda\GraphSpec\LowerBound instead', E_USER_DEPRECATED);

