<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: model_config.proto

namespace Inference;

if (false) {
    /**
     * This class is deprecated. Use Inference\ModelOptimizationPolicy\Cuda instead.
     * @deprecated
     */
    class ModelOptimizationPolicy_Cuda {}
}
class_exists(ModelOptimizationPolicy\Cuda::class);
@trigger_error('Inference\ModelOptimizationPolicy_Cuda is deprecated and will be removed in the next major release. Use Inference\ModelOptimizationPolicy\Cuda instead', E_USER_DEPRECATED);

