<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: model_config.proto

namespace Inference;

if (false) {
    /**
     * This class is deprecated. Use Inference\ModelMetrics\MetricControl\MetricIdentifier instead.
     * @deprecated
     */
    class ModelMetrics_MetricControl_MetricIdentifier {}
}
class_exists(ModelMetrics\MetricControl\MetricIdentifier::class);
@trigger_error('Inference\ModelMetrics_MetricControl_MetricIdentifier is deprecated and will be removed in the next major release. Use Inference\ModelMetrics\MetricControl\MetricIdentifier instead', E_USER_DEPRECATED);

