<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: model_config.proto

namespace Inference;

if (false) {
    /**
     * This class is deprecated. Use Inference\ModelOptimizationPolicy\ExecutionAccelerators instead.
     * @deprecated
     */
    class ModelOptimizationPolicy_ExecutionAccelerators {}
}
class_exists(ModelOptimizationPolicy\ExecutionAccelerators::class);
@trigger_error('Inference\ModelOptimizationPolicy_ExecutionAccelerators is deprecated and will be removed in the next major release. Use Inference\ModelOptimizationPolicy\ExecutionAccelerators instead', E_USER_DEPRECATED);

