<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: model_config.proto

namespace Inference;

if (false) {
    /**
     * This class is deprecated. Use Inference\ModelVersionPolicy\All instead.
     * @deprecated
     */
    class ModelVersionPolicy_All {}
}
class_exists(ModelVersionPolicy\All::class);
@trigger_error('Inference\ModelVersionPolicy_All is deprecated and will be removed in the next major release. Use Inference\ModelVersionPolicy\All instead', E_USER_DEPRECATED);

