<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc_service.proto

namespace Inference;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *&#64;&#64;
 *&#64;&#64;.. cpp:var:: message RepositoryIndexResponse
 *&#64;&#64;
 *&#64;&#64;   Response message for RepositoryIndex.
 *&#64;&#64;
 *
 * Generated from protobuf message <code>inference.RepositoryIndexResponse</code>
 */
class RepositoryIndexResponse extends \Google\Protobuf\Internal\Message
{
    /**
     *&#64;&#64;
     *&#64;&#64;  .. cpp:var:: ModelIndex models (repeated)
     *&#64;&#64;
     *&#64;&#64;     An index entry for each model.
     *&#64;&#64;
     *
     * Generated from protobuf field <code>repeated .inference.RepositoryIndexResponse.ModelIndex models = 1;</code>
     */
    private $models;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Inference\RepositoryIndexResponse\ModelIndex[]|\Google\Protobuf\Internal\RepeatedField $models
     *          &#64;&#64;
     *          &#64;&#64;  .. cpp:var:: ModelIndex models (repeated)
     *          &#64;&#64;
     *          &#64;&#64;     An index entry for each model.
     *          &#64;&#64;
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\GrpcService::initOnce();
        parent::__construct($data);
    }

    /**
     *&#64;&#64;
     *&#64;&#64;  .. cpp:var:: ModelIndex models (repeated)
     *&#64;&#64;
     *&#64;&#64;     An index entry for each model.
     *&#64;&#64;
     *
     * Generated from protobuf field <code>repeated .inference.RepositoryIndexResponse.ModelIndex models = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getModels()
    {
        return $this->models;
    }

    /**
     *&#64;&#64;
     *&#64;&#64;  .. cpp:var:: ModelIndex models (repeated)
     *&#64;&#64;
     *&#64;&#64;     An index entry for each model.
     *&#64;&#64;
     *
     * Generated from protobuf field <code>repeated .inference.RepositoryIndexResponse.ModelIndex models = 1;</code>
     * @param \Inference\RepositoryIndexResponse\ModelIndex[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setModels($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Inference\RepositoryIndexResponse\ModelIndex::class);
        $this->models = $arr;

        return $this;
    }

}

