<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc_service.proto

namespace Inference;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *&#64;&#64;
 *&#64;&#64;.. cpp:var:: message ServerReadyResponse
 *&#64;&#64;
 *&#64;&#64;   Response message for ServerReady.
 *&#64;&#64;
 *
 * Generated from protobuf message <code>inference.ServerReadyResponse</code>
 */
class ServerReadyResponse extends \Google\Protobuf\Internal\Message
{
    /**
     *&#64;&#64;
     *&#64;&#64;  .. cpp:var:: bool ready
     *&#64;&#64;
     *&#64;&#64;     True if the inference server is ready, false it not ready.
     *&#64;&#64;
     *
     * Generated from protobuf field <code>bool ready = 1;</code>
     */
    protected $ready = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $ready
     *          &#64;&#64;
     *          &#64;&#64;  .. cpp:var:: bool ready
     *          &#64;&#64;
     *          &#64;&#64;     True if the inference server is ready, false it not ready.
     *          &#64;&#64;
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\GrpcService::initOnce();
        parent::__construct($data);
    }

    /**
     *&#64;&#64;
     *&#64;&#64;  .. cpp:var:: bool ready
     *&#64;&#64;
     *&#64;&#64;     True if the inference server is ready, false it not ready.
     *&#64;&#64;
     *
     * Generated from protobuf field <code>bool ready = 1;</code>
     * @return bool
     */
    public function getReady()
    {
        return $this->ready;
    }

    /**
     *&#64;&#64;
     *&#64;&#64;  .. cpp:var:: bool ready
     *&#64;&#64;
     *&#64;&#64;     True if the inference server is ready, false it not ready.
     *&#64;&#64;
     *
     * Generated from protobuf field <code>bool ready = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setReady($var)
    {
        GPBUtil::checkBool($var);
        $this->ready = $var;

        return $this;
    }

}

