<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc_service.proto

namespace Inference;

if (false) {
    /**
     * This class is deprecated. Use Inference\SystemSharedMemoryStatusResponse\RegionStatus instead.
     * @deprecated
     */
    class SystemSharedMemoryStatusResponse_RegionStatus {}
}
class_exists(SystemSharedMemoryStatusResponse\RegionStatus::class);
@trigger_error('Inference\SystemSharedMemoryStatusResponse_RegionStatus is deprecated and will be removed in the next major release. Use Inference\SystemSharedMemoryStatusResponse\RegionStatus instead', E_USER_DEPRECATED);

