<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc_service.proto

namespace Inference;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *&#64;&#64;
 *&#64;&#64;.. cpp:var:: message TraceSettingResponse
 *&#64;&#64;
 *&#64;&#64;   Response message for TraceSetting.
 *&#64;&#64;
 *
 * Generated from protobuf message <code>inference.TraceSettingResponse</code>
 */
class TraceSettingResponse extends \Google\Protobuf\Internal\Message
{
    /**
     *&#64;&#64;  .. cpp:var:: map<string,SettingValue> settings
     *&#64;&#64;
     *&#64;&#64;     The current trace settings, including any changes specified
     *&#64;&#64;     by TraceSettingRequest.
     *&#64;&#64;
     *
     * Generated from protobuf field <code>map<string, .inference.TraceSettingResponse.SettingValue> settings = 1;</code>
     */
    private $settings;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array|\Google\Protobuf\Internal\MapField $settings
     *          &#64;&#64;  .. cpp:var:: map<string,SettingValue> settings
     *          &#64;&#64;
     *          &#64;&#64;     The current trace settings, including any changes specified
     *          &#64;&#64;     by TraceSettingRequest.
     *          &#64;&#64;
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\GrpcService::initOnce();
        parent::__construct($data);
    }

    /**
     *&#64;&#64;  .. cpp:var:: map<string,SettingValue> settings
     *&#64;&#64;
     *&#64;&#64;     The current trace settings, including any changes specified
     *&#64;&#64;     by TraceSettingRequest.
     *&#64;&#64;
     *
     * Generated from protobuf field <code>map<string, .inference.TraceSettingResponse.SettingValue> settings = 1;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getSettings()
    {
        return $this->settings;
    }

    /**
     *&#64;&#64;  .. cpp:var:: map<string,SettingValue> settings
     *&#64;&#64;
     *&#64;&#64;     The current trace settings, including any changes specified
     *&#64;&#64;     by TraceSettingRequest.
     *&#64;&#64;
     *
     * Generated from protobuf field <code>map<string, .inference.TraceSettingResponse.SettingValue> settings = 1;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setSettings($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::MESSAGE, \Inference\TraceSettingResponse\SettingValue::class);
        $this->settings = $arr;

        return $this;
    }

}

