<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc_service.proto

namespace Inference;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *&#64;&#64;
 *&#64;&#64;.. cpp:var:: message TraceSettingRequest
 *&#64;&#64;
 *&#64;&#64;   Request message for TraceSetting.
 *&#64;&#64;
 *
 * Generated from protobuf message <code>inference.TraceSettingRequest</code>
 */
class TraceSettingRequest extends \Google\Protobuf\Internal\Message
{
    /**
     *&#64;&#64;  .. cpp:var:: map<string,SettingValue> settings
     *&#64;&#64;
     *&#64;&#64;     The new setting values to be updated,
     *&#64;&#64;     settings that are not specified will remain unchanged.
     *&#64;&#64;
     *
     * Generated from protobuf field <code>map<string, .inference.TraceSettingRequest.SettingValue> settings = 1;</code>
     */
    private $settings;
    /**
     *&#64;&#64;
     *&#64;&#64;  .. cpp:var:: string model_name
     *&#64;&#64;
     *&#64;&#64;     The name of the model to apply the new trace settings.
     *&#64;&#64;     If not given, the new settings will be applied globally.
     *&#64;&#64;
     *
     * Generated from protobuf field <code>string model_name = 2;</code>
     */
    protected $model_name = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array|\Google\Protobuf\Internal\MapField $settings
     *          &#64;&#64;  .. cpp:var:: map<string,SettingValue> settings
     *          &#64;&#64;
     *          &#64;&#64;     The new setting values to be updated,
     *          &#64;&#64;     settings that are not specified will remain unchanged.
     *          &#64;&#64;
     *     @type string $model_name
     *          &#64;&#64;
     *          &#64;&#64;  .. cpp:var:: string model_name
     *          &#64;&#64;
     *          &#64;&#64;     The name of the model to apply the new trace settings.
     *          &#64;&#64;     If not given, the new settings will be applied globally.
     *          &#64;&#64;
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\GrpcService::initOnce();
        parent::__construct($data);
    }

    /**
     *&#64;&#64;  .. cpp:var:: map<string,SettingValue> settings
     *&#64;&#64;
     *&#64;&#64;     The new setting values to be updated,
     *&#64;&#64;     settings that are not specified will remain unchanged.
     *&#64;&#64;
     *
     * Generated from protobuf field <code>map<string, .inference.TraceSettingRequest.SettingValue> settings = 1;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getSettings()
    {
        return $this->settings;
    }

    /**
     *&#64;&#64;  .. cpp:var:: map<string,SettingValue> settings
     *&#64;&#64;
     *&#64;&#64;     The new setting values to be updated,
     *&#64;&#64;     settings that are not specified will remain unchanged.
     *&#64;&#64;
     *
     * Generated from protobuf field <code>map<string, .inference.TraceSettingRequest.SettingValue> settings = 1;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setSettings($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::MESSAGE, \Inference\TraceSettingRequest\SettingValue::class);
        $this->settings = $arr;

        return $this;
    }

    /**
     *&#64;&#64;
     *&#64;&#64;  .. cpp:var:: string model_name
     *&#64;&#64;
     *&#64;&#64;     The name of the model to apply the new trace settings.
     *&#64;&#64;     If not given, the new settings will be applied globally.
     *&#64;&#64;
     *
     * Generated from protobuf field <code>string model_name = 2;</code>
     * @return string
     */
    public function getModelName()
    {
        return $this->model_name;
    }

    /**
     *&#64;&#64;
     *&#64;&#64;  .. cpp:var:: string model_name
     *&#64;&#64;
     *&#64;&#64;     The name of the model to apply the new trace settings.
     *&#64;&#64;     If not given, the new settings will be applied globally.
     *&#64;&#64;
     *
     * Generated from protobuf field <code>string model_name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setModelName($var)
    {
        GPBUtil::checkString($var, True);
        $this->model_name = $var;

        return $this;
    }

}

