<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc_service.proto

namespace Inference;

if (false) {
    /**
     * This class is deprecated. Use Inference\TraceSettingRequest\SettingValue instead.
     * @deprecated
     */
    class TraceSettingRequest_SettingValue {}
}
class_exists(TraceSettingRequest\SettingValue::class);
@trigger_error('Inference\TraceSettingRequest_SettingValue is deprecated and will be removed in the next major release. Use Inference\TraceSettingRequest\SettingValue instead', E_USER_DEPRECATED);

