<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: model_config.proto

namespace Inference\ModelMetrics;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 *\@\@
 *\@\@  .. cpp:var:: message MetricControl
 *\@\@
 *\@\@     Override metrics settings of this model.
 *\@\@
 *
 * Generated from protobuf message <code>inference.ModelMetrics.MetricControl</code>
 */
class MetricControl extends \Google\Protobuf\Internal\Message
{
    /**
     *\@\@  .. cpp:var:: MetricIdentifier metric_identifier
     *\@\@
     *\@\@     The identifier defining metrics to be overridden with the
     *\@\@     metric_options.
     *\@\@
     *
     * Generated from protobuf field <code>.inference.ModelMetrics.MetricControl.MetricIdentifier metric_identifier = 1;</code>
     */
    protected $metric_identifier = null;
    protected $metric_options;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Inference\ModelMetrics\MetricControl\MetricIdentifier $metric_identifier
     *          \@\@  .. cpp:var:: MetricIdentifier metric_identifier
     *          \@\@
     *          \@\@     The identifier defining metrics to be overridden with the
     *          \@\@     metric_options.
     *          \@\@
     *     @type \Inference\ModelMetrics\MetricControl\HistogramOptions $histogram_options
     *          \@\@  .. cpp:var:: HistogramOptions histogram_options
     *          \@\@
     *          \@\@     Histogram options.
     *          \@\@
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\ModelConfig::initOnce();
        parent::__construct($data);
    }

    /**
     *\@\@  .. cpp:var:: MetricIdentifier metric_identifier
     *\@\@
     *\@\@     The identifier defining metrics to be overridden with the
     *\@\@     metric_options.
     *\@\@
     *
     * Generated from protobuf field <code>.inference.ModelMetrics.MetricControl.MetricIdentifier metric_identifier = 1;</code>
     * @return \Inference\ModelMetrics\MetricControl\MetricIdentifier|null
     */
    public function getMetricIdentifier()
    {
        return $this->metric_identifier;
    }

    public function hasMetricIdentifier()
    {
        return isset($this->metric_identifier);
    }

    public function clearMetricIdentifier()
    {
        unset($this->metric_identifier);
    }

    /**
     *\@\@  .. cpp:var:: MetricIdentifier metric_identifier
     *\@\@
     *\@\@     The identifier defining metrics to be overridden with the
     *\@\@     metric_options.
     *\@\@
     *
     * Generated from protobuf field <code>.inference.ModelMetrics.MetricControl.MetricIdentifier metric_identifier = 1;</code>
     * @param \Inference\ModelMetrics\MetricControl\MetricIdentifier $var
     * @return $this
     */
    public function setMetricIdentifier($var)
    {
        GPBUtil::checkMessage($var, \Inference\ModelMetrics\MetricControl\MetricIdentifier::class);
        $this->metric_identifier = $var;

        return $this;
    }

    /**
     *\@\@  .. cpp:var:: HistogramOptions histogram_options
     *\@\@
     *\@\@     Histogram options.
     *\@\@
     *
     * Generated from protobuf field <code>.inference.ModelMetrics.MetricControl.HistogramOptions histogram_options = 2;</code>
     * @return \Inference\ModelMetrics\MetricControl\HistogramOptions|null
     */
    public function getHistogramOptions()
    {
        return $this->readOneof(2);
    }

    public function hasHistogramOptions()
    {
        return $this->hasOneof(2);
    }

    /**
     *\@\@  .. cpp:var:: HistogramOptions histogram_options
     *\@\@
     *\@\@     Histogram options.
     *\@\@
     *
     * Generated from protobuf field <code>.inference.ModelMetrics.MetricControl.HistogramOptions histogram_options = 2;</code>
     * @param \Inference\ModelMetrics\MetricControl\HistogramOptions $var
     * @return $this
     */
    public function setHistogramOptions($var)
    {
        GPBUtil::checkMessage($var, \Inference\ModelMetrics\MetricControl\HistogramOptions::class);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getMetricOptions()
    {
        return $this->whichOneof("metric_options");
    }

}

