<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc_service.proto

namespace Inference\ModelInferRequest;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *&#64;&#64;
 *&#64;&#64;  .. cpp:var:: message InferRequestedOutputTensor
 *&#64;&#64;
 *&#64;&#64;     An output tensor requested for an inference request.
 *&#64;&#64;
 *
 * Generated from protobuf message <code>inference.ModelInferRequest.InferRequestedOutputTensor</code>
 */
class InferRequestedOutputTensor extends \Google\Protobuf\Internal\Message
{
    /**
     *&#64;&#64;
     *&#64;&#64;    .. cpp:var:: string name
     *&#64;&#64;
     *&#64;&#64;       The tensor name.
     *&#64;&#64;
     *
     * Generated from protobuf field <code>string name = 1;</code>
     */
    protected $name = '';
    /**
     *&#64;&#64;    .. cpp:var:: map<string,InferParameter> parameters
     *&#64;&#64;
     *&#64;&#64;       Optional requested output tensor parameters.
     *&#64;&#64;
     *
     * Generated from protobuf field <code>map<string, .inference.InferParameter> parameters = 2;</code>
     */
    private $parameters;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *          &#64;&#64;
     *          &#64;&#64;    .. cpp:var:: string name
     *          &#64;&#64;
     *          &#64;&#64;       The tensor name.
     *          &#64;&#64;
     *     @type array|\Google\Protobuf\Internal\MapField $parameters
     *          &#64;&#64;    .. cpp:var:: map<string,InferParameter> parameters
     *          &#64;&#64;
     *          &#64;&#64;       Optional requested output tensor parameters.
     *          &#64;&#64;
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\GrpcService::initOnce();
        parent::__construct($data);
    }

    /**
     *&#64;&#64;
     *&#64;&#64;    .. cpp:var:: string name
     *&#64;&#64;
     *&#64;&#64;       The tensor name.
     *&#64;&#64;
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     *&#64;&#64;
     *&#64;&#64;    .. cpp:var:: string name
     *&#64;&#64;
     *&#64;&#64;       The tensor name.
     *&#64;&#64;
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     *&#64;&#64;    .. cpp:var:: map<string,InferParameter> parameters
     *&#64;&#64;
     *&#64;&#64;       Optional requested output tensor parameters.
     *&#64;&#64;
     *
     * Generated from protobuf field <code>map<string, .inference.InferParameter> parameters = 2;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getParameters()
    {
        return $this->parameters;
    }

    /**
     *&#64;&#64;    .. cpp:var:: map<string,InferParameter> parameters
     *&#64;&#64;
     *&#64;&#64;       Optional requested output tensor parameters.
     *&#64;&#64;
     *
     * Generated from protobuf field <code>map<string, .inference.InferParameter> parameters = 2;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setParameters($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::MESSAGE, \Inference\InferParameter::class);
        $this->parameters = $arr;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(InferRequestedOutputTensor::class, \Inference\ModelInferRequest_InferRequestedOutputTensor::class);

