<?php

declare(strict_types=1);

namespace App\Service\SelfAware;

use App\Entity\Model;
use App\Repository\ModelRepository;
use App\Service\Knowledge\KnowledgeContextFormatter;
use App\Service\ModelConfigService;
use App\Service\SelfAware\Docs\PlatformDocsHits;

/**
 * Replaces (or strips) the `[PLATFORM_CAPABILITIES]` and `[PLATFORM_DOCS]`
 * placeholders in a topic prompt. One call site for both ChatHandler paths.
 */
final readonly class SelfAwarePromptDecorator
{
    public const PLACEHOLDER_CAPABILITIES = '[PLATFORM_CAPABILITIES]';
    public const PLACEHOLDER_DOCS = '[PLATFORM_DOCS]';

    public function __construct(
        private SelfAwareConfig $config,
        private CapabilityInventory $inventory,
        private CapabilityReportRenderer $renderer,
        private KnowledgeContextFormatter $knowledgeContextFormatter,
        private ModelRepository $modelRepository,
        private ModelConfigService $modelConfig,
    ) {
    }

    /**
     * Widget conversations (public embeds) are excluded — they answer for the
     * operator's business, not for Synaplan.
     *
     * @param array<string, mixed> $classification
     * @param array<string, mixed> $options
     */
    public static function isWidgetConversation(array $classification, array $options): bool
    {
        return 'WIDGET' === ($options['channel'] ?? null)
            || 'widget' === ($classification['source'] ?? null);
    }

    public function apply(
        string $prompt,
        string $topic,
        int $userId,
        bool $isWidget,
        ?PlatformDocsHits $docsHits = null,
        ?int $modelId = null,
    ): string {
        $enabled = $this->config->isEnabled($userId > 0 ? $userId : null);
        $injectInventory = $enabled && !$isWidget && (
            SelfAwareConfig::ROUTABLE_TOPIC === $topic
            || ('general' === $topic && $this->config->isInventoryInGeneral($userId > 0 ? $userId : null))
        );

        if ($injectInventory) {
            $block = $this->renderer->render(
                $this->inventory->build($userId),
                $this->modelLine($modelId, $userId),
            );
            $prompt = str_replace(self::PLACEHOLDER_CAPABILITIES, $block, $prompt);
        } else {
            $prompt = str_replace(self::PLACEHOLDER_CAPABILITIES, '', $prompt);
        }

        $injectDocs = $enabled
            && !$isWidget
            && SelfAwareConfig::ROUTABLE_TOPIC === $topic
            && null !== $docsHits
            && !$docsHits->isEmpty();

        if ($injectDocs) {
            $prompt = str_replace(
                self::PLACEHOLDER_DOCS,
                $this->knowledgeContextFormatter->formatPlatformDocsContext($docsHits),
                $prompt,
            );
        } else {
            $prompt = str_replace(self::PLACEHOLDER_DOCS, '', $prompt);
        }

        return $prompt;
    }

    /**
     * Names the model answering this turn and the Chat / General default.
     * Omitted when neither resolves, so an install without a chat model
     * keeps the previous "ask your administrator" behaviour.
     */
    private function modelLine(?int $modelId, int $userId): ?string
    {
        $replyId = (null !== $modelId && $modelId > 0) ? $modelId : null;
        $defaultId = $this->modelConfig->getDefaultModel('CHAT', $userId > 0 ? $userId : null);
        if (null === $defaultId || $defaultId <= 0) {
            $defaultId = null;
        }

        $reply = $this->modelLabel($replyId);
        $default = $replyId === $defaultId ? $reply : $this->modelLabel($defaultId);
        if (null === $reply && null === $default) {
            return null;
        }

        $instruction = ' When asked which model you are, keep the introduction: you are the Synaplan AI assistant and you use the chat model configured for this workspace. Add the model name from this line to that answer. Do not replace the introduction with only the provider model name, and do not say an administrator decides the model or that you cannot name it.';
        if (null !== $reply && $reply === $default) {
            return 'MODEL: This reply is generated by '.$reply.', the default model for Chat / General.'.$instruction;
        }
        if (null !== $reply && null !== $default) {
            return 'MODEL: This reply is generated by '.$reply.'. Default model for Chat / General: '.$default.'.'.$instruction;
        }
        if (null !== $reply) {
            return 'MODEL: This reply is generated by '.$reply.'.'.$instruction;
        }

        return 'MODEL: Default model for Chat / General: '.$default.'.'.$instruction;
    }

    private function modelLabel(?int $modelId): ?string
    {
        if (null === $modelId) {
            return null;
        }

        $model = $this->modelRepository->find($modelId);
        if (!$model instanceof Model) {
            return null;
        }

        $name = trim($model->getName());
        if ('' === $name) {
            return null;
        }

        $service = trim($model->getService());
        if ('' === $service) {
            return $name;
        }

        return $name.' ('.$service.')';
    }
}
