<?php

declare(strict_types=1);

namespace App\Tests\Unit\Service\SelfAware;

use App\Entity\Model;
use App\Repository\ConfigRepository;
use App\Repository\ModelRepository;
use App\Service\Knowledge\KnowledgeContextFormatter;
use App\Service\ModelConfigService;
use App\Service\SelfAware\CapabilityFact;
use App\Service\SelfAware\CapabilityInventory;
use App\Service\SelfAware\CapabilityReport;
use App\Service\SelfAware\CapabilityReportRenderer;
use App\Service\SelfAware\CapabilityState;
use App\Service\SelfAware\Docs\PlatformDocsHit;
use App\Service\SelfAware\Docs\PlatformDocsHits;
use App\Service\SelfAware\SelfAwareConfig;
use App\Service\SelfAware\SelfAwarePromptDecorator;
use PHPUnit\Framework\TestCase;

final class SelfAwarePromptDecoratorTest extends TestCase
{
    public function testReplacesCapabilitiesForSynaplanAndStripsOtherwise(): void
    {
        $decorator = $this->decorator(enabled: true, inventoryInGeneral: true);

        $synaplan = $decorator->apply(
            "Hello\n[PLATFORM_CAPABILITIES]\n[PLATFORM_DOCS]\n",
            'synaplan',
            2,
            false,
        );
        $this->assertStringContainsString('AVAILABLE NOW:', $synaplan);
        $this->assertStringNotContainsString('[PLATFORM_CAPABILITIES]', $synaplan);
        $this->assertStringNotContainsString('[PLATFORM_DOCS]', $synaplan);

        $general = $decorator->apply('x [PLATFORM_CAPABILITIES] y', 'general', 2, false);
        $this->assertStringContainsString('AVAILABLE NOW:', $general);

        $other = $decorator->apply('x [PLATFORM_CAPABILITIES] y', 'officemaker', 2, false);
        $this->assertSame('x  y', $other);
    }

    public function testGeneralHonoursInventoryFlagAndWidgetsAreStripped(): void
    {
        $decorator = $this->decorator(enabled: true, inventoryInGeneral: false);
        $general = $decorator->apply('[PLATFORM_CAPABILITIES]', 'general', 2, false);
        $this->assertSame('', $general);

        $on = $this->decorator(enabled: true, inventoryInGeneral: true);
        $widget = $on->apply('[PLATFORM_CAPABILITIES]', 'synaplan', 2, true);
        $this->assertSame('', $widget);
    }

    public function testDisabledFlagStripsPlaceholders(): void
    {
        $decorator = $this->decorator(enabled: false, inventoryInGeneral: true);
        $out = $decorator->apply('[PLATFORM_CAPABILITIES][PLATFORM_DOCS]', 'synaplan', 2, false);
        $this->assertSame('', $out);
    }

    public function testDocsPlaceholderFilledOnlyForSynaplanHits(): void
    {
        $decorator = $this->decorator(enabled: true, inventoryInGeneral: true);
        $hits = new PlatformDocsHits([
            new PlatformDocsHit('channels', 'Channels', 'https://docs.synaplan.com/channels', 'Using', 'WhatsApp steps', 0.9),
        ]);

        $withDocs = $decorator->apply('[PLATFORM_DOCS]', 'synaplan', 2, false, $hits);
        $this->assertStringContainsString('[Doc:channels]', $withDocs);

        $general = $decorator->apply('[PLATFORM_DOCS]', 'general', 2, false, $hits);
        $this->assertSame('', $general);
    }

    public function testModelLineNamesTheAnsweringModelAndTheChatDefault(): void
    {
        $same = $this->decorator(enabled: true, inventoryInGeneral: true, defaultModelId: 10);
        $once = $same->apply('[PLATFORM_CAPABILITIES]', 'synaplan', 2, false, null, 10);
        $this->assertSame(1, substr_count($once, 'Claude Sonnet 4.5 (Anthropic)'));
        $this->assertStringContainsString(
            'MODEL: This reply is generated by Claude Sonnet 4.5 (Anthropic), the default model for Chat / General.',
            $once,
        );

        $different = $this->decorator(enabled: true, inventoryInGeneral: true, defaultModelId: 10);
        $both = $different->apply('[PLATFORM_CAPABILITIES]', 'general', 2, false, null, 20);
        $this->assertStringContainsString('This reply is generated by GPT-4o (OpenAI).', $both);
        $this->assertStringContainsString('Default model for Chat / General: Claude Sonnet 4.5 (Anthropic).', $both);
        $this->assertStringContainsString('you are the Synaplan AI assistant', $both);
        $this->assertStringContainsString('Add the model name from this line', $both);
        $this->assertStringNotContainsString('name it exactly like this', $both);

        $unknown = $this->decorator(enabled: true, inventoryInGeneral: true, defaultModelId: null);
        $none = $unknown->apply('[PLATFORM_CAPABILITIES]', 'synaplan', 2, false, null, null);
        $this->assertStringNotContainsString('MODEL:', $none);
        $this->assertStringContainsString('AVAILABLE NOW:', $none);
    }

    public function testWidgetConversationHelper(): void
    {
        $this->assertTrue(SelfAwarePromptDecorator::isWidgetConversation(['source' => 'widget'], []));
        $this->assertTrue(SelfAwarePromptDecorator::isWidgetConversation([], ['channel' => 'WIDGET']));
        $this->assertFalse(SelfAwarePromptDecorator::isWidgetConversation(['source' => 'web'], ['channel' => 'WEB']));
    }

    private function decorator(bool $enabled, bool $inventoryInGeneral, ?int $defaultModelId = null): SelfAwarePromptDecorator
    {
        $configRepo = $this->createMock(ConfigRepository::class);
        $configRepo->method('getValue')->willReturnCallback(
            static function (int $owner, string $group, string $setting) use ($enabled, $inventoryInGeneral): ?string {
                if (SelfAwareConfig::CONFIG_GROUP !== $group) {
                    return null;
                }

                return match ($setting) {
                    SelfAwareConfig::KEY_ENABLED => $enabled ? '1' : '0',
                    SelfAwareConfig::KEY_INVENTORY_IN_GENERAL => $inventoryInGeneral ? '1' : '0',
                    default => null,
                };
            }
        );

        $inventory = $this->createMock(CapabilityInventory::class);
        $inventory->method('build')->willReturn(new CapabilityReport(
            [new CapabilityFact('chat', 'Chat', CapabilityState::Available, 'ready', null, null, null)],
            '4.2.1',
            false,
            false,
        ));

        $claude = (new Model())->setName('Claude Sonnet 4.5')->setService('Anthropic');
        $gpt = (new Model())->setName('GPT-4o')->setService('OpenAI');
        $models = $this->createMock(ModelRepository::class);
        $models->method('find')->willReturnCallback(
            static function (mixed $id) use ($claude, $gpt): ?Model {
                return match ((int) $id) {
                    10 => $claude,
                    20 => $gpt,
                    default => null,
                };
            }
        );

        $modelConfig = $this->createMock(ModelConfigService::class);
        $modelConfig->method('getDefaultModel')->willReturn($defaultModelId);

        return new SelfAwarePromptDecorator(
            new SelfAwareConfig($configRepo),
            $inventory,
            new CapabilityReportRenderer(),
            new KnowledgeContextFormatter(),
            $models,
            $modelConfig,
        );
    }
}
