<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: model_config.proto

namespace Inference\ModelMetrics\MetricControl;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 *\@\@  .. cpp:var:: message HistogramOptions
 *\@\@
 *\@\@     Histogram metrics options.
 *\@\@
 *
 * Generated from protobuf message <code>inference.ModelMetrics.MetricControl.HistogramOptions</code>
 */
class HistogramOptions extends \Google\Protobuf\Internal\Message
{
    /**
     *\@\@  .. cpp:var:: double buckets (repeated)
     *\@\@
     *\@\@     Repeated double type in ascending order for histogram bucket
     *\@\@     boundaries. Each bucket value represents a range less than or
     *\@\@     equal to itself. The range greater than the largest bucket value
     *\@\@     is allocated implicitly.
     *\@\@     For example, [ -5.0, -2, 0, 3.5, 5 ].
     *\@\@
     *
     * Generated from protobuf field <code>repeated double buckets = 1;</code>
     */
    private $buckets;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type float[] $buckets
     *          \@\@  .. cpp:var:: double buckets (repeated)
     *          \@\@
     *          \@\@     Repeated double type in ascending order for histogram bucket
     *          \@\@     boundaries. Each bucket value represents a range less than or
     *          \@\@     equal to itself. The range greater than the largest bucket value
     *          \@\@     is allocated implicitly.
     *          \@\@     For example, [ -5.0, -2, 0, 3.5, 5 ].
     *          \@\@
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\ModelConfig::initOnce();
        parent::__construct($data);
    }

    /**
     *\@\@  .. cpp:var:: double buckets (repeated)
     *\@\@
     *\@\@     Repeated double type in ascending order for histogram bucket
     *\@\@     boundaries. Each bucket value represents a range less than or
     *\@\@     equal to itself. The range greater than the largest bucket value
     *\@\@     is allocated implicitly.
     *\@\@     For example, [ -5.0, -2, 0, 3.5, 5 ].
     *\@\@
     *
     * Generated from protobuf field <code>repeated double buckets = 1;</code>
     * @return RepeatedField<float>
     */
    public function getBuckets()
    {
        return $this->buckets;
    }

    /**
     *\@\@  .. cpp:var:: double buckets (repeated)
     *\@\@
     *\@\@     Repeated double type in ascending order for histogram bucket
     *\@\@     boundaries. Each bucket value represents a range less than or
     *\@\@     equal to itself. The range greater than the largest bucket value
     *\@\@     is allocated implicitly.
     *\@\@     For example, [ -5.0, -2, 0, 3.5, 5 ].
     *\@\@
     *
     * Generated from protobuf field <code>repeated double buckets = 1;</code>
     * @param float[] $var
     * @return $this
     */
    public function setBuckets($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::DOUBLE);
        $this->buckets = $arr;

        return $this;
    }

}

