<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: model_config.proto

namespace Inference\ModelVersionPolicy;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 *\@\@  .. cpp:var:: message Specific
 *\@\@
 *\@\@     Serve only specific versions of the model.
 *\@\@
 *
 * Generated from protobuf message <code>inference.ModelVersionPolicy.Specific</code>
 */
class Specific extends \Google\Protobuf\Internal\Message
{
    /**
     *\@\@    .. cpp:var:: int64 versions (repeated)
     *\@\@
     *\@\@       The specific versions of the model that will be served.
     *\@\@
     *
     * Generated from protobuf field <code>repeated int64 versions = 1;</code>
     */
    private $versions;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int[]|string[] $versions
     *          \@\@    .. cpp:var:: int64 versions (repeated)
     *          \@\@
     *          \@\@       The specific versions of the model that will be served.
     *          \@\@
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\ModelConfig::initOnce();
        parent::__construct($data);
    }

    /**
     *\@\@    .. cpp:var:: int64 versions (repeated)
     *\@\@
     *\@\@       The specific versions of the model that will be served.
     *\@\@
     *
     * Generated from protobuf field <code>repeated int64 versions = 1;</code>
     * @return RepeatedField<int>|RepeatedField<string>
     */
    public function getVersions()
    {
        return $this->versions;
    }

    /**
     *\@\@    .. cpp:var:: int64 versions (repeated)
     *\@\@
     *\@\@       The specific versions of the model that will be served.
     *\@\@
     *
     * Generated from protobuf field <code>repeated int64 versions = 1;</code>
     * @param int[]|string[] $var
     * @return $this
     */
    public function setVersions($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::INT64);
        $this->versions = $arr;

        return $this;
    }

}

