<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: model_config.proto

namespace Inference\ModelRepositoryAgents;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *&#64;&#64;
 *&#64;&#64;  .. cpp:var:: message Agent
 *&#64;&#64;
 *&#64;&#64;     A repository agent that should be invoked for the specified
 *&#64;&#64;     repository actions for this model.
 *&#64;&#64;
 *
 * Generated from protobuf message <code>inference.ModelRepositoryAgents.Agent</code>
 */
class Agent extends \Google\Protobuf\Internal\Message
{
    /**
     *&#64;&#64;    .. cpp:var:: string name
     *&#64;&#64;
     *&#64;&#64;       The name of the agent.
     *&#64;&#64;
     *
     * Generated from protobuf field <code>string name = 1;</code>
     */
    protected $name = '';
    /**
     *&#64;&#64;    .. cpp:var:: map<string, string> parameters
     *&#64;&#64;
     *&#64;&#64;       The parameters for the agent.
     *&#64;&#64;
     *
     * Generated from protobuf field <code>map<string, string> parameters = 2;</code>
     */
    private $parameters;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *          &#64;&#64;    .. cpp:var:: string name
     *          &#64;&#64;
     *          &#64;&#64;       The name of the agent.
     *          &#64;&#64;
     *     @type array|\Google\Protobuf\Internal\MapField $parameters
     *          &#64;&#64;    .. cpp:var:: map<string, string> parameters
     *          &#64;&#64;
     *          &#64;&#64;       The parameters for the agent.
     *          &#64;&#64;
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\ModelConfig::initOnce();
        parent::__construct($data);
    }

    /**
     *&#64;&#64;    .. cpp:var:: string name
     *&#64;&#64;
     *&#64;&#64;       The name of the agent.
     *&#64;&#64;
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     *&#64;&#64;    .. cpp:var:: string name
     *&#64;&#64;
     *&#64;&#64;       The name of the agent.
     *&#64;&#64;
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     *&#64;&#64;    .. cpp:var:: map<string, string> parameters
     *&#64;&#64;
     *&#64;&#64;       The parameters for the agent.
     *&#64;&#64;
     *
     * Generated from protobuf field <code>map<string, string> parameters = 2;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getParameters()
    {
        return $this->parameters;
    }

    /**
     *&#64;&#64;    .. cpp:var:: map<string, string> parameters
     *&#64;&#64;
     *&#64;&#64;       The parameters for the agent.
     *&#64;&#64;
     *
     * Generated from protobuf field <code>map<string, string> parameters = 2;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setParameters($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->parameters = $arr;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(Agent::class, \Inference\ModelRepositoryAgents_Agent::class);

