<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: model_config.proto

namespace Inference\ModelInstanceGroup\SecondaryDevice;

use UnexpectedValueException;

/**
 *&#64;&#64;
 *&#64;&#64;  .. cpp:enum:: SecondaryDeviceKind
 *&#64;&#64;
 *&#64;&#64;     The kind of the secondary device.
 *&#64;&#64;
 *
 * Protobuf type <code>inference.ModelInstanceGroup.SecondaryDevice.SecondaryDeviceKind</code>
 */
class SecondaryDeviceKind
{
    /**
     *&#64;&#64;    .. cpp:enumerator:: SecondaryDeviceKind::KIND_NVDLA = 0
     *&#64;&#64;
     *&#64;&#64;       An NVDLA core. http://nvdla.org
     *&#64;&#64;       Currently KIND_NVDLA is only supported by the TensorRT backend.
     *&#64;&#64;
     *
     * Generated from protobuf enum <code>KIND_NVDLA = 0;</code>
     */
    const KIND_NVDLA = 0;

    private static $valueToName = [
        self::KIND_NVDLA => 'KIND_NVDLA',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(SecondaryDeviceKind::class, \Inference\ModelInstanceGroup_SecondaryDevice_SecondaryDeviceKind::class);

