<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: model_config.proto

namespace Inference\ModelOptimizationPolicy;

use UnexpectedValueException;

/**
 *\@\@
 *\@\@  .. cpp:enum:: ModelPriority
 *\@\@
 *\@\@     Model priorities. A model will be given scheduling and execution
 *\@\@     preference over models at lower priorities. Current model
 *\@\@     priorities only work for TensorRT models.
 *\@\@
 *
 * Protobuf type <code>inference.ModelOptimizationPolicy.ModelPriority</code>
 */
class ModelPriority
{
    /**
     *\@\@    .. cpp:enumerator:: ModelPriority::PRIORITY_DEFAULT = 0
     *\@\@
     *\@\@       The default model priority.
     *\@\@
     *
     * Generated from protobuf enum <code>PRIORITY_DEFAULT = 0;</code>
     */
    const PRIORITY_DEFAULT = 0;
    /**
     *\@\@    .. cpp:enumerator:: ModelPriority::PRIORITY_MAX = 1
     *\@\@
     *\@\@       The maximum model priority.
     *\@\@
     *
     * Generated from protobuf enum <code>PRIORITY_MAX = 1;</code>
     */
    const PRIORITY_MAX = 1;
    /**
     *\@\@    .. cpp:enumerator:: ModelPriority::PRIORITY_MIN = 2
     *\@\@
     *\@\@       The minimum model priority.
     *\@\@
     *
     * Generated from protobuf enum <code>PRIORITY_MIN = 2;</code>
     */
    const PRIORITY_MIN = 2;

    private static $valueToName = [
        self::PRIORITY_DEFAULT => 'PRIORITY_DEFAULT',
        self::PRIORITY_MAX => 'PRIORITY_MAX',
        self::PRIORITY_MIN => 'PRIORITY_MIN',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

