<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: model_config.proto

namespace Inference\ModelOptimizationPolicy;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 *\@\@
 *\@\@  .. cpp:var:: message PinnedMemoryBuffer
 *\@\@
 *\@\@     Specify whether to use a pinned memory buffer when transferring data
 *\@\@     between non-pinned system memory and GPU memory. Using a pinned
 *\@\@     memory buffer for system from/to GPU transfers will typically provide
 *\@\@     increased performance. For example, in the common use case where the
 *\@\@     request provides inputs and delivers outputs via non-pinned system
 *\@\@     memory, if the model instance accepts GPU IOs, the inputs will be
 *\@\@     processed by two copies: from non-pinned system memory to pinned
 *\@\@     memory, and from pinned memory to GPU memory. Similarly, pinned
 *\@\@     memory will be used for delivering the outputs.
 *\@\@
 *
 * Generated from protobuf message <code>inference.ModelOptimizationPolicy.PinnedMemoryBuffer</code>
 */
class PinnedMemoryBuffer extends \Google\Protobuf\Internal\Message
{
    /**
     *\@\@    .. cpp:var:: bool enable
     *\@\@
     *\@\@       Use pinned memory buffer. Default is true.
     *\@\@
     *
     * Generated from protobuf field <code>bool enable = 1;</code>
     */
    protected $enable = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $enable
     *          \@\@    .. cpp:var:: bool enable
     *          \@\@
     *          \@\@       Use pinned memory buffer. Default is true.
     *          \@\@
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\ModelConfig::initOnce();
        parent::__construct($data);
    }

    /**
     *\@\@    .. cpp:var:: bool enable
     *\@\@
     *\@\@       Use pinned memory buffer. Default is true.
     *\@\@
     *
     * Generated from protobuf field <code>bool enable = 1;</code>
     * @return bool
     */
    public function getEnable()
    {
        return $this->enable;
    }

    /**
     *\@\@    .. cpp:var:: bool enable
     *\@\@
     *\@\@       Use pinned memory buffer. Default is true.
     *\@\@
     *
     * Generated from protobuf field <code>bool enable = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setEnable($var)
    {
        GPBUtil::checkBool($var);
        $this->enable = $var;

        return $this;
    }

}

