<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: model_config.proto

namespace Inference\ModelSequenceBatching\Control;

use UnexpectedValueException;

/**
 *\@\@
 *\@\@    .. cpp:enum:: Kind
 *\@\@
 *\@\@       The kind of the control.
 *\@\@
 *
 * Protobuf type <code>inference.ModelSequenceBatching.Control.Kind</code>
 */
class Kind
{
    /**
     *\@\@      .. cpp:enumerator:: Kind::CONTROL_SEQUENCE_START = 0
     *\@\@
     *\@\@         A new sequence is/is-not starting. If true a sequence is
     *\@\@         starting, if false a sequence is continuing. Must
     *\@\@         specify either int32_false_true, fp32_false_true or
     *\@\@         bool_false_true for this control. This control is optional.
     *\@\@
     *
     * Generated from protobuf enum <code>CONTROL_SEQUENCE_START = 0;</code>
     */
    const CONTROL_SEQUENCE_START = 0;
    /**
     *\@\@      .. cpp:enumerator:: Kind::CONTROL_SEQUENCE_READY = 1
     *\@\@
     *\@\@         A sequence is/is-not ready for inference. If true the
     *\@\@         input tensor data is valid and should be used. If false
     *\@\@         the input tensor data is invalid and inferencing should
     *\@\@         be "skipped". Must specify either int32_false_true,
     *\@\@         fp32_false_true or bool_false_true for this control. This
     *\@\@         control is optional.
     *\@\@
     *
     * Generated from protobuf enum <code>CONTROL_SEQUENCE_READY = 1;</code>
     */
    const CONTROL_SEQUENCE_READY = 1;
    /**
     *\@\@      .. cpp:enumerator:: Kind::CONTROL_SEQUENCE_END = 2
     *\@\@
     *\@\@         A sequence is/is-not ending. If true a sequence is
     *\@\@         ending, if false a sequence is continuing. Must specify
     *\@\@         either int32_false_true, fp32_false_true or bool_false_true
     *\@\@         for this control. This control is optional.
     *\@\@
     *
     * Generated from protobuf enum <code>CONTROL_SEQUENCE_END = 2;</code>
     */
    const CONTROL_SEQUENCE_END = 2;
    /**
     *\@\@      .. cpp:enumerator:: Kind::CONTROL_SEQUENCE_CORRID = 3
     *\@\@
     *\@\@         The correlation ID of the sequence. The correlation ID
     *\@\@         is an uint64_t value that is communicated in whole or
     *\@\@         in part by the tensor. The tensor's datatype must be
     *\@\@         specified by data_type and must be TYPE_UINT64, TYPE_INT64,
     *\@\@         TYPE_UINT32 or TYPE_INT32. If a 32-bit datatype is specified
     *\@\@         the correlation ID will be truncated to the low-order 32
     *\@\@         bits. This control is optional.
     *\@\@
     *
     * Generated from protobuf enum <code>CONTROL_SEQUENCE_CORRID = 3;</code>
     */
    const CONTROL_SEQUENCE_CORRID = 3;

    private static $valueToName = [
        self::CONTROL_SEQUENCE_START => 'CONTROL_SEQUENCE_START',
        self::CONTROL_SEQUENCE_READY => 'CONTROL_SEQUENCE_READY',
        self::CONTROL_SEQUENCE_END => 'CONTROL_SEQUENCE_END',
        self::CONTROL_SEQUENCE_CORRID => 'CONTROL_SEQUENCE_CORRID',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

