<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc_service.proto

namespace Inference\CudaSharedMemoryStatusResponse;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *&#64;&#64;
 *&#64;&#64;  .. cpp:var:: message RegionStatus
 *&#64;&#64;
 *&#64;&#64;     Status for a shared memory region.
 *&#64;&#64;
 *
 * Generated from protobuf message <code>inference.CudaSharedMemoryStatusResponse.RegionStatus</code>
 */
class RegionStatus extends \Google\Protobuf\Internal\Message
{
    /**
     *&#64;&#64;
     *&#64;&#64;    .. cpp:var:: string name
     *&#64;&#64;
     *&#64;&#64;       The name for the shared memory region.
     *&#64;&#64;
     *
     * Generated from protobuf field <code>string name = 1;</code>
     */
    protected $name = '';
    /**
     *&#64;&#64;    .. cpp:var:: uin64 device_id
     *&#64;&#64;
     *&#64;&#64;       The GPU device ID where the cudaIPC handle was created.
     *&#64;&#64;
     *
     * Generated from protobuf field <code>uint64 device_id = 2;</code>
     */
    protected $device_id = 0;
    /**
     *&#64;&#64;    .. cpp:var:: uint64 byte_size
     *&#64;&#64;
     *&#64;&#64;       Size of the shared memory region, in bytes.
     *&#64;&#64;
     *
     * Generated from protobuf field <code>uint64 byte_size = 3;</code>
     */
    protected $byte_size = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *          &#64;&#64;
     *          &#64;&#64;    .. cpp:var:: string name
     *          &#64;&#64;
     *          &#64;&#64;       The name for the shared memory region.
     *          &#64;&#64;
     *     @type int|string $device_id
     *          &#64;&#64;    .. cpp:var:: uin64 device_id
     *          &#64;&#64;
     *          &#64;&#64;       The GPU device ID where the cudaIPC handle was created.
     *          &#64;&#64;
     *     @type int|string $byte_size
     *          &#64;&#64;    .. cpp:var:: uint64 byte_size
     *          &#64;&#64;
     *          &#64;&#64;       Size of the shared memory region, in bytes.
     *          &#64;&#64;
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\GrpcService::initOnce();
        parent::__construct($data);
    }

    /**
     *&#64;&#64;
     *&#64;&#64;    .. cpp:var:: string name
     *&#64;&#64;
     *&#64;&#64;       The name for the shared memory region.
     *&#64;&#64;
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     *&#64;&#64;
     *&#64;&#64;    .. cpp:var:: string name
     *&#64;&#64;
     *&#64;&#64;       The name for the shared memory region.
     *&#64;&#64;
     *
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     *&#64;&#64;    .. cpp:var:: uin64 device_id
     *&#64;&#64;
     *&#64;&#64;       The GPU device ID where the cudaIPC handle was created.
     *&#64;&#64;
     *
     * Generated from protobuf field <code>uint64 device_id = 2;</code>
     * @return int|string
     */
    public function getDeviceId()
    {
        return $this->device_id;
    }

    /**
     *&#64;&#64;    .. cpp:var:: uin64 device_id
     *&#64;&#64;
     *&#64;&#64;       The GPU device ID where the cudaIPC handle was created.
     *&#64;&#64;
     *
     * Generated from protobuf field <code>uint64 device_id = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setDeviceId($var)
    {
        GPBUtil::checkUint64($var);
        $this->device_id = $var;

        return $this;
    }

    /**
     *&#64;&#64;    .. cpp:var:: uint64 byte_size
     *&#64;&#64;
     *&#64;&#64;       Size of the shared memory region, in bytes.
     *&#64;&#64;
     *
     * Generated from protobuf field <code>uint64 byte_size = 3;</code>
     * @return int|string
     */
    public function getByteSize()
    {
        return $this->byte_size;
    }

    /**
     *&#64;&#64;    .. cpp:var:: uint64 byte_size
     *&#64;&#64;
     *&#64;&#64;       Size of the shared memory region, in bytes.
     *&#64;&#64;
     *
     * Generated from protobuf field <code>uint64 byte_size = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setByteSize($var)
    {
        GPBUtil::checkUint64($var);
        $this->byte_size = $var;

        return $this;
    }

}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(RegionStatus::class, \Inference\CudaSharedMemoryStatusResponse_RegionStatus::class);

