<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: model_config.proto

namespace Inference\ModelInstanceGroup;

use UnexpectedValueException;

/**
 *\@\@
 *\@\@  .. cpp:enum:: Kind
 *\@\@
 *\@\@     Kind of this instance group.
 *\@\@
 *
 * Protobuf type <code>inference.ModelInstanceGroup.Kind</code>
 */
class Kind
{
    /**
     *\@\@    .. cpp:enumerator:: Kind::KIND_AUTO = 0
     *\@\@
     *\@\@       This instance group represents instances that can run on either
     *\@\@       CPU or GPU. If all GPUs listed in 'gpus' are available then
     *\@\@       instances will be created on GPU(s), otherwise instances will
     *\@\@       be created on CPU.
     *\@\@
     *
     * Generated from protobuf enum <code>KIND_AUTO = 0;</code>
     */
    const KIND_AUTO = 0;
    /**
     *\@\@    .. cpp:enumerator:: Kind::KIND_GPU = 1
     *\@\@
     *\@\@       This instance group represents instances that must run on the
     *\@\@       GPU.
     *\@\@
     *
     * Generated from protobuf enum <code>KIND_GPU = 1;</code>
     */
    const KIND_GPU = 1;
    /**
     *\@\@    .. cpp:enumerator:: Kind::KIND_CPU = 2
     *\@\@
     *\@\@       This instance group represents instances that must run on the
     *\@\@       CPU.
     *\@\@
     *
     * Generated from protobuf enum <code>KIND_CPU = 2;</code>
     */
    const KIND_CPU = 2;
    /**
     *\@\@    .. cpp:enumerator:: Kind::KIND_MODEL = 3
     *\@\@
     *\@\@       This instance group represents instances that should run on the
     *\@\@       CPU and/or GPU(s) as specified by the model or backend itself.
     *\@\@       The inference server will not override the model/backend
     *\@\@       settings.
     *\@\@
     *
     * Generated from protobuf enum <code>KIND_MODEL = 3;</code>
     */
    const KIND_MODEL = 3;

    private static $valueToName = [
        self::KIND_AUTO => 'KIND_AUTO',
        self::KIND_GPU => 'KIND_GPU',
        self::KIND_CPU => 'KIND_CPU',
        self::KIND_MODEL => 'KIND_MODEL',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

