<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: model_config.proto

namespace Inference\ModelInstanceGroup;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\GPBUtil;
use Google\Protobuf\RepeatedField;

/**
 *\@\@
 *\@\@  .. cpp:var:: message SecondaryDevice
 *\@\@
 *\@\@     A secondary device required for a model instance.
 *\@\@
 *
 * Generated from protobuf message <code>inference.ModelInstanceGroup.SecondaryDevice</code>
 */
class SecondaryDevice extends \Google\Protobuf\Internal\Message
{
    /**
     *\@\@  .. cpp:var:: SecondaryDeviceKind kind
     *\@\@
     *\@\@     The secondary device kind.
     *\@\@
     *
     * Generated from protobuf field <code>.inference.ModelInstanceGroup.SecondaryDevice.SecondaryDeviceKind kind = 1;</code>
     */
    protected $kind = 0;
    /**
     *\@\@  .. cpp:var:: int64 device_id
     *\@\@
     *\@\@     Identifier for the secondary device.
     *\@\@
     *
     * Generated from protobuf field <code>int64 device_id = 2;</code>
     */
    protected $device_id = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $kind
     *          \@\@  .. cpp:var:: SecondaryDeviceKind kind
     *          \@\@
     *          \@\@     The secondary device kind.
     *          \@\@
     *     @type int|string $device_id
     *          \@\@  .. cpp:var:: int64 device_id
     *          \@\@
     *          \@\@     Identifier for the secondary device.
     *          \@\@
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\ModelConfig::initOnce();
        parent::__construct($data);
    }

    /**
     *\@\@  .. cpp:var:: SecondaryDeviceKind kind
     *\@\@
     *\@\@     The secondary device kind.
     *\@\@
     *
     * Generated from protobuf field <code>.inference.ModelInstanceGroup.SecondaryDevice.SecondaryDeviceKind kind = 1;</code>
     * @return int
     */
    public function getKind()
    {
        return $this->kind;
    }

    /**
     *\@\@  .. cpp:var:: SecondaryDeviceKind kind
     *\@\@
     *\@\@     The secondary device kind.
     *\@\@
     *
     * Generated from protobuf field <code>.inference.ModelInstanceGroup.SecondaryDevice.SecondaryDeviceKind kind = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setKind($var)
    {
        GPBUtil::checkEnum($var, \Inference\ModelInstanceGroup\SecondaryDevice\SecondaryDeviceKind::class);
        $this->kind = $var;

        return $this;
    }

    /**
     *\@\@  .. cpp:var:: int64 device_id
     *\@\@
     *\@\@     Identifier for the secondary device.
     *\@\@
     *
     * Generated from protobuf field <code>int64 device_id = 2;</code>
     * @return int|string
     */
    public function getDeviceId()
    {
        return $this->device_id;
    }

    /**
     *\@\@  .. cpp:var:: int64 device_id
     *\@\@
     *\@\@     Identifier for the secondary device.
     *\@\@
     *
     * Generated from protobuf field <code>int64 device_id = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setDeviceId($var)
    {
        GPBUtil::checkInt64($var);
        $this->device_id = $var;

        return $this;
    }

}

